### ISSUE TITLE
Rails Sprockets::FileNotFound error "couldn't find file 'i18n'"

### ISSUE THREAD

**Issue by reagleton** [fnando/i18n-js#119]
I followed the instructions to install the gem for Rails 3.2.8 and I keep getting the following error.

I even tried using the rake setup task and that also failed to fix this error.

Where do I find a copy of the relevant file?

PS I just realised that I used Bundler instead of 'gem install'. Could that be the problem?

**Comment by gregblass** [comment]
Getting the same issue here.
