### ISSUE TITLE
Exclude only certain keys

### ISSUE THREAD

**Issue by josepjaume** [fnando/i18n-js#125]
Hi!

I'm working on a Rails App that uses https://github.com/gregbell/active_admin. Since it will clutter the I18n namespace with `activeadmin.*` keys, is there any way to exclude them (the opposite `only` on i`18n-js.yml`)?

I've tried to fiddle a little bit with the code but I can't seem to find a simple way to do it.

Thanks!

**Comment by PikachuEXE** [comment]
It seems someone already came up with a PR: #312

**Comment by PikachuEXE** [comment]
Please check the PR for any issue, will merge next week and release another version
