### ISSUE TITLE
Suggestion: break i18n-js javascript into component files

### ISSUE THREAD

**Issue by johnnyshields** [fnando/i18n-js#163]
Many JS users are concerned about size of their files, every little bit adds up.

It would be useful to break up i18n.js into smaller components which can be selectively included, each extending the I18n prototype. I'd imagine 4 modules would be good:
- translation
- interpolation
- pluralization
- localization

In addition, I'd move the default values for localization (days of week, months of year)  into their own file, since they take up space when most like people will include them in their translation bundle.

**Comment by stgeneral** [comment]
I've missed this issue and opened similar one #289. 

Modular structure is not only about minimizing the file. Core is pretty tiny now but probably it may grow in the future. Modular structure is also about some extra flexibility and a bit more clear code structure (like backend programming practice to place only one class into one file). Probably it would be a good plan for the next major release.

Anyway, thanks for the great gem.
