### ISSUE TITLE
Add some project maintainers

### ISSUE THREAD

**Issue by PikachuEXE** [fnando/i18n-js#170]
There are so many pull requests pending without response
I am sure many people are using this and needs these updates

So I hope the owner @fnando can add a few maintainers (if there is anyone willing to)

**Comment by johnnyshields** [comment]
@fnando can you please add me as a Collaborator? I've been active in terms of PRs and Issue triaging. I won't merge stuff to master but mainly would like to close out fixed/dead issues.
