### ISSUE TITLE
sprockets reports 'can't modify immutable index' in test env on 3.0.0.rc5

### ISSUE THREAD

**Issue by ccmcbeck** [fnando/i18n-js#212]
This seems similar to #89 

Here is my `Gemfile`

    ruby '2.1.1'
    gem 'rails', '4.1.1'
    gem 'i18n-js', '3.0.0.rc5'

Everything seems fine in `development` and `production` (on Heroku), but in the `test` environment I get this:

    $ RAILS_ENV=test rails console
    /Users/chris/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.12.1/lib/sprockets/index.rb:81:in `expire_index!': can't modify immutable index (TypeError)
    	from /Users/chris/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.12.1/lib/sprockets/base.rb:175:in `register_preprocessor'
    	from /Users/chris/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/i18n-js-3.0.0.rc5/lib/i18n/js/engine.rb:11:in `block (2 levels) in <class:Engine>'

Here it the code in `engine.rb` beginning at line 11

    Rails.application.assets.register_preprocessor "application/javascript", :"i18n-js_dependencies" do |context, source|
      next source unless context.logical_path == "i18n/translations"
      ::I18n.load_path.each {|path| context.depend_on(path)}
      source
    end

I don't get the error when I use this in my `Gemfile`

    gem 'i18n-js', :git => 'https://github.com/fnando/i18n-js.git', :branch => 'rewrite'

Unfortunately, that version doesn't work for me.  It doesn't regenerate the asset in `development` when I modify a locale file.

In both cases, `I18n::JS.has_asset_pipeline? => true`

I'm able to reproduce this on two different computers

**Comment by PikachuEXE** [comment]
@GCorbel Sorry for seeing this late
Do you still have issue with this error?

**Comment by GCorbel** [comment]
No, it works now. Thanks.
