### ISSUE TITLE
Missing new translation after a new locale added

### ISSUE THREAD

**Issue by elpic** [fnando/i18n-js#213]
After I made a deploy with capistrano all the new translations are not available. To make it work I should clear the cache and redeploy

**Comment by arion** [comment]
Still had a problem with this. Capistrano task: (https://gist.github.com/arion/d1afafbe065d7d669ef9)

**Comment by PikachuEXE** [comment]
@arion 
Have you tried `rake tmp:cache:clear` as well?
I am not sure what works for clearing sprockets cache.
It would be great if documentation links can be found.

**Comment by PikachuEXE** [comment]
I will reopen until you solve it

**Comment by ryanb** [comment]
This is an old issue, but thought I'd share my solution. While it isn't possible to add a directory using the `//= depend_on` directive in Sprockets, you can add it to the context directly which will cause it to detect new files. I'm doing this at the top of my own `translations.js.erb` asset file.

```rb
<%
  depend_on Rails.root.join("config", "locales").to_s
  Dir.glob(Rails.root.join("config", "locales", "**", "*.yml")) do |path|
    depend_on path
  end
%>
```

If you want to update this project, you could do this in the `engine.rb` preprocessor or in `filtered.js.erb`.
