### ISSUE TITLE
Is there something like I18n.default_scope?

### ISSUE THREAD

**Issue by phillipoertel** [fnando/i18n-js#232]
This is a question or feature request rather than a bug:

We store all translations for JS in the scope de.client.js. Is it possible to configure the JS for I18n so that it automatically looks for all translations in that scope, without having to supply it with all I18n.t calls? That would be very useful for us.

Example:

// Ruby
I18n.t('de.client.js.foo') # => bar

// JS
I18n.default_scope = "de.client.js";
I18n.t('foo'); # => bar

Thanks and kind regards,
Phillip

**Comment by lesliev** [comment]
I did this slightly differently - I added a helper that I can put into my views:
```ruby
    # Define a Javascript I18n.lt function that allows us to set a prefix in a view, eg:
    # = js_local_translate('admin.assessors.assessment_rounds.components')
    #
    # Then we can use much shorter keys eg:
    # I18n.lt('assessment_round.update')
    #
    def js_local_translate(prefix)
      "<script>
          I18n.lt = function(scope, options = {}) {
            return I18n.t(scope, Object.assign(options, {scope: '#{prefix}'}));
          }
       </script>".html_safe
    end
```

The advantage is that it doesn't interfere with using `I18n.t` for full paths. 
In any case, it would be nice if i18n-js supported something like Rails lazy-lookup: http://guides.rubyonrails.org/i18n.html#lazy-lookup

**Comment by PikachuEXE** [comment]
"lazy-lookup" is based on template path, but there is no template path in JS
