### ISSUE TITLE
translations.js is being generated differently between different machines

### ISSUE THREAD

**Issue by rafaelgaspar** [fnando/i18n-js#239]
The order of the keys are different.

This can't happen with Asset Pipeline, otherwise my application.js is going to be different across my app servers, and that causes a different asset fingerprint.

I'm trying to look further into this, but still haven't figured after what commit this started happening, will update if I find something.

**Comment by PikachuEXE** [comment]
Someone has kindly submitted a PR: #318
So I guess now would be great to discuss and decide what we want:
- sorted translation to ensure consistency for translation files generated on different machines
- keep translation unsorted, resolve by chaning gems like [`russian`](https://github.com/yaroslav/russian/) 
- **both** (with option), default unsorted

**Comment by Envek** [comment]
Second case (just keep unsorted) is not an option as it's hard to patch all the gems (especially not actively maintained ones, see yaroslav/russian#56, there are still no feedback). And I saw a lot of neglected gems recently.
I think current behavior (unsorted) with option enabling sorting will satisfy everyone. Good explanation in README is required too.
Personally, I do not care for order of keys at all.

@msjonker, can you please tell you opinion? And thanks for pull request!

**Comment by msjonker** [comment]
The only reliable solution we found to ensure consistent asset fingerprints was to sort prior to JSON. I agree that this could be turned on as an option, for those who don't want this. However, I don't think the sorting of the JSON should have any adverse effects, aside from the extra processing.

**Comment by PikachuEXE** [comment]
I guess we can add it as an option, but warn about this "unsorted" behaviour until next major version
And then always sort it for next major version (if no one objects)
That option can be default to true (since they can set it back and we are still in `rc`)

**Comment by msjonker** [comment]
That works for me.

**Comment by PikachuEXE** [comment]
#318 is almost done.
Could you guys review it (or even try it) to see if that's what you want.
Once reviewed I will merge.

**Comment by Envek** [comment]
Looks good for me, but can't battle test it now.

**Comment by PikachuEXE** [comment]
I will wait until you have battle test it :clock3:

**Comment by Envek** [comment]
Well, I don't sure that I will be able to battle test it all — we are no more working on the machines where I've noticed this.

**Comment by PikachuEXE** [comment]
@rafaelgaspar Are you able to test #318?

**Comment by rafaelgaspar** [comment]
Sorry, I ended up having to scope my JS translations better to avoid this bug, so I can't reproduce it anymore in my app.

**Comment by PikachuEXE** [comment]
Well then I will just merge it.

**Comment by PikachuEXE** [comment]
Closing since #318 merged
Reopen if you can prove it doesn't work
