### ISSUE TITLE
Add support for currency codes

### ISSUE THREAD

**Issue by jfbrennan** [fnando/i18n-js#250]
Great library, really appreciate it!

One tiny missing piece is support for currency codes (http://www.xe.com/iso4217.php).

What I would like to be able to do:

//in my config file
        "currency": {
            "format": {
                "unit": "$",
                "code": "USD",
                "precision": 2,
                "format": "%c%u%n"
            }

Which would produce "USD$1,000.00"

There are other locales where you would need to set the format like this: "%n%c"  to get "100 SEK" for example.

I think all that is required is to add this line of code in a few places:

```
    .replace("%c", options.code)
```

**Comment by johnnyshields** [comment]
@jfbrennan I believe locale and currency should be two separate concepts. In other words, there is not a 1:1 relationship between language and currency. So my vote would be to not add this feature to this gem.

**Comment by espen** [comment]
This is not supported in [I18n rails](http://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_to_currency) btw. There is just unit. You could include the code in the unit as well. I'm not sure how often there is a need to separate the two: "SEK 100 kr"? One option is to use two operations and do a translate and a toCurrency: `I18n.t('number.currency.format.code') + ' ' + I18n.toCurrency(1000);`
