### ISSUE TITLE
Add ability to compile assets even if `config.assets.initialize_on_precompile = false`

### ISSUE THREAD

**Issue by cbliard** [fnando/i18n-js#257]
I want to precompile assets to create a suitable Docker image. When `config.assets.initialize_on_precompile = true`, app cannot be started because there is no database yet. When `config.assets.initialize_on_precompile = false`, i18n-js complains that environment is not initialized, meaning `I18n` is not fully loaded.

I tried to keep `config.assets.initialize_on_precompile = false` and load `I18n` manually. I added the following code to `config/application.rb`

```
module I18nInitializerWorkaround
  class Railtie < Rails::Railtie
    initializer "i18n_initializer_workaround", :group => :assets do |app|
      config.i18n.railties_load_path.concat(App::Application.paths["config/locales"].existent)
      ::I18n::Railtie.initialize_i18n(app)
    end
  end
end
```

The above code is inspired from `I18n::Railtie` and the `:add_locales` initializer in `Rails::Engine`. I am running Rails 3.2.19 and i18n-js 2.1.2.

After neutralizing `SimpleIdeias::I18n#assert_usable_configuration!`, precompiling assets while `config.assets.initialize_on_precompile = false` seems to work.

Do you think this is a suitable fallback? If so I can create a pull request to load I18n instead of raising an exception in `assert_usable_configuration!`

**Comment by gaga5lala** [comment]
Hi @cbliard, I have same problem when building docker image, I've added `module I18nInitializerWorkaround` to `config/application.rb and` set `config.assets.initialize_on_precompile = false` in both staging and production. But still have an error of no database connection when executing `bundle exec rake i18n:js:export`. Do I have something wrong? Thanks.

**Comment by pietschy** [comment]
Hi @gaga5lala, we had the same issue and solved it by creating separate environment for our docker builds and using https://github.com/nulldb/nulldb as the database.

**Comment by gaga5lala** [comment]
@pietschy thanks for info!!

I found a blog post about using nulldb avoid db connection when assets precompile as you said, it works!
http://blog.zeit.io/use-a-fake-db-adapter-to-play-nice-with-rails-assets-precompilation/

**Comment by cbliard** [comment]
Hi @gaga5lala, I checked how we do it, and I do not have any `I18nInitializerWorkaround` module left. Instead, I have this monkey-patch:

```
# override i18n-js code
module SimplesIdeias
  module I18n
    def assert_usable_configuration!
      true
    end
  end
end
```

The `assert_usable_configuration!` check was introduced in 9f7a094 (in 2011) and was recently removed in 12fe8ec2 for v3.0.0.rc15. This check prevents using `config.assets.initialize_on_precompile = false`.

We are still using 3.0.0.rc14, so it may be why you see an error and we do not.

I think the nulldb approach of @pietschy is better than monkey-patching the i18n-js lib.

**Comment by andrewzah** [comment]
Any chance of getting this fixed without requiring an additional dependency via nulldb?

**Comment by sAnti09** [comment]
@andrewzah I tried it and it worked. If there are some initializers that reference the mysql adapter class, wrap them with a conditional statement so they would only be executed if the adapter is nondb. In this way, I was able to create a docker image successfully.
