### ISSUE TITLE
How to use from a engine

### ISSUE THREAD

**Issue by timoschilling** [fnando/i18n-js#262]
I want to use `i18n-js` inside of a engine (for example `activeadmin`, but could be each other rails engine), now I see one problems:
1. How can I configure `i18n-js` from inside of a engine? The readme shows a [export configuration](https://github.com/fnando/i18n-js#export-configuration), but they only works for inside the app and not from inside a engine!

**Comment by johnnyshields** [comment]
@timoschilling would an acceptable solution be if the `I18n::JS.export` method were to merge all `i18n-js.yml` files from each engine's config dir?

**Comment by timoschilling** [comment]
@johnnyshields Thats options. A other solution could be to configure per ruby:
```ruby
I18n::JS.configure do |config|
  config.xxx = "..."
end
```

**Comment by johnnyshields** [comment]
I think it's better to auto-detect engine locale files (assuming the engines are loaded at the time the `I18n::JS.export` runs.) Would you be able to raise a PR for this?

**Comment by timoschilling** [comment]
I can work on that if I find some time.

**Comment by raszi** [comment]
:+1:

**Comment by johnnyshields** [comment]
@timoschilling can you please review PR #295 which is work in progress? Please close this issue in favor of the PR if you're happy with the direction of it.

**Comment by PikachuEXE** [comment]
Close issue after PR is merged / tested, not before

**Comment by PikachuEXE** [comment]
Please check #326

**Comment by PikachuEXE** [comment]
@raszi @timoschilling 
Please take a look at https://github.com/fnando/i18n-js/pull/326#issuecomment-165390302
Which might solve this issue
