### ISSUE TITLE
couldn't find file 'i18n' 

### ISSUE THREAD

**Issue by Saicheg** [fnando/i18n-js#283]
Hey!

I tried version 3.0.0.rc8 on my project with rails 4.2.beta4 and faced with the next error

```
Sprockets::FileNotFound (couldn't find file 'i18n' (in /projects/name/app/assets/javascripts/application.js:3)):

```

Any ideas of what it can be?

**Comment by zeitnot** [comment]
@cpence same problem. So me to :)

**Comment by zeitnot** [comment]
@PikachuEXE I have downgraded to rails `4.1.9` from `4.2.*`. So it seems that it works with `rails < 4.2`.

**Comment by PikachuEXE** [comment]
Does `//= require i18n` resolve it?
I am busy until the middle of March :S

**Comment by zeitnot** [comment]
With `rails < 4.2` yes. With `rails 4.2+` no.

**Comment by kevin-bonnin** [comment]
I finally got it to work with rails 4.2+

You need to `//= require i18n.js` instead of `//= require i18n`. I still don't really get why, but I had a similar issue with older versions of sprockets and other gems so I gave it a try and it worked.

**Comment by zeitnot** [comment]
@kevin-bonnin +rep :)

**Comment by PikachuEXE** [comment]
So we confirmed that the `//= require i18n` should be replaced by `//= require i18n.js`?
I can update the README if so.

Also do we need the `.js` suffix for `i18n/translations`?

**Comment by johnnyshields** [comment]
@kevin-bonnin @zeitnot can you please answer @PikachuEXE's question so we can close this issue?

**Comment by kevin-bonnin** [comment]
@PikachuEXE, @johnnyshields this is what I use and it's working fine:

```javascript
//= require i18n.js
//= require i18n/translations
```

**Comment by PikachuEXE** [comment]
I will put it in README

**Comment by PikachuEXE** [comment]
Added in 78030390e36529b2611f960bda88df1d9e01aafd
Anymore action needed?

**Comment by kevin-bonnin** [comment]
@PikachuEXE  nope I think you can close, thanks :D
