### ISSUE TITLE
Properly error if invalid key or missing placeholders given

### ISSUE THREAD

**Issue by MaryBartlett** [fnando/i18n-js#285]
It would be really useful to throw an error if an invalid key or missing placeholder is given;
e.g. 
i18n.t('abc') where 'abc' doesn't exist - get error 'translation for 'abc' missing';
i18n.t('string with {{placeholder}}', {cat: 'dog'}); - get error 'placeholder missing, received {cat: 'dog'}'

At the moment, missing translations and placeholders do return a message that there has been an error, but unfortunately that message is a string so without further interpretation it isn't easy to see there's been an issue. 
"[missing "en-GB.abc" translation]"
"[missing {{placeholder}} value]"

**Comment by johnnyshields** [comment]
Maybe this should be a console warning?

**Comment by PikachuEXE** [comment]
How to log an error without breaking any browser compatibility?
I have zero knowledge for browser logging (of errors).
You know the famous IE...

**Comment by johnnyshields** [comment]
One options would be to provide an onError callback into the I18n.js initializer. This could be then raised however the user feels appropriate.

**Comment by TrevorBurnham** [comment]
I'd enjoy this feature as well. You could add an optional callback to `options`, e.g.

```js
I18n.missingTranslation = function(scope, options) {
  ...
  
  if (typeof options.onMissingTranslation === 'function') {
    options.onMissingTranslation(fullScopeWithLocale);
  }

  return '[missing "' + fullScopeWithLocale + '" translation]';
};
```

If you'd like, I can submit a pull request.

**Comment by MaryBartlett** [comment]
Yes I'd be happy for you to take a look at this! I meant to when I raised it but had forgotten about it!
