### ISSUE TITLE
Ensure the Rails.root/tmp/cache dir exists

### ISSUE THREAD

**Issue by Azdaroth** [fnando/i18n-js#291]
If ``` Rails.root/tmp/cache ``` directory doesn't exist, the app booting process fails with No such file or directory error (see: https://github.com/fnando/i18n-js/blob/fcbcb528dfe1689cf8c26c1b494d471526732713/lib/i18n/js/middleware.rb#L35). Not a problem when running app with ```rails server``` which creates tmp/cache, but it's going to fail with eg. pow (http://pow.cx).

**Comment by PikachuEXE** [comment]
I don't know why it happens since the line `L34` should create the directory already.
Can you try to fork and edit the code to see what works for you?

**Comment by Azdaroth** [comment]
Oh, sorry, I thought I was using the up-to-date version which was not the case. L34 indeed solves the problem.
