### ISSUE TITLE
Rails 3, doesn't seem to pickup "new" stuff I put in en.yml

### ISSUE THREAD

**Issue by rstudner** [fnando/i18n-js#303]
Okay.. very strange.

Using the library, everything was working great.

All of a sudden, if I add things to en.yml they don't show up in the I18n.translations.

It seems to be fixed in time/stuck and i'm not sure how to kick it :)

**Comment by rstudner** [comment]
I ran a bundle exec rake assets:precompile and now I appear to be seeing my updates....

But if I make 'newer' updates .. it again doesn't seem them.  Hrmph.

**Comment by PikachuEXE** [comment]
Are you talking about in development or production?
Is `rake assets:precompile` run on deployment after `en.yml` is modified? (if production)

**Comment by gmccullough** [comment]
I believe I'm running into the same issue. Any edits to config/locals/*.yml aren't reflected in filtered.js unless I stop my server, run rake assets:clean, and restart the server. Seems like this shouldn't be necessary. This is in development.

I just started to use this gem and ran into this issue, so I may have some sort of misconfiguration on my end. Any suggestions?

**Comment by PikachuEXE** [comment]
Which version of the gem are you using?
All README is for the `rc` versions of the gem, not official version will be released soon :S

**Comment by rstudner** [comment]
I'm using the 0.12.2/latest stable gem at the moment.  building the 1.0.0 pre8 one right now to try it as well.

**Comment by gmccullough** [comment]
I'm using 3.0.0.rc8

**Comment by jesperronn** [comment]
@rstudner @gmccullough in #306 I learned to run `rake tmp:cache:clear`, which finally helped me reload the translations. I also tried `rake assets:clobber` and `rm public/javascripts/translations.js` and updating my yaml files but that was in vain.

I have now set our ci-build up to clear cache before it precompiles assets with `rake tmp:cache:clear`.
