### ISSUE TITLE
missingTranslation does not take options scope into account

### ISSUE THREAD

**Issue by rubylibre** [fnando/i18n-js#309]
For example:
when en.activerecord.attributes.post.title is missing,
and options is:
```
var options = { scope: activerecord.attributes.post }
```
when calling:
```
I18n.t('title', options);
```
the message returned by missingTranslation is:
```
[missing "en.title" translation]
```

**Comment by PikachuEXE** [comment]
Fixed by 0f5e7448edf8c3a7ac2e9f4f77090fec7fc9ffab
Feel free to reopen if you got more cases not covered yet
