### ISSUE TITLE
Mimic rails behaviour: ..._html (embedded HTML in translation)

### ISSUE THREAD

**Issue by SqueezedLight** [fnando/i18n-js#310]
Hi guys, 
i'm trying to translate a text with a HTML link in it. At the moment i have:

`accept_terms_html: "Accept our <a href='#'>%{terms}</a>."`

But it doesn't work with this:
`I18n.t("loginpage.accept_terms_html", { locale: locale,
				        																terms: I18n.t("loginpage.terms_href", {locale: locale}) })`

The `terms` and `locale` params are passed as expected, but the HTML tags are not interpreted as HTML. I18n-js seems to return a string, despite xxx_html should mark it as html_safe (rails behaviour). 

Is there a way to mimic the rails behavior?

Thanks in advance

**Comment by PikachuEXE** [comment]
I don't understand what thing you are trying to do with this gem.
HTML is escaped in rails template. (HAML, ERB, SLIM, etc.)
But in JS (with asset compling) there is no HTML escaping right?
So what do you mean by `the HTML tags are not interpreted as HTML`?

**Comment by SqueezedLight** [comment]
I try to translate a text with html links in it, but the tags are escaped. That's the problem...

**Comment by SqueezedLight** [comment]
Sorry guys, found it. I'm using react and it was actually a problem with inserting html into jsx. Found the solution here: https://facebook.github.io/react/docs/jsx-gotchas.html

@PikachuEXE: Thanks for your help. Your comment made me thinking about the principles again :)

**Comment by dmitry** [comment]
@SqueezedLight :+1: forgot about that recently. This issue pushed me to remember :)

**Comment by scott-knight** [comment]
I have this same issue using native js

**Comment by PikachuEXE** [comment]
@scott-knight 
Again whatever string you pass into I18n (JS) it will return the same content
No HTML escaping is done
If you still think I18n is causing the issue please describe more

**Comment by scott-knight** [comment]
@PikachuEXE - sorry, i didnt mean to imply that it wasn't producing text as expected. What I was trying to state was that the output was not the same as the native Rails way of escaping a translation. in the en.yml file you can use a key and string `example_key_html: "This is an <strong> example</strong>"` and Rails will produce the output with element in the DOM. The I18n.js version merely outputs the entire thing as a string. I was hoping there was a way that the JS translator would do the same thing.

**Comment by PikachuEXE** [comment]
Hmmm so you mean in JS with your example:
```js
I18n.t("example_key_html");
```
is giving a string different from `This is an <strong> example</strong>`?

**Comment by scott-knight** [comment]
@PikachuEXE - no, it is giving me the string as a string with the html elements included.if you go here: http://guides.rubyonrails.org/i18n.html in section 4.4 - this is what I am after. It would be great if the i18n-JS could mimic what rails does.

**Comment by PikachuEXE** [comment]
So you **do** want HTML escape?
I don't think that's what this JS lib would provide...

**Comment by confiks** [comment]
So the behaviour with Rails ERB and React is pretty much the same: they both escape HTML special characters to 'character entities' when rendered (i.e. `<` becomes `&lt;`).

As @SqueezedLight describes, Rails has a feature that when you use a translation YAML key with the suffix `_html`, and you look up that translation, the ActiveSupport method `html_safe` gets called on the string, and when you output that string in ERB (`<%= some_safe_string %>`), the special characters are left alone (as the string is considered safe).

React obviously hasn't overloaded Javascript strings with some `html_safe?` property, but I18n could choose to use `dangerouslySetInnerHTML` to get the same effect. In a past codebase, I did something like this:

```
import i18n from 'i18n-js';
import escapeTextContentForBrowser from 'react/src/renderers/dom/shared/`';
import _ from 'lodash';

const translate = (scope, interpolations) => {
  if(!scope.endsWith('_html'))
    return i18n.t(scope);

  const escapedInterpolations = _.mapValues(interpolations, escapeTextContentForBrowser);
  return <span dangerouslySetInnerHTML={{ __html: t(scope, escapedInterpolations) }} />;
}
```

So the while the translation is clearly marked to be safe in the YAML file with the `_html` prefix, the  interpolations to the translation function may contain user-controlled data, and are escaped with React's `escapeTextContentForBrowser`.
