### ISSUE TITLE
String Interpolation Not Working

### ISSUE THREAD

**Issue by activestylus** [fnando/i18n-js#313]
Given:

```
add_n_items: "Add {{n}}" items
```

When I run:

```
I18n.t('add_n_items')
```

It outputs `"Add {{n}} items"`

I even tried the new way (Rails >=3) `"Add %{n} items"`, but no dice

**Comment by PikachuEXE** [comment]
Wait, have you give `n` in the method call? Like
```javascript
 I18n.t('add_n_items', {n: 1})
```

**Comment by activestylus** [comment]
OK so I did that and instead of returning a string it returns an object. Here is a real world example:

```javascript
I18n.t('add_tracks',{n:3});
//=> {one: "Add 1 Track", other: "Add {{n}} Tracks", zero: "Add Tracks"}
```

Here is the relevant translation from my locale file:

```yaml
add_tracks:
    one: "Add 1 Track"
    other: Add {{n}} Tracks
    zero: Add Tracks
```

Given your documentation I had assumed that I could simply call I18n.t('add_tracks',{n:3}) and get the "Add 3 Tracks" as a string. Instead, to get the interpolation to work, I must do it like this:

```javascript
I18n.t('add_tracks.other',{n:3});
```

Which makes sense as we don't want to have the t function do unexpected things. Perhaps what this lib needs is a native pluralize method? I18n.p('add_tracks',3)

**Comment by PikachuEXE** [comment]
Please look spec starting at 
https://github.com/fnando/i18n-js/blob/master/spec/js/interpolation.spec.js#L23
and translation at
https://github.com/fnando/i18n-js/blob/master/spec/js/translations.js#L27

The interpolation plus pluralization only occurs an option named `count` is passed in AND the translation key provided leads to an object.

**Comment by PikachuEXE** [comment]
This is aligning to the behaviour of `i18n` gem, which also looks for option `count`.
See https://github.com/svenfuchs/i18n/blob/master/lib/i18n/backend/base.rb#L31

**Comment by activestylus** [comment]
Thanks for clarifying - I wasn't aware of this behavior with the ruby gem and it is pretty handy!

Cheers
