### ISSUE TITLE
RequireJS optimization doesn't correctly detect define method in i18n.js

### ISSUE THREAD

**Issue by thegillis** [fnando/i18n-js#314]
I'm currently incorporating the i18n-js gem into my project. We currently export translations and use the requirejs-rails gem to load the i18n.js file from the server. We then will use the r.js optimization tool to assemble all of our dependencies into one JS file.

Although the contents of the i18n.js file are included in this r.js optimized version, it does not correctly detect the define method and appends a "shim" define at the end. Unfortunately this causes the I18n JS object to be inaccessible. I have tracked the problem down to the global closure inside the define call.

Steps to reproduce (current version of r.js included in the latest requirejs-rails gem on ubuntu server with packages nodejs npm):

```
wget 'https://raw.githubusercontent.com/jwhitley/requirejs-rails/0.9.5/bin/r.js'
# master copy as of 3/11/2015
wget 'https://raw.githubusercontent.com/fnando/i18n-js/f67fa51427dd004b43f20c46c4016a71012d6699/app/assets/javascripts/i18n.js'
# Optimized version
nodejs r.js -o baseUrl=. name=i18n out=i18n-optim.js
# Non-optimized version
nodejs r.js -o baseUrl=. name=i18n out=i18n-nooptim.js optimize=none
```

If you view the i18n-nooptim.js file, the last line is:

```
define("i18n.js", function(){});
```

Unfortunately this causes all require statements to return undefined for the 'i18n' dependency:

```
require(['i18n'], function(I18n) {
  I18n.t('true'); // FAIL
});
```

This is also identical to the most recent development copy of the r.js tool:

```
# master as of 3/11/2015
wget -O r.2.1.16.js 'https://raw.githubusercontent.com/jrburke/r.js/443809bfe5d668bf4217c4f26b4636011cf91aa6/dist/r.js'
nodejs r.2.1.16.js -o baseUrl=. name=i18n out=i18n-16-optim.js
nodejs r.2.1.16.js -o baseUrl=. name=i18n out=i18n-16-nooptim.js optimize=none
```

You will notice that the i18n-16-nooptim.js and i18n-16-optim.js files suffer from the same problem.

The fix is to replace the line:

```
define('i18n', (function(global){ return function(){ return factory(global); }})(this));
```

With:

```
var global=this;
define('i18n', function(){ return factory(global);});
```

I believe that these are functionally identical, but I'm not sure about the original intention for this define statement statement, so I'm not sure if it will violate any edge cases. It's even fewer bytes :)

I'll create a pull request as an example fix.

**Comment by thegillis** [comment]
Notes:

This issue appears to be similar to this problem:
https://github.com/jrburke/r.js/issues/704

In this case though it was happening with jQuery.

I was not able to follow the change to the parser to figure out how it relates to this problem.

**Comment by johnnyshields** [comment]
@thegillis if we add ES6 module support to this library, does it fix your issue?
