### ISSUE TITLE
Travis fails during build: No default rake task

### ISSUE THREAD

**Issue by jesperronn** [fnando/i18n-js#316]
It seems that Travis fails builds with the message as you can see from the build in #258 

Rake cannot find a default task. SEe this build for and example:

* https://travis-ci.org/fnando/i18n-js/builds/37231142

(ran 4 hours ago)

@fnando, I think  you can fix Travis by changing `rake` to `rake test`, `rake spec` or similar

**Comment by PikachuEXE** [comment]
Fixed in 9c708415872068a84696c1ad136daf51b172b107
