### ISSUE TITLE
toNumber precision and significant concepts

### ISSUE THREAD

**Issue by efqdalton** [fnando/i18n-js#323]
This function is working like old Rails number_to_human helper, precision parameter is handled like a significant and not like a real precision.

Rails changed this behavior some time ago, and I think that the concept of precision and significant makes more sense than handling wrongly precision as significant.

Look at number helper Rails reference at:
[number_to_human](http://api.rubyonrails.org/classes/ActiveSupport/NumberHelper.html#method-i-number_to_human)

And look at Rails tests to see the difference more clearly at:
[number_helper_test.rb](http://github.com/rails/rails/blob/081a3963ea2aab617a92874d7ef59ce98eee6a64/activesupport/test/number_helper_test.rb)

**Comment by PikachuEXE** [comment]
So you are suggesting to change the behaviour of `toNumber` to follow the latest rails helper behaviour?

**Comment by efqdalton** [comment]
Exactly! I believe that it's a good idea for two reasons:

1. Mathematically, make sense calling precision as the "scientific correct precision" (sometimes, the last n digits after separator aren't important, but we can say something about how many significant digits we have), but still is interesting to provide the concept of number of digits after separator for cases that expects it (for money amounts, for example)

2. Symmetry, since a lot of this project is clearly inspired on I18n used at Rails, it's interesting to follow the same behaviour, being friendlier to devs.

What do you think?

**Comment by PikachuEXE** [comment]
I agree we should stick to the current rails behaviour, unless we have a stronger reason not to.
Could you please check if they plan to change it again in rails 5? (although by then `3.x` might be released already)
If not we can start implementing it (wait, need to copy rails test first :D)

**Comment by johnnyshields** [comment]
+1 for correcting this to match rails

**Comment by flyingL123** [comment]
Rails 4 allows you to pass a `:units` argument to the `number_to_human` method. This can be a string representing a scope that refers to another hash in the locale file that tells rails which units to use. For example, if my locale file has this hash:

    area:
      unit:
        one: "square feet"
        other: "square feet"

Then I can call `number_to_human(28.5, units: :area)`.  Does this i18n-js have a function that provides similar support? For example does `toNumber` accept a `units` argument that would work the same way as it does in rails?

**Comment by PikachuEXE** [comment]
I think `number_to_human` (Ruby) should be implemented on a separate function (JS)
instead of putting it into `toNumber`

**Comment by flyingL123** [comment]
I was just trying to think through how that would work. Would it essentially just call `toNumber` to get the number value and then append the units by looking up the appropriate value from the `units` option passed in?

**Comment by PikachuEXE** [comment]
Maybe similar to [`toCurrency`](https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js#L590)

**Comment by flyingL123** [comment]
I added the following function to the version of i18n in my project. It's working for me, but I could use some help cleaning it up. Any chance you have time to take a look?

	I18n.numberToHuman = function(number, options) {
	  // If a 'units' option is passed in, use it
	  // to determine what 'unit' should be used.
	  // Units can be a hash or a string that points
	  // to a hash in the translations hash.

	  var increments = {
		milli: 0.001,
		centi: 0.01,
		deci: 0.1,
		unit: 1,
		ten: 10,
		hundred: 100,
		thousand: 1000,
		million: 1000000,
		billion: 1000000000
	  };

	  var unitsHash =
		typeof options.units == "string" ?
		this.lookup(options.units) : options.units;

	  if (typeof unitsHash != "undefined") {
		// The unit to be used.
		// It should be the largest unit
		// that has an increment value less than
		// or equal to the number. For example,
		// 50 would useUnit 'unit', and 800
		// would useUnit 'hundred'.
		var useUnit;

		// The smallest unit in the unitsHash.
		// We need this in case the number is less
		// than the smallest unit.
		var smallestUnit;
		for (var unit in unitsHash) {
		  if (unitsHash.hasOwnProperty(unit)) {
			if (typeof smallestUnit == "undefined" || increments[unit] < increments[smallestUnit]) {
			  smallestUnit = unit;
			}

			if (number >= increments[unit]) {
			  useUnit = unit;
			}
		  }
		}

		if (typeof useUnit == "undefined") {
		  useUnit = smallestUnit;
		}

		number = number / increments[useUnit];
	  }

	  options = this.prepareOptions(
		options,
		this.lookup("number.format"),
		{unit: "", precision: 2, format: "%n %u", delimiter: ",", separator: "."}
	  );

	  number = this.toNumber(number, options);

	  if (typeof useUnit != "undefined") {
		var key;
		if (number == 1) {
		  key = 'one';
		}
		else if (number == 0 ) {
		  key = 'zero';
		}
		else {
		  key = 'other';
		}

		options.unit = unitsHash[useUnit][key];
	  }

	  number = options.format
		.replace("%u", options.unit)
		.replace("%n", number)
	  ;

	  return number;
	};

**Comment by PikachuEXE** [comment]
Before cleaning up the code, it's better to have a spec.
I might be best to just fork this repo and add your version of code & spec, then we can see what needs to be changed / clean up :smile:

**Comment by fnando** [comment]
Given that v4 now handles this properly by using https://www.npmjs.com/package/bignumber.js, I'm going to close this one.
