### ISSUE TITLE
Is 3.0.0.rc8 considered Rails 4 ready? 

### ISSUE THREAD

**Issue by 11mdlow** [fnando/i18n-js#328]
The README lists Rails 3.2, so I just wanted to be sure. Our team is in the midst of a Rails 3 --> 4 upgrade and needed a released version of this gem that's ready for Rails 4

**Comment by PikachuEXE** [comment]
Yes I am using it on rails 4.1
The chance of breaking actually depends on `sprockets` most of the time around caching

**Comment by PikachuEXE** [comment]
Does that answer your question?

**Comment by 11mdlow** [comment]
ah sorry, forgot to close out the issue. yep! that answers it!
