### ISSUE TITLE
Error when saving to cache

### ISSUE THREAD

**Issue by andresgap** [fnando/i18n-js#330]
We encounter this error when trying the save to the cache folder if the folder already exists. See log: 
Errno::EEXIST - File exists @ dir_s_mkdir - /.../tmp/cache:
  /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
  /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
  /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
  /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
  i18n-js (3.0.0.rc8) lib/i18n/js/middleware.rb:34:in `save_cache'
  i18n-js (3.0.0.rc8) lib/i18n/js/middleware.rb:62:in `verify_locale_files!'
  i18n-js (3.0.0.rc8) lib/i18n/js/middleware.rb:10:in `call'

I added the following PR to solve this: https://github.com/fnando/i18n-js/pull/329/files.

**Comment by PikachuEXE** [comment]
OK I guess #329 is related to this, please mention the issue in PR next time
As I commented in #329, it "should" do nothing if it exists already

But by reading the code of ruby, it raises error if file is NOT a directory
So maybe there is a part in the path `/www/d360/releases/20150522230303/tmp/cache` is a file?

**Comment by andresgap** [comment]
Yes, 'cache' is a symbolic link.

**Comment by PikachuEXE** [comment]
OK, please follow the comments at #329

**Comment by andresgap** [comment]
Done, please check

**Comment by PikachuEXE** [comment]
Why are you commenting here lol
Merging

**Comment by PikachuEXE** [comment]
Closed for #329

**Comment by andresgap** [comment]
Thanks, quick question when rc9 is going to be release?

**Comment by PikachuEXE** [comment]
Commented in #329 o_0
