### ISSUE TITLE
Where should the logic of filtering translations (opiton only & exclude) moved to?

### ISSUE THREAD

**Issue by PikachuEXE** [fnando/i18n-js#333]
From https://github.com/fnando/i18n-js/pull/326#issuecomment-109147685

`Segment` seems to be a good candidate.

**Comment by johnnyshields** [comment]
My PR here #319 is intended as a first step to cleaning up all this logic--I think the first thing to do is to move it out of the I18n::JS module and into a new temporary module called I18n::JS::Exporter. We can then break the Exporter into even smaller classes.

**Comment by PikachuEXE** [comment]
Filtering != exporting
`Segment`?

**Comment by johnnyshields** [comment]
> Filtering != exporting

Yes, I am aware, but I think the first step is to extract all the logic currently in the main file `I18n::JS` into it's own bucket. Afterwards we can move it to the `Segment` or possibly a new `Filter` class.

**Comment by PikachuEXE** [comment]
I guess let's talk about it after #326 is done, that one is more ... imminent?
