### ISSUE TITLE
rake i18n:js:export command does not work in rails 4.2.1

### ISSUE THREAD

**Issue by barcala** [fnando/i18n-js#335]
I'm trying to configure i18n-js gem in rails 4.2.1 and trying to follow installation instructions I get an error when running:
```
$ rails generate i18n:js:config
Could not find generator 'i18n:js:config'. Maybe you meant 'scss:scaffold' or 'css:scaffold' or 'less:scaffold'
Run `rails generate --help` for more options.
```

`rake i18n:js:export` seems to be working fine.

Any explanation about this?

**Comment by barcala** [comment]
I am using 2.1.2 i18n-js gem. Can it be used with rails 4?

Thank you,

**Comment by PikachuEXE** [comment]
Please use `3.0.0.rc10`
It stays as RC due to historical reasons.
We are working for an official release.
But it's safe to use in production.
Just remember to check CHANGELOG for every update

**Comment by barcala** [comment]
ok. Thank you.
