### ISSUE TITLE
rc8 through rc10 failing with "I18n is not defined"

### ISSUE THREAD

**Issue by gtd** [fnando/i18n-js#336]
Sorry for the lack of details, I am debugging a complex app with a heavy mix of sprockets and require-js, and I'm not fluent in any of these components.  The symptom is that i18n-js 3.0.0.rc7 works, but rc8, rc9, and rc10 all fail with an error:

```
Uncaught ReferenceError: I18n is not defined
```

The coffeescript file that loads i18n-js is:

``` coffeescript
//= require i18n
//= require i18n/translations
define ->
  $.extend(I18n, window.I18n_config)
  return I18n
```

I can confirm it's loading in all cases.

Here are the other gem versions I suspect may be relevant:

```
rails (4.0.13)
rails-i18n (4.0.4)
requirejs-rails (0.9.5)
sprockets (2.12.3)
```

I looked through the changelog, but nothing jumps out at me as the cause (but as I said, I am not fluent in these components).  Any thoughts?

**Comment by PikachuEXE** [comment]
The most common case of having `I18n` undefined is the lack of `//= require i18n` (although I don't know why)
So if you have that already, then the whatever loading code inside maybe broken.
And I don't know how to fix it
There are other related issues / PR related to AMD/CommonJS
Maybe looking through them and/or comment the people involved for idea.
If you want real time chat you can use the Gitter channel provided in README
