### ISSUE TITLE
Fallbacks don't work when translations are set to nil

### ISSUE THREAD

**Issue by michieldewit** [fnando/i18n-js#338]
I am using a tool to manage translations online (WebTranslateIt). This tool makes sure all language keys are available in all YML files. If no translation is available, it will output a `nil` value (`~` in YML). The new `I18n::JS::Utils MERGER` does not take these `nil` values into account and will not merge the appropriate fallback.

Example:

```
en:
  key:
    value: "My value"
```

Spanish (`es`) is configured with `en` as fallback:

```
es:
  key:
    value: ~
```

The resulting JavaScript should be something like:

```
I18n.translations["es"] = {
  "key": {
    "value": "My value"
  }
}
```

but instead is

```
I18n.translations["es"] = {
  "key": {
    "value": null
  }
}
```

**Comment by PikachuEXE** [comment]
Please try `master` to see if this is resolved

**Comment by michieldewit** [comment]
It is. Thanks!
