### ISSUE TITLE
When using async javascript with assets there no way to define language

### ISSUE THREAD

**Issue by AaronGaim** [fnando/i18n-js#340]
I get the error in the layouts/application.html.erb 'i18n is not defined'
Its ignoring changing I18n in the controller before the pages loads.
In assets it will always be 'en' as default :(

**Comment by PikachuEXE** [comment]
The locale in Ruby (which you set in controller or other places) will not be automagically passed into the world of front-end (The JS context).
It's the developer's responsibility to pass it.
If you are loading i18n by `script` tag (async or not), just put 
```haml
:javascript
    (function(I18n) {
      I18n.defaultLocale = "#{I18n.default_locale}";
      I18n.locale = "#{I18n.locale}";
    }(this.I18n = {}))
```
before the tag
You can change `this.I18n = {}` to whatever you need to suit your load order.

For `i18n is not defined`, if you are using asset pipeline, sometimes `//= require i18n/translations` is not enough. Try adding `//= require i18n` as well to see if solves your problem.

If you are using a different setup, please provide details.

**Comment by AaronGaim** [comment]
Adding this to layouts/application.html.erb javascript, 
corrected the problem, thank you!
```
    (function(I18n) {
      I18n.defaultLocale = "#{I18n.default_locale}";
      I18n.locale = "#{I18n.locale}";
    }(this.I18n = {}))
```

I do not quite understand how it works, but it works on production with async!

**Comment by PikachuEXE** [comment]
It's a closure that also define `I18n` as an empty Object on `this` (in browser its the window)
The JS code in closure is generated by getting the locale from Ruby world,
so that `I18n.locale` in JS will be set to whatever you have in controller.
e.g. When `I18n.locale` is `fr`, `I18n.locale = "<%= I18n.locale %>";` is rendered as `I18n.locale = "fr";`

I guess this is a common way (not sure if it's the best way) to put things in Ruby into JS.

**Comment by AaronGaim** [comment]
The problem with this realization that if there are a lot of elements that loaded on the page, it do not always have time to load <script> with this code, before other code that uses i18n.js executed

**Comment by PikachuEXE** [comment]
I guess that depends on how you load your scripts

**Comment by AaronGaim** [comment]
I use a standard load with ```// = require_tree.``` . 
At the moment to make this work, I added file ```a_first.js``` with 
```
var safeLang = $('html')[0].lang
    I18n.defaultLocale = safeLang;
    I18n.locale = safeLang;
```

**Comment by PikachuEXE** [comment]
So you have a `javascript_include_tag` for `application.js` in layout template?
Then put the JS code (closure) before it.

**Comment by PikachuEXE** [comment]
Of course you can also get the value from `html`, it doesn't matter.
There are many ways to pass variables from Ruby to JS world.

**Comment by AaronGaim** [comment]
You mean something like:
```
<script type="text/javascript">
    (function(I18n) {
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
    }(this.I18n = {}))
</script>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true, async: true %>
```
?

**Comment by PikachuEXE** [comment]
Yup, that way it will load synchronously.
And the script after should get the `I18n.locale`.

**Comment by AaronGaim** [comment]
I thought about it, but this syntax it looks bad :)

**Comment by PikachuEXE** [comment]
Then just use whatever works for you ;p
