### ISSUE TITLE
undefined method `initialized? for backend:chain

### ISSUE THREAD

**Issue by seaify** [fnando/i18n-js#344]
@Sija @fnando @DefV 

Rails 4.2.1, use Asset Pipeline, I did the list of things
1. add gem "i18n-js", ">= 3.0.0.rc11" to gemfile and bundle install
2. add i18n,  i18n/translations to application.js
and in the document, it tells me that the default setting is working. but it do not
```ruby
chuck@chuck-MacBook-Pro:~/seaify/weishop(add_i18n_js|✚7…) % rake i18n:js:export                                                                                                                                                                  
rake aborted!
NoMethodError: undefined method `initialized?' for #<I18n::Backend::Chain:0x007fc76789bb70>
/Users/chuck/.rvm/gems/ruby-2.1.5/gems/i18n-js-3.0.0.rc11/lib/i18n/js.rb:155:in `block in translations'
/Users/chuck/.rvm/gems/ruby-2.1.5/gems/i18n-js-3.0.0.rc11/lib/i18n/js.rb:154:in `instance_eval'
/Users/chuck/.rvm/gems/ruby-2.1.5/gems/i18n-js-3.0.0.rc11/lib/i18n/js.rb:154:in `translations'
/Users/chuck/.rvm/gems/ruby-2.1.5/gems/i18n-js-3.0.0.rc11/lib/i18n/js.rb:88:in `translation_segments'
/Users/chuck/.rvm/gems/ruby-2.1.5/gems/i18n-js-3.0.0.rc11/lib/i18n/js.rb:34:in `export'
/Users/chuck/.rvm/gems/ruby-2.1.5/gems/i18n-js-3.0.0.rc11/lib/tasks/export.rake:5:in `block (3 levels) in <top (required)>'
/Users/chuck/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/chuck/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => i18n:js:export
(See full trace by running task with --trace)
```
Could you tell me how to solve this? or write a wiki for this situation. 
According to https://github.com/fnando/i18n-js/issues/59,  it seems that i should add a initializer file to set the default backend?

**Comment by PikachuEXE** [comment]
What `i18n` backend you are using?

**Comment by seaify** [comment]
@PikachuEXE 
I use https://github.com/spree-contrib/spree_i18n this gem, not the rails-i18n.

I use i18n as keyword to search all the files, doesn't see where already set the backend for using.

So i guess the spree_i18n should defined a backend and use it.

**Comment by PikachuEXE** [comment]
I think this gem only support simple backend at the moment.
Try setting `I18n.backend` yourself to see what happen.

**Comment by seaify** [comment]
@PikachuEXE 
I checkout the spree_i18n source code, and find this
```ruby
I18n.backend = I18n::Backend::Chain.new(I18n::Backend::I18nDataBackend.new, I18n.backend)
```
so simplely set
```ruby
 I18n.backend = I18n::Backend::Simple.new
````
won't work
you mean that the i18n-js currently can't support other backend?
Or how can i make the spree_i18n backend to support it? 
what kind of things should be done? 
Is there some method should be filled in other backend?

**Comment by PikachuEXE** [comment]
`won't work` <= Do you have the same error message again?
I want to know if the part `I18n::Backend::Chain` in `for #<I18n::Backend::Chain:0x007fc76789bb70>`
has changed.

**Comment by seaify** [comment]
@PikachuEXE 
After set the backend as I18n::Backend::Simple.new, the error disappear, and i can use the i18n in coffeescript.

But in this project, i think it's not a solution in my project to simply replace the backend, i should fix the spree_i18n backend issue. It might bring some strange errors.

**Comment by PikachuEXE** [comment]
I don't I think I have time to handle non `Simple` backend as `I18n.backend` in `3.0`.
And non `Simple` backend might work differently than `Simple` backend, which is the reason of assuming `Simple` backend in this gem.

**Comment by seaify** [comment]
@PikachuEXE 

Ok. Got it. Understand. I will try to fix it my own, let it both works.

Thanks so much for your kindly reply!!!

**Comment by PikachuEXE** [comment]
Great :)
Feel free to chat at https://gitter.im/fnando/i18n-js

**Comment by seaify** [comment]
@PikachuEXE 

can't i18n-js support backend:chain? I can put the I18n::Backend::Simple.new into to the chain. it can iterate the backend, and finally use the I18n::Backend::Simple.new.

**Comment by PikachuEXE** [comment]
The real problem is not trying to call `init` on simple backend, but instead unable to predict that how other backends in the chain causes the gem to have strange behaviour (i.e. bug).
I admit there should be a proper error for non-simple backend. I will do it before 3.0

**Comment by cjcruz** [comment]
hey @seaify ! are your changes still working well?? (I18n.backend = I18n::Backend::Simple.new
) i have the same problem with spree_i18n. Please let me know if you encountered another solution. thnks

**Comment by maca** [comment]
Should this issue be closed? seems to me that it is still unresolved.
