### ISSUE TITLE
Configurable global variable name

### ISSUE THREAD

**Issue by vemv-kantox** [fnando/i18n-js#348]
A hubspot.com script uses too a `window.I18n` variable, and their dev team insists in polluting the global namespace with such a common name :(

For now I'm forking your gem to use some other hardcoded name, but it'd be great to be able to pass the `I18n` variable name as a config option.

Might give it a shot myself if I have the time. Maybe it'll take much less effort to you.

Thanks much!

**Comment by PikachuEXE** [comment]
Hmm...
I know there is a way to have "no conflict" thing but I don't know how.
Copy some code from other projects to your fork to see how it works :P

**Comment by vemv-kantox** [comment]
Silly me, there's already a namespace option! Should we close this issue?

**Comment by vemv-kantox** [comment]
mmm the `namespace` option seems to apply only to `translations.js` files, but not to `i18n.js` itself?
