### ISSUE TITLE
Problem with special character

### ISSUE THREAD

**Issue by dinhtuan1991vt** [fnando/i18n-js#353]
Here is my translation yml:
```
en:
  js:
    test: "<strong>%{name}</strong> created this board."
```
In my JS, I run with "name" param is "$&".
```
console.log(I18n.t('js.test', {name: "$&"}))
```
Unfortunately, it will show message like this: %{name}s created this board, while I expect that message should be: $& created this board. Is there any problem with special character like "&" ? And how to solve this?

**Comment by PikachuEXE** [comment]
The test case at https://github.com/fnando/i18n-js/blob/master/spec/js/translate.spec.js#L187 shows its working fine.
Maybe you can provide more about your env, such as your I18n (JS) options?
e.g. If `I18n.placeholder` is changed, it might not work as expected

**Comment by dinhtuan1991vt** [comment]
I don't change I18n.placeholder. I think there is problem with "$" character. Could you check it again with my example?

**Comment by PikachuEXE** [comment]
I have changed the test case in a branch
You can fork and run them with `rake spec:js`

- https://github.com/fnando/i18n-js/blob/demo/issue/353/spec/spec/js/translations.js#L12
- https://github.com/fnando/i18n-js/blob/demo/issue/353/spec/spec/js/translate.spec.js#L190

**Comment by dinhtuan1991vt** [comment]
Thank you very much. I used the old version(2.0) and I got this error. But now when I update latest version, it is OK now.
