### ISSUE TITLE
Multiple translations inclusion

### ISSUE THREAD

**Issue by brauliobo** [fnando/i18n-js#358]
In my app, first I include the core translations (basically the rails' default one) then one file from a specific context/plugin, as the app is quite huge and including everything would result in big files for the user to download.

Today, I can't do that with i18n-js, as the second translation load will reset all previously loaded translations!

I will begin to do something based on http://stackoverflow.com/a/929791/670229 and then send a PR. Do you think this is ok?

**Comment by PikachuEXE** [comment]
Looks like #354 
See if that's what you want

**Comment by brauliobo** [comment]
@PikachuEXE It seems the PR is already complete, I'll merge into a fork, hope it gets merged soon!

**Comment by PikachuEXE** [comment]
Could you also help me check the doc of the PR?
It's better to have an actual user to check those things :)

**Comment by brauliobo** [comment]
@PikachuEXE sure, will do it now.
