### ISSUE TITLE
Getting i18n-js to work with jQuery DataTables

### ISSUE THREAD

**Issue by chhhris** [fnando/i18n-js#359]
Not sure if there's something I'm missing, but I'm not able to reference translations in my Rails app (from `config/locales/en.yml`) inside of the DataTables jQuery plugin:

```
// vendor/assets/javascripts/jquery.dataTables.js
...
"sNext": I18n.t('generic.data.next'),
...
```
The DataTable plugin does not seem to be referencing the correct path to the translation (note the prepended 'en' in the screenshot below). I looked into setting the locale explicitly but haven't figured how to make that work. 
![wrong-path](https://cloud.githubusercontent.com/assets/2659618/9864197/ee841f94-5afb-11e5-91c9-f8615cbb340a.png)

I've loved using this gem to reference translations from within `app/assets/javascripts/`, but I don't know what I need to do to make it work inside of `vendor/assets/javascripts/`.

Any help is much appreciated!

**Comment by PikachuEXE** [comment]
If `vendor/assets/javascripts/jquery.dataTables.js` is loaded **before** the translations file(s) loaded
Then all translations are missing and will produce such message

**Comment by chhhris** [comment]
Actually what I'm finding is that it has nothing to do with `vendor/assets` vs. `app/assets`, it's just that in certain files the locale is not being set correctly.

Which is why when the language on my browser is english, all the `I18n.t('...')` text is fine, but if I switch to Spanish, then I get these errors: `"[missing "en.data_table.s_empty_table" translation]"` 

And when I inspect `I18n.locale` in that file, I get "en" even though it should be spanish.

Now I'm trying to figure out why '18n-js' seems to be working in certain files but not others...

**Comment by chhhris** [comment]
With the help of a coworker, I fixed the issue by calling the I18n translation and using that when initializing the DataTable plugin, for ex:
```
$.element.dataTable({
  ...
  language: I18n.t('data_table')
  ...
});
```
