### ISSUE TITLE
Adding an i18n Jquery extension

### ISSUE THREAD

**Issue by maissani** [fnando/i18n-js#362]
The file should be named: jquery.i18n.js
It will add to jquery the following functionalities:
$("element").I18n.translate(); //Find and replace all translation in an element. 
etc....
It's easy to implement and will be usefull for jquery users. 

Maybe i will fork the project and made a pull request myself, it's as you wish. 

Best Regards, 
Mehdi AISSANI

**Comment by PikachuEXE** [comment]
I think this project means to provide 
- a JS library for using translations
- a Ruby library to intergrate with Rails to generate wanted translations

Other features should be contained in another project.

**Comment by fnando** [comment]
This is something for a separate project, for sure.
