### ISSUE TITLE
Setting main locale doesn't work

### ISSUE THREAD

**Issue by ayong-mdsol** [fnando/i18n-js#363]
This is in my i18n-tasks.yml
```ruby
# The "main" locale.
base_locale: eng
## All available locales are inferred from the data by default. Alternatively, specify them explicitly:
locales: [eng, chi, jpn, kor, klg]
## Reporting locale, default: en. Available: en, ru.
internal_locale: eng
```

I have set it such that it looks for eng and not en, yet, for some reason it is still looking for en.

![screen shot 2015-10-08 at 5 41 50 pm](https://cloud.githubusercontent.com/assets/5631435/10380771/dd44111c-6de3-11e5-81c2-847b9f19955c.png)

**Comment by PikachuEXE** [comment]
`i18n-tasks.yml`?
Another gem?

**Comment by pineapplethief** [comment]
Why to break rails convention on two letter locale codes?

**Comment by ayong-mdsol** [comment]
Yeah it was a different gem. Sorry for the confusion
