### ISSUE TITLE
Incorrect translation of keys that have substring "en.", "fr." or other 

### ISSUE THREAD

**Issue by max-konin** [fnando/i18n-js#364]
```javascript
I18n.t("written.title")  // => translation missing: en.writttitle
```

**Comment by PikachuEXE** [comment]
This is to tell you the translation key is missing in locale `en` or `fr`
One might have such translation key in one locale but not in another locale

**Comment by max-konin** [comment]
No. The translation with key: "written.title" is exist. but method "t" try translate key "en.writttitle" not  "writtEN.title" (without "en."). 

When I switch other locale this key is normally translated

**Comment by PikachuEXE** [comment]
So when `written.title` key is used in locale `en`, it tries to use `writttitle` instead of `written.title`
Let me try to reproduce it with test case (in JS) first

**Comment by max-konin** [comment]
I apologize for taking the time. I18n.t work correct. Something wrong with export translation to js

**Comment by PikachuEXE** [comment]
What's wrong?
I created a test case for `written.title`, seems fine for translation.

**Comment by max-konin** [comment]
I have custom export method from custom backend. This does not apply to this gem.
