### ISSUE TITLE
toNumber loses precision on big numbers

### ISSUE THREAD

**Issue by andrewjtait** [fnando/i18n-js#365]
The `toNumber` method calls `Math.abs` on the value passed to it ([see here](https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js#L532)), this means that whatever value is passed to it is processed as a number. This causes issues when working with big numbers such as `123456789.123456789`, as JavaScript cannot handle large floating point numbers particularly well we lose precision.

For example `Math.abs("123456789.123456789")` returns `123456789.12345679`.

Is there a better solution we can use that doesn't require the value to be converted to a number first? It seems like this is only done in `i18n-js` to apply precision to a particular scale, if we don't supply a precision then could it just skip this line?

I'm happy to contribute, just looking for guidance or opinions.

**Comment by PikachuEXE** [comment]
What if I make the default number options configurable?
Right now `NUMBER_FORMAT` is hardcoded and no way to change it.
