### ISSUE TITLE
i18n-js and ember-cli-mirage

### ISSUE THREAD

**Issue by benoittgt** [fnando/i18n-js#366]
Hello

I'm building and app with ember on the top of rails with [ember-cli-rails[(https://github.com/thoughtbot/ember-cli-rails) and the project use i18n-js without any problem when running the app from rails. But when I want to run the test. `Uncaught ReferenceError: I18n is not defined`. Because run alone without rails when running test, I've tried to add the script to the footer of my index page who is used to run the test

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Front Tests</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{content-for 'head'}}
    {{content-for 'test-head'}}

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/front.css">
    <link rel="stylesheet" href="assets/test-support.css">

    {{content-for 'head-footer'}}
    {{content-for 'test-head-footer'}}
  </head>
  <body>

    {{content-for 'body'}}
    {{content-for 'test-body'}}
    <script src="assets/vendor.js"></script>
    <script src="assets/test-support.js"></script>
    <script src="assets/front.js"></script>
    <script src="testem.js"></script>
    <script src="assets/test-loader.js"></script>
    <script src="../../app/assets/javascripts/i18n/translation.js"></script>

    {{content-for 'body-footer'}}
    {{content-for 'test-body-footer'}}
  </body>
</html>
```

But it's still undefined. 
Can i18n-js can be loaded here ?

Maybe the best is to stop using i18n-js and turn to something only on the ember app for the translation. 

Related issues : 
* [On ember-cli-rails](https://github.com/thoughtbot/ember-cli-rails/issues/223#issuecomment-150618747)
* [On ember mirage](https://github.com/samselikoff/ember-cli-mirage/issues/327)

**Comment by PikachuEXE** [comment]
Try adding 
```
<script src="../../app/assets/javascripts/i18n.js"></script>
```
The README state to "include" `i18n/translation` since it already got require statement for sprockets
But sometimes that doesn't work

**Comment by benoittgt** [comment]
Thanks for your answer @PikachuEXE. But it doesn't work, I got a 404. I don't have any i18n file. It only works if I copy past the [i18n-js code](https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js) directly in my `emberapp/test/index.html`. It's very dirty for the moment but I will try to load directly the i18n file in my ember app, need to figure out.

**Comment by benoittgt** [comment]
I've finally move my translation code to ember. i18n is now using [ember-18n](https://github.com/jamesarosen/ember-i18n).
