### ISSUE TITLE
Doesn't work with heroku

### ISSUE THREAD

**Issue by schneems** [fnando/i18n-js#367]
```
$ heroku run bash
$ rm tmp/i18n-js.cache
$ rake assets:precompile
rake aborted!
Sprockets::FileNotFound: couldn't find file '/app/tmp/i18n-js.cache'
```

The buildpack stores the contents of tmp/cache/assets https://github.com/heroku/heroku-buildpack-ruby/blob/8e037b688f277c695dcf9a056a2d0e1eb8747ed1/lib/language_pack/rails4.rb#L66 sprockets needs this directory to be able to compile quickly. We don't copy the entire tmp directory since it can have other build artifacts that aren't needed and your cache would grow unbounded. Instead we only cache tmp/cache/assets. What is happening is this file the i18n-js.cache is in the top level `tmp/` directory and not in `tmp/cache/assets`.

I believe that on the first push when the file isn't found it is generated (and it is empty). On the second push, another asset references this file which is assumed to already exist, and when it doesn't you get this error.

It looks like this file is always empty. Do we need it?

**Comment by PikachuEXE** [comment]
Maybe this is duplicate of #255 ?

**Comment by schneems** [comment]
Probably, this was with `i18n-js (2.1.2)`. I'll ask my customer to try upgrading versions.
