### ISSUE TITLE
Is it possible(i cannot) to auto generate locale file with multiple specific contents from en.yml using i18n-js.yml file

### ISSUE THREAD

**Issue by AravinthG** [fnando/i18n-js#368]
I can add single component from en.yml to auto generated locale file. But I cannot add multiple components from en.yml into autogenerated locale file for each language.

               translate:
                   - file: 'app/assets/javascripts/i18n/%{locale}.js
                     only: ['normal', 'special']

The result is always null in each local file

              var I18n = I18n || {};
              I18n.translations = {"en":null}

I want the result to be like: en.js

                 var I18n = I18n || {};
                 I18n.translations = {"en":{"normal":{"title":"normal","desc":"normal delivery"}},{"special":{"title":"special","desc":"special delivery"}}}

The problem : it is searching for key 'normalspecial' when multiple components are entered. when i enter only single component, it works fine.

When i tried this

                translate:
                     - file: 'app/assets/javascripts/i18n/%{locale}.js'
                       only: '*.normal'

it doesn't search for 'normal' component instead searches for subkey 'normal' in all components. even this format doesn't support multiple component.
Can anybody pls just clarify the mistake i am doing

**Comment by PikachuEXE** [comment]
We have changed the logic around that in `3.0.0.rc10`
You can read that at https://github.com/fnando/i18n-js/blob/master/CHANGELOG.md

Assuming you are using `3.0.0.rc10` or above
If you want translation like: `{"en":{"normal":{"title":"normal","desc":"normal delivery"}}}`
You can try to put  `*.normal.*`

For multiple condition you can try to put `only: ['*.special.*', '*.normal.*']`

If you still have trouble with the translations generated please report back.

**Comment by AravinthG** [comment]
Thanks for the reply. My current version is  i18n-js (2.1.2). I will try with version you specified and respond.

**Comment by AravinthG** [comment]
Thank you PikachuEXE. Problem seems to be the older version of gem.
It worked fine after updating the gem.

**Comment by PikachuEXE** [comment]
If your problem is solved, can you please close the issue?
Thanks.
