### ISSUE TITLE
Combines every locale  into single string and mentions as invalid locale

### ISSUE THREAD

**Issue by AravinthG** [fnando/i18n-js#369]
The gem worked fine until I made another pull request without saving the stash. 
Now when I installed the gem again and tried to export it shows the following error : 
    
         I18n::ArgumentError: Valid locales: enfrarcacsdadees-LAesetfihehuiditja-JPkonb-NOnlplpt-BRpt-PTru-RUskslsv-SEthtrukvizh-CN - Given Locales: ja-JPjaen

        /Users/user/.rvm/gems/ruby-2.1.5/gems/i18n-js-3.0.0.rc11/lib/i18n/js/fallback_locales.rb:76:in `ensure_valid_locales!'

I followed all the procedures from readme file.
All locales are combined as single string and shows invalid locale. 
It worked fine previously. The file I pulled has nothing to do with locale.
Should I provide manual entry of locale in config file

**Comment by AravinthG** [comment]
This error was solved when I added a I18n.available_locales = ['your locales']

**Comment by PikachuEXE** [comment]
I have just try to improve the readability of the error message in d87b933a57c97b54bf84177551df6452f276203c

**Comment by AravinthG** [comment]
the problem occurs when I try to add locales that have '-' in them like zh-CN, pt-BR.
It doesn't accept a locale with hyphen
ex: 
         I18n.available_locales = ['ar','ca','cs','da','de','en','fr','he','hu','ja','pt-BR']

error:
         I18n::ArgumentError: Valid locales: arcacsdadeenfrhehujaes-LA - Given Locales: es-LAesen

How to express such locales in the array?

**Comment by PikachuEXE** [comment]
By default, the fallback locales for `pt-BR` would be `pt` and `en` in `i18n-js`
And you only have `pt-BR` & `en` in `I18n.available_locales`
That's why the gem is complaining about not-matching locales

**Comment by AravinthG** [comment]
yes. adding fallback worked. Thank you.
