### ISSUE TITLE
Syntax error when I add 'only' option in i18n-js.yml

### ISSUE THREAD

**Issue by AravinthG** [fnando/i18n-js#370]
translations:
  	     - file: 'app/assets/javascripts/i18n/%{locale}.js'
  	       only: ['*.normal.*', '*.special.*']            

     ArgumentError: syntax error on line 19, col 9: `  	  only: ['*.special.*', '*.normal.*']

**Comment by PikachuEXE** [comment]
Since there is no ERB inside
You can use `http://www.yamllint.com/` to see if there is any syntax error in your content first

**Comment by AravinthG** [comment]
Thank you. Though the alignment was right, there were few extra spaces. It worked fine after correcting it.
