### ISSUE TITLE
3.0.0rc11 incompatible with sprockets-rails 3.0.0

### ISSUE THREAD

**Issue by tmikoss** [fnando/i18n-js#377]
After updating to `sprockets-rails` 3.0.0, the application fails to launch with:

`i18n-js-3.0.0.rc11/lib/i18n/js/engine.rb:10:in `block in <class:Engine>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)`

It seems to me you now have to call ` Rails.application.config.assets.configure.register_preprocessor` (see https://github.com/rails/sprockets-rails/commit/02f457e6563ed8c9965d39e78f8026ec4c75ed47). However, that fails for 2.x version of sprockets.

**Comment by PikachuEXE** [comment]
Will fix soon with #374

**Comment by PikachuEXE** [comment]
#376 Merged
Can you try `master`?

**Comment by tmikoss** [comment]
Thanks, works fine on `rc12`!
