### ISSUE TITLE
i18n-js undefined method `register_preprocessor' with Rails 4.2.5

### ISSUE THREAD

**Issue by nhinze** [fnando/i18n-js#379]
I upgraded from Rails 4.1 to 4.2.5. I use i18n-js 2.1.2 . I now get the following error message on server start. Is version 2.1.2 compatible with Rails 4.2.5?

/Users/username/.rvm/gems/ruby-2.0.0-p598@rails42/gems/i18n-js-2.1.2/lib/i18n-js/engine.rb:12:in `block in <class:Engine>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)

**Comment by nhinze** [comment]
I'm having the same issue with 3.0.0.rc11.

**Comment by nhinze** [comment]
Found the issue. i18n-js is not yet compatible with sprockets 3.0.

**Comment by rselk** [comment]
I got this to work with downgrading sprocket-rails:

Gemfile
```ruby
gem 'sprockets-rails', '2.3.3'
```

**Comment by PikachuEXE** [comment]
#376 Merged
Please try `master`
