### ISSUE TITLE
uninitialized constant I18n::JS

### ISSUE THREAD

**Issue by folivi** [fnando/i18n-js#384]
Hi,
I installed the gem then put the line config.middleware.use I18n::JS::Middleware to my dev env file
and I get the error: 
when I run  rake i18n:js:setup  I get nameError: uninitialized constant I18n::JS
How can I fix it?
cheers

**Comment by PikachuEXE** [comment]
What version have you installed?
I am only maintaining `3.0.0.rc`
And `i18n:js:setup` seems to come from `2.x`

**Comment by folivi** [comment]
My bad. I didn't specify the 3.rc in my gemfile

**Comment by PikachuEXE** [comment]
Just added a notice to README in 0de86694911b9d4eaa55c25ef689350e4bce215c
Hope that help more new users
