### ISSUE TITLE
How can I set currency?

### ISSUE THREAD

**Issue by alex-gvozden** [fnando/i18n-js#385]
Hi

is there any way to set currency used, so far only dollars work and forcing a locale does not work.

is this the known issue and what would you recommend then for currency formatting.
We heavily use multiple currencies in our app, since it handles international billing and I would love to hear good suggestion. Yahoo's library does not support ReactNative

Thanks

**Comment by PikachuEXE** [comment]
Looking at https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js#L616-L640
I think you can use `unit` option to set the currency displayed?

**Comment by espen** [comment]
Have you set number.currency.format.unit? For me `I18n.toCurrency(1000);` gives "1 000,00 kr" as defined in my I18n locale.

**Comment by sospedra** [comment]
@espen how do you set `number.currency.format.unit`?

**Comment by espen** [comment]
Set it in your locale file @sospedra ? It's a default entry in the Rails i18n-files: https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en.yml#L163

**Comment by Damdias** [comment]
how we can set in React native ?

**Comment by PikachuEXE** [comment]
I know nothing about React native so I am afraid I can't provide anything specific to it
I can only say use `unit` option in `I18n.toCurrency`

https://github.com/fnando/i18n-js/blob/v3.6.0/app/assets/javascripts/i18n.js#L779-L785
