### ISSUE TITLE
.gitignore for public/javascripts/translations.js??

### ISSUE THREAD

**Issue by jesperronn** [fnando/i18n-js#386]
question, am I suppose to ignore the file `public/javascripts/translations.js`, which seems to constantly update when I am updating text keys?

Is it necessary to put that file in repository?
Will it automatically generate on a production server?
Does it require some kind of setting?

Sorry for the question, I am probably overlooking some documentation about it.

**Comment by PikachuEXE** [comment]
What is you environment and settings?
Things like gems you are using, gem versions, using asset pipeline or not, etc.

**Comment by drselump14** [comment]
Probably same issue with #209
