### ISSUE TITLE
TypeError with global restrictions on translations

### ISSUE THREAD

**Issue by lowjoel** [fnando/i18n-js#394]
Rack Middleware + Rails 4.2.5.1 with asset pipeline.

My i18n-js.yml:

``` yml
translations:
 - only:
   - '*.common.*'
   - '*.javascript.*'
```

My understanding of the README is that this would only export the `common` and `javascript` keys in the resulting JavaScript translation. This however will trigger:

```
TypeError: no implicit conversion of nil into String
./vendor/bundle/ruby/2.3.0/gems/i18n-js-3.0.0.rc12/lib/i18n/js/segment.rb:31:in `dirname'
./vendor/bundle/ruby/2.3.0/gems/i18n-js-3.0.0.rc12/lib/i18n/js/segment.rb:31:in `write_file'
./vendor/bundle/ruby/2.3.0/gems/i18n-js-3.0.0.rc12/lib/i18n/js/segment.rb:24:in `save!'
./vendor/bundle/ruby/2.3.0/gems/i18n-js-3.0.0.rc12/lib/i18n/js.rb:34:in `each'
./vendor/bundle/ruby/2.3.0/gems/i18n-js-3.0.0.rc12/lib/i18n/js.rb:34:in `export'
./vendor/bundle/ruby/2.3.0/gems/i18n-js-3.0.0.rc12/lib/i18n/js/middleware.rb:65:in `verify_locale_files!'
./vendor/bundle/ruby/2.3.0/gems/i18n-js-3.0.0.rc12/lib/i18n/js/middleware.rb:10:in `call'
./vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
./vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
./vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
./vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
./vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
./vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
./vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
./vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
./vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
./vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
...
```

I notice that `I18n::JS::Segment#write_file` will use a nil `_file`. Probably because my configuration does not specify a name.

**Comment by PikachuEXE** [comment]
Maybe you haven't specified `file` (same level as `only`)

**Comment by PikachuEXE** [comment]
oops wrong button

**Comment by lowjoel** [comment]
Yes, according to the readme this can be used to apply to all translations:

> You are able to exclude certain phrases or whole groups of phrases by specifying the YAML key(s) in the except configuration option. The outputted JS translations file (exported or generated by the middleware) will omit any keys listed in except configuration param:
>
> ```
> translations:
>   - except: ['*.active_admin', '*.ransack', '*.activerecord.errors']
> ```

**Comment by PikachuEXE** [comment]
OK That's the only place missing the `file` node
Will fix it soon

**Comment by lowjoel** [comment]
Awesome work, thanks for being so quick @PikachuEXE

**Comment by PikachuEXE** [comment]
Let's keep this open until README fixed

**Comment by lowjoel** [comment]
Hang on -- so you're only fixing the README?

Then how do I accomplish this? I only want the *.common.* and *.javascript.* keys to be sent to the client. I can't just specify a separate file, because when I include `i18n/translations` it will still be all translations.

**Comment by PikachuEXE** [comment]
Please provide more details
Here is what I **guess** (as example of what you should provide):
- Using middleware
- Using asset pipeline
- Only want some translations to be exported

**Comment by lowjoel** [comment]
Yup -- that's exactly it. What else do you need to understand my issue at hand better?

**Comment by PikachuEXE** [comment]
My understanding to this gem is:
If you are using asset pipeline, you **do not** need to use middleware
How do you send the translations (in JS) to client side currently?

**Comment by lowjoel** [comment]
Wow. That's an epic misunderstanding on my part.

I currently have both middleware and the asset pipeline.

**Comment by PikachuEXE** [comment]
If you have something like
```
#= require i18n/translation
```
Then you don't need the middleware

**Comment by lowjoel** [comment]
OK I've removed the middleware, and it seems to work. That was really a big mistake on my part, sorry. :sob: 

So is the i18n-js.yml without a filename a supported configuration?

**Comment by PikachuEXE** [comment]
`file` is required is development want to "export" it
by rake task or middleware
Using asset pipeline does not use the `file` option

**Comment by lowjoel** [comment]
Ah, so maybe README.md requires another section for the Rails asset pipeline and i18n-js.yml? The current documentation only talks about the middleware and the export task.

Thank you so much @PikachuEXE.

**Comment by PikachuEXE** [comment]
I plan to update the doc once all big issues for 3.0.0 are solved
And they are not solved yet (busy!)

**Comment by lowjoel** [comment]
thanks for your hard work, @PikachuEXE.

**Comment by afdev82** [comment]
I'm having the same issue and I'm including the files in the html:
```
    <%= javascript_include_tag "i18n" %>
    <%= javascript_include_tag "translations", skip_pipeline: true %>
```
no require statement in the `application.js` manifest file.

**Comment by PikachuEXE** [comment]
You are getting `TypeError` with `skip_pipeline` enabled?
How does `translations` look like?
