### ISSUE TITLE
rake asset:precompile fails with i18n-js

### ISSUE THREAD

**Issue by lowjoel** [fnando/i18n-js#395]
I'm using an app with Carrierwave, who defines locales like pt-BR and pt-PT without defining pt (Portuguese Brazil/Portugal)

I also have localisations which define zh-CN (Chinese (Simplified) China) without zh because zh-TW zh-HK would be different from zh-CN, and zh-CN and zh-SG (Chinese (Simplified) Singapore) would also be (slightly) different, so defining zh doesn't make much sense especially with simplified/traditional characters.

When running rake assets:precompile in RAILS_ENV=production I get  `I18n::ArgumentError: Valid locales: cs, de, el, en, es, fr_CA, fr, id, ja, nb, nl, pl, pt-BR, pt-PT, ru, sk, tr, zh-CN, zh-TW, pt - Given Locales: zh-CN, zh, en`. I'm using the i18n default fallbacks module, because that's the default.

Is there a better solution than erroring out? I think just ignoring the missing locale is a better solution here.

**Comment by PikachuEXE** [comment]
Do you use those translation entries? (for `pt-BR` & `pt-PT`)

**Comment by lowjoel** [comment]
I don't, I tried specifying

```yml
translations:
 - only:
   - 'en.common.*'
   - 'en.javascript.*'
```

but that doesn't help

**Comment by PikachuEXE** [comment]
Oh, you need to add `zh` to `I18n.available_locales`

**Comment by lowjoel** [comment]
Thanks @PikachuEXE, I'll try that.

Rails will simply ignore the missing languages though, shouldn't that be the default behaviour instead of needing additional configuration?

**Comment by PikachuEXE** [comment]
Good point, let's review this before 3.0.0
For please workaround it :S

**Comment by lowjoel** [comment]
Thanks again @PikachuEXE! You have been very helpful :smile:
