### ISSUE TITLE
t.split is not a function

### ISSUE THREAD

**Issue by AutoSponge** [fnando/i18n-js#396]
In later versions of babel, I18n [here](https://github.com/fnando/i18n-js/blob/264aba7dedebf82d51d3b409848834c746da7cc1/app/assets/javascripts/i18n.js#L257) gets compiled to something like this `r.forEach(function(t){n=t.split("-")[0],~o.indexOf(t)`.

This code errors when it encounters an object which seems to happen in ES6 code that has been transpiled because the exports.default overwrites properties of the I18n object and when code like `this["default"]` interprets it, the object is passed.

Please either stop using the reserved "default" as a property name or guard against objects passed to the forEach predicate above.

**Comment by PikachuEXE** [comment]
I think using another property name is acceptable to me.
Assuming there is a spec about related functions and the change of property name passed the spec.

Could you kindly submit a Pull Request for a fix?
That way you can test the change with your own use case more easily.

**Comment by AutoSponge** [comment]
Sorry, I no longer have access to the codebase where this occurred. Feel free to close this if you can not replicate.

**Comment by PikachuEXE** [comment]
OK, let's reopen if someone can reproduce it
