### ISSUE TITLE
i18n-js experiment

### ISSUE THREAD

**Issue by fnando** [fnando/i18n-js#399]
Hello, everyone!

I18n.js has become too complex. This complexity is mainly due to how older Rails versions work (remember when asset pipeline was a pile of poop emoji?).

I just pushed some code to https://github.com/fnando/i18n-js/tree/experiment. The idea is dumbing down the way we access translations. Instead of using complicated yaml files, we only use `<%= store_translations "*.date.*" %>` in a `app/assets/javascripts/locales.js.erb`), for instance. This solve some problems:
- It's easier to export locales files and tweak them as you need/want.
- Supporting module systems like require.js doesn't require crazy hacks.
- We can rely on Sprockets caching.

The only downside is that there is more manual work involved, but I'm totally fine with the trade-offs. 

Making things simpler will always reflect on features, which means we'll remove a few things:
- Exporting files to disk is no more; now you _have_ to use the asset pipeline.
- Things added mostly to fix diffs due to exported files (e.g. sorted keys, pretty print)
- Hacks like `js_extend` to disable misbehavior of our JS code.
#### What this experiment branch implements
- Support for dist static files (for using with NPM/Bower/other)
- Real package.json for NPM packaging
- Configurable namespace for translations and I18n itself
- Smart(er) cache expiration based on translation files by using Sprockets 3+.
- Configurable shims inclusion.
- Running example apps using I18n with require.js, ES6 modules and Rails "Omakase".
#### Migration Path for Rails < 4.2

Some people won't be able to migrate to newer Rails versions, not being able to leverage the newer Sprockets features. Possible migration path:
- Use i18n-js' static files through i18n-js (detect that we're running older Rails versions and just push the dist directory to the assets load path).
- Create an external tool to export files to disk (may or may not be maintained by me / @PikachuEXE)
#### Feature replacement

| Feature | Old Implementation | New Implementation | Status |
| --- | --- | --- | --- |
| translation filtering | mapped through config file (e.g. config/i18njs.yml) | templates files | done |
| export files to disk | `rake i18n:js:export` | Use [fnando/i18n-js-cli](https://github.com/fnando/i18n-js-cli) | done |
| configuration through yaml files | e.g. `config/i18njs.yml` | Use [fnando/i18n-js-cli](https://github.com/fnando/i18n-js-cli) | done |
| middleware exporter | config.middleware.use I18n::JS::Middleware | Sprockets' dependency resolver | done |
| all configs related to how files are exported (sorting, pretty print, etc) | uses yaml file | Configurable I18n::JS.json_encoder callable | done |
| other I18n backends (Redis) | unavailable | Configurable I18n::JS.translations callable | done |

So this is what I have for now. I'd like to know your opinions. It'd be awesome if you could test these changes and report issues.

**Comment by johnnyshields** [comment]
1) Translation filtering should continue to be done in YAML. Template files are overkill, and YAML supports aliases which means you can easily have one file be a subset of another, which I use in a few places.

2) `pretty_print` and `sorted_keys` are both super useful if you are checking in the translation outputs into Git. In fact, since most JS compilers now automatically uglify automatically, we should *always* use `pretty_print` in this library, and `sorted_keys` should also be the default.

**Comment by johnnyshields** [comment]
Just some background on my use case. I have several different apps both in Rails and various JS frameworks (Ember, React). I have all my translations in my Rails repo, and I'm exporting subsets of the keys to each JS app.

In the future I'd like to move all the translations to their own repo, and export translation subsets as either JSON, JS, or YAML depending on the case (w/ YAML I can export to other Rails apps).

**Comment by johnnyshields** [comment]
3) Re: `js_extend`, IMHO this should be configurable because I don't want to perform a hash deep-merge on my JS frontend each time the app loads for thousands of I18n keys.

**Comment by johnnyshields** [comment]
Just a thought, why not make export configurable as Template **OR** YAML, JSON, or JS?

**Comment by fnando** [comment]
@johnnyshields answers below.

1) Template files make things easier. Returning translations for require.js, for instance, doesn't require dirty hacks or shims. Cache expiration works the way it should be. And you can configure the keys with Ruby in an initializer as the README shows (e.g. `DEFAULT_I18NJS_SCOPES`), avoiding repetition.

2) There won't be translation output to check in into Git, which renders `pretty_print` and `sorted_keys` useless. If you really want to, it's easy to do it so with the now configurable `I18n::JS.to_json` callable (e.g. `I18n::JS.to_json = ->(translations) { JSON.pretty_generate(translations) }`).

If we decide to support file disk exporting, then this tool can add sorting/pretty print automatically. But I do believe that these features are not beneficial to regular asset pipeline users as myself.

3) You can just pass in an array with all filters and the merge won't happen every time,  like in `<%= I18n::JS.store_translations self, ["*.date.*", "*.time.*"] %>` and you won't need to deep merge several times. Since the translations object will be empty, we can even optimize it to just assign the translations.

> ...and I'm exporting subsets of the keys to each JS app.

Can you share some of your YAML configuration, so I can see how you're doing it?

> In the future I'd like to move all the translations to their own repo, and export translation subsets as either JSON, JS, or YAML depending on the case (w/ YAML I can export to other Rails apps).

Yet another reason why I think file disk exporting should be a separate tool. This will help both older Rails version users and people that don't use Rails at all.

> Just a thought, why not make export configurable as Template OR YAML, JSON, or JS?

Complexity. I18n.js became a bag full of tricks that are useful for some really specific use cases that most people don't use/need. Maybe we should think of a plugin system that can add these additional features?

**Comment by johnnyshields** [comment]
So, it seems you're taking this library in a completely different direction that how I use it. Your way isn't wrong, however it would not be a viable solution for my usage pattern.

I think we need 3 separate repos:
- `i18n-js` - the Javascript only, which can be used by people who don't use Ruby at all. (For some Javascript purists, having Ruby mixed in with JS in the same repo is a big turn-off)
- `i18n-js-rails-templates` - your way (above)
- `i18n-js-exporter` - something like the current featureset, with the ability to export JS, JSON, and YAML with the assumption that the user will check the results into Git.

Here's an example of YAML aliases where I want one file to have all the keys from another file:

```yaml
- file: '../ts_ember/vendor/i18n/data/login.js'
  pretty_print: true
  only: &TS_EMBER_LOGIN
    - '*.locales.*'
    - '*.actions.logout'
    - '*.actions.go_back'
    - '*.ts_ember_i18n.login.*'
    - '*.ts_ember_i18n.error.*'
    - '*.sessions.keyfob_placeholder'
    - '*.devise.sessions.new.sign_in'
    - '*.devise.passwords.new.send_me_reset_password_instructions'
    - '*.devise.passwords.edit.change_your_password'

- file: '../ts_ember/vendor/i18n/data/%{locale}.js'
  pretty_print: true
  only:
    <<: *TS_EMBER_LOGIN
    - '*.languages.*'
    - '*.countries.*'
    - '*.currencies.JPY'
    - '*.currencies.AUD'
    - '*.currencies.HKD'
    - '*.currencies.INR'
    - ...
```

**Comment by fnando** [comment]
@johnnyshields  NPM installing this branch will install these files, so I think we're good. :)

```
$ tree node_modules/i18n-js/
node_modules/i18n-js/
├── LICENSE.txt
├── README.md
├── dist
│   ├── i18n.js
│   ├── i18n.js.gz
│   └── i18n.min.js
└── package.json
```

I was thinking about the CLI, and it can be something like this:

```
i18njs export \ 
  --require ./config/environment.rb \
  --include '*.date.*' \
  --include '*.title.*' \
  --include '*.login.*' \
  --namespace I18n \
  --output app/assets/javascripts/translations.js \
  --pretty-print

i18njs export \
  --require ./config/environment.rb \
  --config config/i18njs.yml
```

I'll try to make it work this week.

**Comment by johnnyshields** [comment]
@fnando right but I won't be using the CLI. I want to do everything via YAML configs.

**Comment by fnando** [comment]
@johnnyshields notice that I covered YAML config through the `--config` option.

**Comment by johnnyshields** [comment]
sure, but why not also look for the YAML in a sensible default location (like `/config/i18n-js.yml`)?

**Comment by fnando** [comment]
I'm not proposing everything to be required; is more of a CLI draft.

**Comment by fnando** [comment]
FYI, `i18n-js-cli` code is here and is totally functional. I have to write some tests to validate exported files, but it's working.

https://github.com/fnando/i18n-js-cli

**Comment by pietschy** [comment]
Hi there, I like this new approach, it's much cleaner and will get rid of some hackery I've need in the past to make it work in a rails/angular/jspm/typescript environment. 

So far it's all working well in my dev environment but I'm having a couple of issues.

  1. Running `rails assets:precompile` is barfing with `uninitialized constant I18n::JS::VERSION`. I haven't hunted too much further on this so I'm not sure if it's my setup.
  2. Using bundler to install i18n-js-cli in my docker build is failing with `There was a LoadError while loading i18n-js-cli.gemspec: cannot load such file -- thor`.

And my last sticking point is with my karma testing environment.  I can inject rails assets, but the tool chain I'm using doesn't work with erb's.  Would it be feasable to leave `i18n.js` as a pure javascript or alternatively have the command line tool generate it as well? 

I'd be happy to provide a pull request if that'd help.

Thanks & cheers
Andrew
