### ISSUE TITLE
Fallbacks are not working with Chain backend

### ISSUE THREAD

**Issue by rap1ds** [fnando/i18n-js#406]
I'm using a `I18n::Backend::Chain` backend and got it working nicely by monkey-patching the `translations` method as suggested in https://github.com/fnando/i18n-js/issues/59#issuecomment-41360199

The problem that I'm now facing is that fallbacks are not working. The issue is that `using_i18n_fallbacks_module?` https://github.com/fnando/i18n-js/blob/master/lib/i18n/js/fallback_locales.rb#L60 returns always `false`, because it checks if the fallbacks are included in the backend class and in case of chain backend, the fallbacks module is not included in that backend.

I was able to fix this issue by monkey-patching the `using_i18n_fallbacks_module?`:

``` ruby
module I18n
  module JS

    def self.selected_backends
      current_backend = ::I18n.backend

      case current_backend
      when I18n::Backend::Chain
        current_backend.backends.select do |backend_in_chain|
          backend_in_chain.respond_to?(:translations, true)
        end
      else
        if current_backend.respond_to?(:translations, true)
          [current_backend]
        end
      end
    end

    def self.translations
      all_translations = {}

      selected_backends.each do |selected_backend|
        selected_backend.instance_eval do
          # all `selected_backends` are `::I18n::Backend::Simple`
          if defined?(:initialized?) && defined?(:init_translations)
            init_translations unless initialized?
          end
        end
        all_translations.deep_merge!(selected_backend.send(:translations))
      end

      all_translations
    end

    class FallbackLocales
      def using_i18n_fallbacks_module?
        I18n::JS.selected_backends.any? do |backend|
          backend.class.included_modules.include?(I18n::Backend::Fallbacks)
        end
      end
    end
  end
end
```

Another way to fix this issue is to change the `using_i18n_fallbacks_module?` to ask if `I18n` responds to `fallbacks`, as suggested in the [comment](https://github.com/fnando/i18n-js/blob/master/lib/i18n/js/fallback_locales.rb#L54).

I'm not sure what is the correct way to fix this. Maybe implement it using `I18n.respond_to?(:fallbacks)`? Or maybe something else?

**Comment by fnando** [comment]
The biggest issue is that backends doesn't have an official public API. My recommendation with custom backends (anything other than simple or gettext) is to wrap it in your own custom backend. Then you can set it as `I18n.backend = YourCustomBackend`.

The gist is that `I18n.backend.send(:translations)` must return anything you'd like to be available.
