### ISSUE TITLE
I18n.extend is not a deep merge

### ISSUE THREAD

**Issue by nate00** [fnando/i18n-js#409]
The README claims that `I18n.extend` performs a deep merge: https://github.com/fnando/i18n-js/blob/d2fd8f29ca0c01b81c534f0eb8cee661af379565/README.md#javscript-deep-merge-js_extend-option

But it looks like `I18n.extend` is actually a shallow merge: https://github.com/fnando/i18n-js/blob/d2fd8f29ca0c01b81c534f0eb8cee661af379565/app/assets/javascripts/i18n.js#L912-L936

I'm happy to submit a PR to update the README if this is indeed a mistake.

**Comment by PikachuEXE** [comment]
Yup that's a mistake in README
What do you think that it should say?

Or just submit PR :P
