### ISSUE TITLE
JS issue with 3.0.0.rc13 on FF and Edge (not Chrome)

### ISSUE THREAD

**Issue by ameft** [fnando/i18n-js#411]
After a bundle update on my app I had strange issues with my js code. It took me a while to understand that the responsible was i18n-js updating from rc12 to rc13.
On Firefox console I get the error "unreachable code after return statement" and many js blocks of the application don't work. Strange thing is that the error is reported in a library (moment.js) where I don't use i18n-js.
Everything fine on Chrome.
Don't know what the problem is and if I'm the only one.. just reverted to rc12 and eveything is fine again.

**Comment by PikachuEXE** [comment]
Any screenshots of the error and the actual location in the script that generates the error?
Something like:
![error](https://cloud.githubusercontent.com/assets/1018543/16549805/8a43b924-41d5-11e6-8b5f-48e03d7c3e38.png)
![script](https://cloud.githubusercontent.com/assets/1018543/16549806/8a4bc858-41d5-11e6-9c56-ee195cc5387b.png)

I got no such error in my app (gem updated, Firefox ESR 45.2.0)

**Comment by ameft** [comment]
With i18n-js 3.0.0.rc13 I get this error in console:
![image](https://cloud.githubusercontent.com/assets/1355449/16687125/e76860b6-4516-11e6-81eb-1a6c61eacc0a.png)

No error with 3.0.0.rc12.

**Comment by PikachuEXE** [comment]
Got something calls `I18n.strftime`
And `I18n.strftime` could be called by `I18n.toTime`
And `I18n.toTime` could be called by `I18n.localize`

So maybe try to find any code the calls one or more of those methods?
