### ISSUE TITLE
Deprecation warning in sprockets 3.7.0

### ISSUE THREAD

**Issue by jsantos** [fnando/i18n-js#415]
Using i18n-js 3.0.0.rc13, sprockets 3.7.0 and Rails 4.2.7:

```bash
DEPRECATION WARNING: You are using the a deprecated processor interface #<Proc:0x007fe3aac61228@/Users/jsantos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/i18n-js-3.0.0.rc13/lib/i18n/js/engine.rb:30>.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Engine> at /Users/jsantos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/i18n-js-3.0.0.rc13/lib/i18n/js/engine.rb:30)
```

This has been recently fixed in other gems, such as [sass-rails](https://github.com/rails/sass-rails/issues/381#issuecomment-234733694).

**Comment by PikachuEXE** [comment]
Will look at it when free (busy until next week)
If you got a chance to change the code that works (with the deprecation message)
You can try to submit a PR to speed up the development :)

**Comment by fwininger** [comment]
:+1:

**Comment by PikachuEXE** [comment]
I guess you guys can do +1 in reactions

Anyway I am still busy working on payment stuff for my work.
So need to delay the work for this for 1 week at least.
Sorry about that.

**Comment by espen** [comment]
It's just a warning @PikachuEXE, nothing is breaking. Thanks for all your work on the project and take the time you need with stuff that makes you money.

**Comment by PikachuEXE** [comment]
@espen 
I guess #417 should make the gem support sprockets 4
Try it :)
I will merge it at the end of this week of no issue found

**Comment by PikachuEXE** [comment]
#418 is opened as updated/fixed version of #417 
Please test it :)

I am going to merge it once all major versions of sprockets are tested against

**Comment by ragesoss** [comment]
This works for me on Sprockets 3.7.0 and silences the warning.

**Comment by PikachuEXE** [comment]
Good
I guess this can be closed now :) ?

**Comment by mamantoha** [comment]
@PikachuEXE it will be a good idea to release 3.0.0.rc14

**Comment by PikachuEXE** [comment]
Ya I will do it tomorrow
Busy Q_Q
