### ISSUE TITLE
Should fallback locales be validated?

### ISSUE THREAD

**Issue by coremessage** [fnando/i18n-js#423]
Rails does not validate fallback locales, but i18n-js does. Do we have to perform this check? Should we make this configurable? Absence of locale validations can be useful for setting up locale aliases without having to pollute `I18n.available_locales`.

**Comment by PikachuEXE** [comment]
Where does the validation occur?
Can you also give an example of the usage you explained?
I am a helper so not very familierized with every bit of this gem.
Thanks.

**Comment by coremessage** [comment]
The validation occurs [here](https://github.com/fnando/i18n-js/blob/master/lib/i18n/js/fallback_locales.rb#L35).

As an example, I want my Rails app to recognize "no" country code as Norway, but all Norwegian translations in rails are stored in "nn" locale. (Same goes for some other languages)
To set up an alias, I configure fallback locales like this:
```ruby
# config/application.rb
# Most of the code omitted
config.i18n.available_locales = ['en', 'no']
config.i18n.fallbacks = { no: :nn }
```
This essentially tells Rails to search for "no" translations in "nn.yml". Then, I configure i18n-js:
```coffeescript
# app/assets/javascripts/translations.coffee
# Most of the code omitted
I18n.fallbacks = true
```
However, i18n-js requires "nn" to be included into `I18n.available_locales`, which makes no sense since "no" and "nn" are the same locale in this case. This can be a problem if your app uses `I18n.available_locales` for a language switcher (which is natural).

Why do we have to perform the check, anyway?

**Comment by PikachuEXE** [comment]
I guess it's for safety at first
But if there is a valid case I am happy to remove it (since rails/I18n itself don't care as well)
If you want the change to be made faster you can submit a PR ;)

**Comment by coremessage** [comment]
Thank you guys! Should I close the issue?

**Comment by PikachuEXE** [comment]
If you have tested it (master) and no problem found
Then please close :)

**Comment by coremessage** [comment]
Okay, locale validation is gone, but now the issue is i18n-js still reads translations from files specified in `I18n.available_locales`. This means that translations for languages that are present in `config/locales`, but not specified in `I18n.available_locales`, are not loaded. It seems that Rails, however, loads locales from `I18n.backend.available_locales`. I've put a pull request together to add an option to override where i18n-js fetches translations from.

Btw, should we make `I18n.backend.available_locales` the default instead of `I18n.available_locales`?

**Comment by PikachuEXE** [comment]
Do you know where does rails call `I18n.backend.available_locales`?
I am not very sure about the difference between `I18n.backend.available_locales` and `I18n.available_locales`

**Comment by coremessage** [comment]
Hmm, we might need a different solution, not quite the one in my PR.
Anyway, Rails is able to fall back to locales that are present in `config/locales` but are not included into `I18n.available_locales`. `I18n.backend.available_locales` returns the list of locales that are present (e.x. yaml files inside `config/locales`), not just those specified under `I18n.available_locales`.

**Comment by PikachuEXE** [comment]
Maybe we can allow user to set what locales should be used to generate translations to JS
And default to `I18n.available_locales` (as a sensible default)
Sounds good?

**Comment by akxcv** [comment]
Yeah, sounds good to me. I can submit a PR a little bit later if you wish.

**Comment by PikachuEXE** [comment]
Yes please :)

Not sure what should the name be though...

**Comment by coremessage** [comment]
Good idea. What about `frontend_locales` or just `locales`?

**Comment by PikachuEXE** [comment]
`available_locales`?
