### ISSUE TITLE
Using dot in the key

### ISSUE THREAD

**Issue by BogdanHossu** [fnando/i18n-js#424]
In my JSON file i have a key like  "Sentence. Next sentence." which unfortunately will not work because the package is searching for an object. Is there a fix for this? To stop looking for an object.

**Comment by PikachuEXE** [comment]
What will happen when you use that in Ruby?

**Comment by BogdanHossu** [comment]
I'm not sure, im using this in react-native project so I'm not sure I can use that.

**Comment by ivan-kalinin** [comment]
@BogdanHossu isn't still not possible right?

**Comment by PikachuEXE** [comment]
Try https://github.com/fnando/i18n-js/pull/541 and leave comment there
I don't want to merge unwanted/untested stuff
