### ISSUE TITLE
Undefined method 'initialized?' for I18n::Backend::ActiveRecord

### ISSUE THREAD

**Issue by karlkaebnick** [fnando/i18n-js#428]
Am running Rails 4.2.5.1.  Have tried versions 3.0.0.rc11 as well as 2.1.2 of the i18n-js gem.  With both of them, when I run 'rake i18n:js:export' I get NoMethodError: undefined method `initialized?' for #I18n::Backend::ActiveRecord.

I know other people have seen this error for other i18n backends (and appear to have found solutions) - is there a known workaround for this with the ActiveRecord backend?

**Comment by PikachuEXE** [comment]
It's due to 
https://github.com/fnando/i18n-js/blob/master/lib/i18n/js.rb#L153
And that method is assuming simple backend

**Comment by stavskiys** [comment]
+1
I have the same problem

**Comment by andreslemik** [comment]
try add this code to initializers:
```ruby
module I18n
  module JS
    def self.translations
     backend = ::I18n::Backend::Simple.new
     backend.instance_eval do
        init_translations unless initialized?
        Private::HashWithSymbolKeys.new(translations)
                                   .slice(*::I18n.available_locales)
                                   .to_h
      end
    end
  end
end
```

Keep in mind that in this case i18n-js will get translations from yaml instead database

**Comment by Iuriy-Budnikov** [comment]
@andreslemik +1

**Comment by PikachuEXE** [comment]
A new version `3.1.0` is released with #519 merged
Can you guys try it?

**Comment by sbungartz** [comment]
Update: If you do try this out, mind the reloading-limitations documented in #521. Possible workarounds for use-cases with and without a `Chain`-Backend are also documented there.

**Comment by vipera** [comment]
i18n-active_record 0.4.0 includes a patch that makes it compatible as a backend for i18n-js. I'm using an (ActiveRecord, Simple) chain backend and it works fine.

More details are in the PR https://github.com/svenfuchs/i18n-active_record/pull/97.
