### ISSUE TITLE
error in firefox

### ISSUE THREAD

**Issue by mcfiredrill** [fnando/i18n-js#431]
### gem version
3.0.0.rc14

### firefox version 
49.0.2

### error
```
TypeError: can't assign to properties of (new String("watch")): not an object i18n.js:87:9
merge()                  i18n.js:87
merge()                  i18n.js:90
merge()                  i18n.js:90
I18n.extend()         i18n.js:941
<anonymous>       en.js:2
```

No issues in Chrome or Safari.

Reverting back to 3.0.0.rc12, and I don't seem to get the error.

**Comment by PikachuEXE** [comment]
Only happens in Firefox or other browsers as well?
Can you also provide the related translation file content?
Thanks.

**Comment by mcfiredrill** [comment]
Only Firefox. 
Also 3.0.0.rc13 works. 

I will try to provide the translation file content if possible.....
