### ISSUE TITLE
IE11 only, interpolation fails for currency starting with $

### ISSUE THREAD

**Issue by amitrai99** [fnando/i18n-js#434]
This bug occurs only in IE11 (version 11.321.14393.0) OS : Windows 10 Home ( Build 14393.351)

**Test Data:**

Translation Hash:

**Test Code**

`I18n.interpolate('%{val}', {val: "$0.00"})`

**Expected Result**

`$0.00`

**Actual Result**

`%{val}.00`

**Comment by PikachuEXE** [comment]
It's hard to ensure it works properly or not without test case
Anyway you can reproduce it in a test case.

Or maybe try to find out what's happening during interpolation in IE 11?
Write a JS code/script that is similar to what `I18n.t` does with your example translation and value. Then ensure the script does reproduce the bug then try to change code to fix the issue.
I cannot find an easy way get an IE11 env myself.

**Comment by amitrai99** [comment]
I narrowed it down to the `interpolate` method and the test case should be pretty simple now. Seems like it is a regex issue.

**Comment by amitrai99** [comment]
There is a new version of i18n which fixes this issue so closing.
