### ISSUE TITLE
Error when removing cache in parallel tests

### ISSUE THREAD

**Issue by dziulius** [fnando/i18n-js#436]
When running in parallel tests, multiple workers attempt to remove cached file at the same time and error happens:

`Errno::ENOENT: No such file or directory @ unlink_internal - /path/to/project/tmp/cache/i18n-js.yml `

`I18n::JS::Middleware#clear_cache` is to blame. For now I've monkey patched it locally:

```ruby
def clear_cache
  File.delete(cache_path) if File.exist?(cache_path)
rescue Errno::ENOENT
end
```

But maybe there is a better solution?

**Comment by PikachuEXE** [comment]
The middleware is always hard to "test"
And not to say how to make it thread-safe

I have no idea what changes should be made to it
If there a method that does "delete if exists"?

**Comment by PikachuEXE** [comment]
Maybe try [`FileUtils.rm_f`](http://ruby-doc.org/stdlib-2.2.2/libdoc/fileutils/rdoc/FileUtils.html#method-c-rm_f)

**Comment by dziulius** [comment]
Yeah, `FileUtils.rm_f` works just fine, without needing to add rescue. Will you update code to use this instead of `File.delete`?

**Comment by PikachuEXE** [comment]
Sure
But I want you to actually try it first before changing it :)
No auto testing can be done for middleware

**Comment by dziulius** [comment]
`FileUtils.rm_f` works pretty much same way as my changes. It just performs rescue under the hood:

```ruby
[3] pry(main)> show-method FileUtils.remove_file

From: /Users/dziulius/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb @ line 793:
Owner: #<Class:FileUtils>
Visibility: public
Number of lines: 5

def remove_file(path, force = false)
  Entry_.new(path).remove_file
rescue
  raise unless force
end
```

So there should not be any issues. But to make sure I'm currently running tests and will let you know the result.

**Comment by dziulius** [comment]
I made few runs with `FileUtils.rm_f` and it works great.

**Comment by PikachuEXE** [comment]
Change made in 6fa7737f965430d4c23a84ba3a184f934cc52ada

**Comment by dziulius** [comment]
Thank you very much!
