### ISSUE TITLE
Procs are exported as their :to_s representation

### ISSUE THREAD

**Issue by jwidderich** [fnando/i18n-js#439]
When exporting translations to js, the resulting JSON contains following:
`"rule": "#<Proc:0x0074823784723@/.rvm/gems/ruby-2.3.1/gems/rails-i18n-5.0.1/lib/rails_i18n/common_pluralizations/one_other.rb:7 (lambda)>"`
under `i18n.plural.rule`. This entry changes every time the translations.js file is regenerated, which causes git conflicts.

Since there is no way we can convert the procs to js, would the best course of action be to just remove all procs from the translations before exporting them?

**Comment by PikachuEXE** [comment]
I think it's best to remove the key when the value is a `proc`. 
But if it's too difficult making the value `null` in JS is fine too.

**Comment by btoone** [comment]
We just came across this exact issue. The suggested work-around wasn't clear to me so I'll list what we did to be helpful. 

I selected a general yaml file, `app/javascript/bundles/i18n/en.yml`,  and appended the `i18n.plural.rule` without a value. Like this.

```yml
en:
  hello: "Hello world"
  i18n:
    plural:
      rule: 
```

The resulting change to `app/javascript/bundles/i18n/en.js` was this:

```diff
-      "rule": "#<Proc:0x00007fe1c28c90f0@/Users/brandon/.asdf/installs/ruby/2.5.8/lib/ruby/gems/2.5.0/gems/rails-i18n-5.1.3/lib/rails_i18n/common_pluralizations/one_other.rb:7 (lambda)>"
+      "rule": null
```

Its odd that this issue is open but so old. Is there any more info about how this happened or a better way to work-around/fix?

**Comment by PikachuEXE** [comment]
Please see if #591 fixes your issue

**Comment by btoone** [comment]
Sorry @PikachuEXE I'm not able to duplicate the error in our app any longer. I removed my work around and regenerated but the "#<Proc:" is no longer being added. Weird.

**Comment by PikachuEXE** [comment]
Well then I will close this until someone else encountered this issue

**Comment by texpert** [comment]
I am encountering this issue on version 4.0.1:

```
"cs": {
    "i18n": {
      "plural": {
        "rule": "#<Proc:0x00007ff00df7be58 /Users/thunder/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/numbers_and_words-0.11.11/lib/numbers_and_words/i18n/plurals/cs.rb:9 (lambda)>"
      }
    },
    ...
```

**Comment by fnando** [comment]
@texpert my suggestion is ignoring things like this using the config file (`!*.i18n.plural.rule` should do the trick). Unfortunately filtering out things like this is hard and expensive. Should we remove everything that's not JavaScript primitives/arrays/objects? Should we coerce into something else?

**Comment by texpert** [comment]
> 

Thank you, @fnando, worked like a charm!
