### ISSUE TITLE
How can I pluralize a formatted number?

### ISSUE THREAD

**Issue by raymondctc** [fnando/i18n-js#440]
E.g. If I want to show something like

`1,000 points`

My JSON setting is like this
```
  "point": {
    "one": "1 Point",
    "other": "{{count}} Points",
    "zero": "0 Points"
  },
```

```
I18n.t('point', { count: 1})
```
=> This one work, gives me '1 Point'

```
I18n.t('point', { count: I18n.toNumber(1)})
```
=> This gives me '1 Points'

Does that mean I have to determine the numeric value by myself? If that's 1, then I don't call `toNumber()`?

**Comment by PikachuEXE** [comment]
I don't understand why you need to call `I18n.toNumber(1)` yourself
What's the output of `I18n.toNumber(1)`?

**Comment by raymondctc** [comment]
@PikachuEXE 
`I18n.toNumber(1)` returns something like 1.000 by default

If I don't call `I18n.toNumber({count})`, when the count reaches e.g. 1000 It will print out `1000 Points` instead of `1,000 Points`

**Comment by PikachuEXE** [comment]
I guess you would have to implement that yourself
The "auto pluralization" does not handle numeric value formatting
It only choose the translation (`many`/`one`/`zero`) based on value provided

**Comment by albertogasparin** [comment]
I was also having this problem, but the actual "workaround" is super simple.
Just add another key with the formatted value and use that instead of `count`.

```js
"point": {
    "one": "1 Point",
    "other": "{{value}} Points",
    "zero": "0 Points"
},

I18n.t('point', { count: 1000, value: I18n.toNumber(1000) })
```

**Comment by PikachuEXE** [comment]
@albertogasparin 
Thanks for the tips!

@raymondctc 
Can you try if that works?

**Comment by raymondctc** [comment]
@albertogasparin @PikachuEXE Cool, thanks that works! 😄

**Comment by PikachuEXE** [comment]
@raymondctc @albertogasparin 
I just added the tips to README in 0ca309c88e162c365d1718e5e8d5f11f0179114f
Please help check if it looks fine to you

**Comment by albertogasparin** [comment]
Super! +1

**Comment by PikachuEXE** [comment]
Gonna mark this as solved :)
