### ISSUE TITLE
Using dot as a key

### ISSUE THREAD

**Issue by carera** [fnando/i18n-js#441]
Hello,

first of all, thank you for the great lib! You're doing a good job.

Is there a way we could use `.` character in our keys without i18n processing it as a scope definition? The use case is we have full sentences as translation keys, including dots.

Related to https://github.com/fnando/i18n-js/issues/424 but that one was closed for unknown reason

**Comment by PikachuEXE** [comment]
Then I will ask the same question in #424
What will happen when you use that in Ruby?
