### ISSUE TITLE
Setting translations more than once causes override

### ISSUE THREAD

**Issue by Naoto-Ida** [fnando/i18n-js#442]
I ended up here due to [this](https://github.com/AlexanderZaytsev/react-native-i18n) depending on this library.

I'm currently running into an issue where I have two places where I am setting translations to the instance of I18n in two places.

Setting the `translations` option more than once when implementations seems to override it, not append to it.

I brought this up with the other library [here](https://github.com/AlexanderZaytsev/react-native-i18n/issues/55), but seems like its a matter with `i18n-js`.

Is there any work around for this?

**Comment by PikachuEXE** [comment]
>> Setting the translations option more than once
Not quite sure what that means

The YML config way does have limitation (cannot specify override or append)

There is a PR started by me but I don't have time to continue...
https://github.com/fnando/i18n-js/pull/326

**Comment by Naoto-Ida** [comment]
@PikachuEXE OK, thanks. I've decided to use the previously mentioned library for the app itself, and have my own implementation of a localization system for my lib that it relies on.
