### ISSUE TITLE
Is it possible: text wrap / break on specific place in word

### ISSUE THREAD

**Issue by MatthiasDebaere** [fnando/i18n-js#444]
Is it possible?

Say I got a translation going "pineapple". But the component the text is being translated in isn't big enough to fit "pineapple" on one line.
It shows as:
```
pineap
 ple
```
Can I specify where the word should break, so it would show like this:
```
pine-       or    pine
apple             apple
```

thanks for an otherwise nicely working library!

**Comment by PikachuEXE** [comment]
I have no idea myself :P
But this does seem an issue of the library itself though...

**Comment by MatthiasDebaere** [comment]
Hehe that's okay, I found a way. For HTML you can use <span> elements and add css property of display: inline-block (see [stackoverflow answer](http://stackoverflow.com/a/24357132/6653549)).

Now, to be honoust, the reason I made this issue here is because I was having this problem in React Native. Since there's an [I18n plugin](https://github.com/AlexanderZaytsev/react-native-i18n) which is based on this library I thought it would be best to come straight to this repository and ask my issue here.

But I also have a solution for the issue in React Native (just in case of future people with a similar problem read this):
In react native you can do this to solve this problem:

 ```
     <View style={ [{ flexDirection: 'column'}] }>
        <Text>
          pine
        </Text>
        <Text>
          apple
        </Text>
      </View>
```
It will still write "pineapple" if there's enough place in the parent component, and break on pine/apple if there isn't enough.

Can be closed!

**Comment by PikachuEXE** [comment]
Well the solution is also language specific
If there is a language which require the word representing "pineapple" as one word (no line break)
Then that solution doesn't work :P

Well let's hope we will never encounter that language :D

**Comment by MatthiasDebaere** [comment]
that's true. I believe that, even with my solutions I found and presented above, I saw that simply finding synonyms for the words in the other languages (if possible), or fiddling with the width/padding/margin... when I couldn't fit it completely was also necessary.

I'll just blame it as 'one of those hoops you have to jump through' if you so desperately want multi-language support for your app/website/...

Cheers Pika
