### ISSUE TITLE
Could we release the version 3.0 of this gem ?

### ISSUE THREAD

**Issue by fwininger** [fnando/i18n-js#445]
Could we release the version 3.0 of this gem ?

It's more common to use : 
```
gem "i18n-js"
```
or 
```
gem "i18n-js", "~> 3.0.0"
```

rather than : 
```
gem "i18n-js", ">= 3.0.0.rc11"
```

Related issue : #413

**Comment by fwininger** [comment]
@PikachuEXE @agombault @SzNagyMisu

**Comment by PikachuEXE** [comment]
I don't know who should really control the release of 3.0.0
Because the owner started #399 
If that is closed or merged or delayed somehow, I will release 3.0.0 right away.

But I will release 3.0.0 anyway if nothing happens for #399 until 2017/04/01.

**Comment by PikachuEXE** [comment]
@fwininger `3.0.0.rc16` released
Should be the last or 2nd last RC version

**Comment by fwininger** [comment]
Thanks! :1st_place_medal:

**Comment by PikachuEXE** [comment]
I am gonna release `3.0.0` on 1, April (yup on purpose!)
Please check if there is anything left to be "broken" (that needs breaking changes)

**Comment by PikachuEXE** [comment]
As promised, `3.0.0` released!

**Comment by fwininger** [comment]
Thanks 🥇

**Comment by SzNagyMisu** [comment]
You are great! THX!
