### ISSUE TITLE
How to access the exported translation strings in specs?

### ISSUE THREAD

**Issue by wyefei** [fnando/i18n-js#447]
This isn't covered in doc and I don't know if it's easy or not, but I have a hard time figuring out how we can access these translation strings in specs. We use Jasmine with Karma and we use the middleware approach for local and test development

**Comment by widescape** [comment]
@wyefei Did you find a way? I'm struggling with this as well.

**Comment by PikachuEXE** [comment]
I never use JS spec so I have no idea too ~_~
