### ISSUE TITLE
i18n:js:export task not exposed in Rails

### ISSUE THREAD

**Issue by franzliedke** [fnando/i18n-js#448]
It seems like the `i18n:js:export` task is not available anymore when including this Gem in a Rails (4) project. Possibly since the big refactor that removed the Railtie.

The [task is still implemented](https://github.com/fnando/i18n-js/blob/b8fb918c827a2d3bbe187372e47bbe1a7a6c4c19/lib/tasks/export.rake), but it is not registered anywhere. Or am I missing some magic Rails convention?

**Comment by PikachuEXE** [comment]
I am using rails 5 and got no such issue
Maybe try creating new projects for both rails 4 & 5 and include this gem to see if rails version is related?

**Comment by bacrossland** [comment]
I've run ```rake i18n:js:export``` on a Rails 4.1.16 project and get no errors.

**Comment by franzliedke** [comment]
Hmm, I also cannot reproduce this with fresh apps in both Rails 4 and 5. I'll try to find out what the problem is in my app, so I'll leave this open for a bit more.

@PikachuEXE Does Rails automatically expose all tasks from *.rake files in the lib/tasks directory? Or how are these detected?

**Comment by PikachuEXE** [comment]
@franzliedke It's "automagic" for me 😂

**Comment by bacrossland** [comment]
@franzliedke Rails automatically exposes files with a .rake extension in lib/tasks if they contain tasks. Files without the .rake extension are ignored by rake.
