### ISSUE TITLE
sync ur i18n and standart

### ISSUE THREAD

**Issue by UMSF-K13-3-Sahan** [fnando/i18n-js#452]
I use ruby 2.2.6 and rails 5.0.2
If i change I18n.locale in my ruby code i.e. standart ruby's I18n, should the i18n-js change locale too?
Cuz i have change locale in controller for ru, and still have english locale in my react component :(
sry for my english :(

**Comment by PikachuEXE** [comment]
You need to pass your locale in ruby world to JS world yourself
This gem won't do that for you

You can try:
1. Having some JS in template: 
```haml
  :javascript
    (function(I18n) {
      I18n.defaultLocale = "#{I18n.config.default_locale}";
      I18n.locale = "#{I18n.config.locale}";
    }(this.I18n = {}))
```

2. Having some JS to get the locale from template (but not having generated JS):
```haml
%body{data: {locale: I18n.config.locale}}
```
```js
// Sorry for using jQuery 
// you can use browser native DOM API
(function(I18n) {
  I18n.locale = $("body").data("locale");
}(this.I18n = {}))
```

**Comment by UMSF-K13-3-Sahan** [comment]
Thank you, man 👍
