### ISSUE TITLE
npm version outdated

### ISSUE THREAD

**Issue by fkoester** [fnando/i18n-js#455]
The version of the JS library on https://www.npmjs.com/package/i18n-js is very outdated (3 years old), please consider updating it.

**Comment by PikachuEXE** [comment]
It's different from this project
Look at it's project URL

**Comment by fkoester** [comment]
Yeah, I noticed that. But under the project url it says 

> Note The NPM package is no longer maintain by us but by fnando.

Also, when I call `npm owner ls i18n-js` it states that @fnando is the owner.

Installing a npm package via a GitHub release URL (like described in your doc) is far from ideal because it conflicts with the own version handling of `npm`/`yarn`, makes it harder to setup an npm registry cache etc.

**Comment by PikachuEXE** [comment]
I can update the version on package.json
But I am not one of the owners, I cannot publish it as `i18n-js`
What can I do? :S

**Comment by fkoester** [comment]
@PikachuEXE 
You can also contact [support@npmjs.com]() and I suppose they will figure out a solution.

See also [https://www.npmjs.com/policies/disputes]().

**Comment by PikachuEXE** [comment]
Email sent (cc to npm support)
I will send again if no response
But I expect @fnando to be AFK most of the time lol

**Comment by hnq90** [comment]
Should we publish a new package on npm?

**Comment by PikachuEXE** [comment]
@hnq90 
[As I said earlier](https://github.com/fnando/i18n-js/issues/455#issuecomment-302625927)
This will be resolved in a few weeks since my email sent (so should be 1-2 weeks from now)
It's better to use the same name for the npm package

**Comment by hnq90** [comment]
@PikachuEXE Really? Did you get reply from NPM Staff?

**Comment by PikachuEXE** [comment]
They replied soon after I sent the email to package owner (which is actually @fnando)

**Comment by hnq90** [comment]
@PikachuEXE I think it's better to publish a this package under new name...

**Comment by PikachuEXE** [comment]
@fkoester
Can you help check what should be done before publish a new version?
Like missing dependency
I am noob in this field

**Comment by PikachuEXE** [comment]
`3.0.1` published on npm

**Comment by hnq90** [comment]
Nice, thank you :+1:

**Comment by fkoester** [comment]
@PikachuEXE Sorry for the late response, I was quite busy lately... But glad you figured it out by yourself and this issue is closed. Thank you very much!

**Comment by PikachuEXE** [comment]
@fkoester Do let me know if you got any issue for the npm released version
Because I don't use it :P
