### ISSUE TITLE
Missing some translates even if I can see them in the translations.js file

### ISSUE THREAD

**Issue by sergeyvdovareize** [fnando/i18n-js#457]
The gem says me that relatively new (several weeks) translations are missing. I cleared the cache and tmp folder. Even more, I can see the needed translations in the translation.js file. But when I try to find them in the browser js console (like this - `i18n.t('blah.blah.blah')`), the function throws me the error message - `[missing blah.blah.blah translation]`.
I repeat. Most of the earlier added translations can be found and correct.
What else should I check?
Thanks

**Comment by PikachuEXE** [comment]
Which approach are you using to integrate `i18n-js`?
Also you can try to debug by inspecting `I18n.translations`

**Comment by felexx90** [comment]
Hello

I have the same problem, I debug a little and find that in the function **I18n.lookup** line 411 from the image there is a if that I think has the wrong condition because is looking for a undefined or null to break

![image](https://user-images.githubusercontent.com/7705569/31848418-f35d8740-b5f7-11e7-9bed-1719e23e80dc.png)

**Comment by PikachuEXE** [comment]
@felexx90 
That is correct. 
If it does not break on `null`/`undefined`, the next loop will throw and error on 
`translations = translations[scopes.shift()];`

**Comment by felexx90** [comment]
@PikachuEXE 
Ok you are right, but I feel that it is still miss the condition when found the translatation, you can see from the debug that the translation is found, but never break and keep searching until the translation is null / undefined. maybe in the while condition? or I am just crazy?

**Comment by PikachuEXE** [comment]
`while(scopes.length)` and `scopes.shift()` will ensure the loop ends when all the parts in full scopes are consumed

**Comment by felexx90** [comment]
@PikachuEXE 
Ok, I found my problem. I can't define in the json file something like this

![image](https://user-images.githubusercontent.com/7705569/31872336-cb4ee62e-b780-11e7-89a8-7fb07cac4c73.png)

has to be like this

![image](https://user-images.githubusercontent.com/7705569/31872360-f8e39b70-b780-11e7-8469-70f98ae5ef39.png)

Thanks for the help and patience

**Comment by PikachuEXE** [comment]
Good to see your issue resolved
