### ISSUE TITLE
Insert React components between words

### ISSUE THREAD

**Issue by xareelee** [fnando/i18n-js#461]
Although this library, i18n-js, provides interpolation for translated strings, I did not find a way to insert React or React Native components between words to provide styles.

For example

```js
// en.js
// ...
{
  "bold": "A word will be <B>bold</B> inside this string."
}

// create the i18n string
const B = (props) => <Text style={{fontWeight: 'bold'}}>{props.children}</Text>
console.log( I18n.t("bold") );
```

* Expected: 

`A word will be `**`bold`**` inside this string.`

* What I got:

`A word will be <B>bold</B> inside this string.`

How can I add styles into some translated words?

**Comment by PikachuEXE** [comment]
I don't get it
There is no escaping of HTML tags
I am not sure about style attributes in tags
But I am also not sure which one you are referring to

**Comment by xareelee** [comment]
@PikachuEXE My bad.

I just want to add attributes to the words but don't know how to get this done with i18n-js.

**Comment by PikachuEXE** [comment]
If you need to html tags with whatever attributes, just add it.
If there some escaping issue with translated value, you can report it.

**Comment by tsolar** [comment]
I had the same problem, and I found this https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml

So, I got it working with something like `<span dangerouslySetInnerHTML={{__html: I18n.t('my_translation')}} ></span>`

**Comment by henrikra** [comment]
@xareelee Did you solve this with React Native?

**Comment by PikachuEXE** [comment]
@xareelee 
Did you solve your issue in some way?

**Comment by xareelee** [comment]
@PikachuEXE @henrikra  Yes, I solve this on my own.

I did write some code to treat the translated string as a HTML format, and parse it after translation. I replace the parsed HTML nodes with my own React components.

**Comment by miguelgonch** [comment]
This may be an old discussion, but I had the same question and didn't want to use `dangerouslySetInnerHTML`. So I ended up using the Trans component. 

I'm leaving this comment if it's useful for someone else with the same problem.

Here's the link with the usage info:
https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0

**Comment by silvestreh** [comment]
@miguelgonch how did you do that? The `Trans` component seems to require using `i18next` instead of `i18n-js`.

**Comment by miguelgonch** [comment]
@silvestreh I didn't checked I posted this for `i18n-js`, sorry I had the same problem for `i18next` and that's how I solved it.

**Comment by silvestreh** [comment]
@fnando / @PikachuEXE Not sure if you guys were aware, but this library comes in recommended in the [Expo documentation](https://docs.expo.dev/versions/latest/sdk/localization/#usage).

Right now, the issue I'm having is that, if I have some bold text, I can't keep the font style when using interpolations.

Say I have a component that looks something like this:

```javascript
import styled from 'styled-components/native';

const View = styled.View``;
const Text = styled.Text``;
const Bold = styled.Text`
  font-weight: 600;
`;

function MyComponent () {
  return (
    <View>
      <Text>You have <Bold>{count}</Bold> new messages</Text>
    </View>
  );
}
```

The first idea you'd get is to use interpolation, like `"You have %{count} new messages"`. The problem is that in React Native there's no way to make `%{count}` bold.

**Comment by PikachuEXE** [comment]
If it's reproducible via test cases we can considering fix it
We can't fix what cannot be reproduced via test cases

**Comment by silvestreh** [comment]
I'm sorry, I think I failed at explaining myself: it's not a bug, @PikachuEXE, but a feature request 😂 

If you don't have the time or energy I totally get it, maintaining open source software while working a full-time job is *very* time (and energy) consuming.

At this point, our React Native code base is fully translated using this library, so I'm not exactly keen on the idea of migrating to a different lib.

Last, but not least, thanks for the time and effort you're all putting into `i18n-js` <3

**Comment by PikachuEXE** [comment]
I am not sure what you are requesting.
Custom string escaping/unescaping?

**Comment by silvestreh** [comment]
I think what I'm requesting is very likely outside the scope of `i18n-js` and I wasn't seeing it that way until last night. But, in a nutshell, I was expecting to have something like this:

```json
{
  "myTranslationKey": "You have <0>%{count}</0> new messages"
}
```

And then call the `t` function and pass the components I want to use for those `<0>` tags:

```javascript
import styled from 'styled-components/native';
import { t } from 'i18n-js';

const View = styled.View``;
const Text = styled.Text``;
const Bold = styled.Text`
  font-weight: 600;
`;

function MyComponent () {
  return (
    <View>
      <Text>{t('myTranslationKey', { count: 5, components: [ Bold ] })}</Text>
    </View>
  );
}
```

That function call would return JSX that looks like `You have <Bold>5</Bold> new messages`. This wouldn't be a String. This is when I realized that this feature is likely outside the scope: it's a React-specific solution. I imagine this is why the folks developing `i18next` created a [`react-i18next`](https://react.i18next.com/) companion library specific for React / React Native.

Anyway, thanks again for taking the time to respond.

**Comment by fnando** [comment]
I think the best approach for you is to create a function that retrieves the translated string (e.g. `Some <Bold>highlighted</Bold> text`) and splits into an array such as `["Some", "<Bold>highlighted</Bold>", "text"]`. Then you can actually retrieve the component named as `Bold` and pass the inner context as a prop.

Imo, this is way too specific to live under this project.

**Comment by silvestreh** [comment]
Specific indeed. I think that what got me a bit confused is that the library is used in Expo's docs, so I assumed it had a focus on React/React Native. Anyway, I'm wrapping `i18n-js`'s `t` function to do what I need and I'll likely share for those that need the functionality.

**Comment by silvestreh** [comment]
Alright, just as promised, here goes my solution. Please do note that this is only meant to be used for simple stuff, like styling some text. You can use primitives as props for the components, such as a string for text color, but not much else.

The wrapped `t` function goes like this:

```javascript
// t-wrapper.js
import React from 'react';
import i18n from 'i18n-js';
import HTML from 'html-parse-stringify'; // New dependency

const t = (key, options = {}) => {
  const { components } = options;
  const localizedString = i18n.t(key, omit(options, 'components'));

  if (!components) {
    // If there are no components passed, just return the localized string
    return localizedString;
  }

  // Turn the localized string into an AST and `map` it so that if the child is a component
  // it renders the appropriate component passed as an option
  return HTML.parse(localizedString).map(child => {
    // Show a missing component when you forget to pass it
    if (child.type === 'tag' && !components[child.name]) {
      return `[missing component for ${child.name}]`;
    }

    // If the child is a component, grab the one from options.component,
    // pass the props and its children
    if (child.type === 'tag' && components[child.name]) {
      const Component = components[child.name];
      return <Component {...child.attrs}>{child.children[0].content}</Component>
    }

    return child.content;
  });
};

export default t;
```

So, you'll need your translation to be like I mentioned earlier:

```json
// en.json
{
  "myTranslation": "Welcome <Bold color='%{color}'>%{name}</Bold>"
}
```

And then you can use this wrapper function like this:

```javascript
// my-component.js
import styled from 'styled-components/native';
import t from './path/to/t-wrapper.js';

const View = styled.View``;
const Text = styled.Text``;
const Bold = styled.Text`
  color: ${props => props.color};
  font-weight: 600;
`;

function MyComponent () {
  return (
    <View>
      <Text>{t('myTranslation', { color: 'blue', name: 'Silvestre', components: { Bold } })}</Text>
    </View>
  );
}
```

The tag name used in the translation string and the component *must* match. In this case, `Bold` is passed in `options.components` and `<Bold>` is used in the translation string.

Hope someone else finds it useful!

**Comment by PikachuEXE** [comment]
I think the solutions can be documented in the [Expo documentation](https://docs.expo.dev/versions/latest/sdk/localization/#usage)

But ya this project is not built for React/React Native/JSX
So we probably won't be putting these in our docs.

**Comment by vpolian-kw** [comment]
```jsx
// T.js
import React from 'react';
import i18n from 'i18n-js';

export function T({ id, values, components = [] }) {
  const message = i18n.t(id, values);
  const row = React.useMemo(() =>
  {
    const nodes = [];
    let messageToParse = message;
    components.forEach(({ component: Component, props }, index) =>
    {
      const componentRegExp = new RegExp(`<${index}>(.*)</${index}>`, 'gi');
      const [beforeText, componentText, restText] = messageToParse.split(componentRegExp);
      messageToParse = restText;
      nodes.push(
        <Text id={beforeText}>{beforeText}</Text>,
        <Component key={index} {...props}>
          {componentText}
        </Component>,
      );
    });
    nodes.push(<Text id={messageToParse}>{messageToParse}</Text>);
    return nodes;
  }, [message, components]);
  return <>{row}</>;
}
```

Usage:

```json
{"example.message": "This is {{exampleText}} with <0>Link 1</0> and <1>Link 2</1>."}
```

```jsx
const components = [
  {
    component: Text,
    props: {
      style: styles.links,
      onPress: openLink1,
    },
  },
  {
    component: Text,
    props: {
      style: styles.links,
      onPress: openLink2,
    },
  },
]

<T
  id="example.message"
  values={{ exampleText: "example message" }}
  components={components}
/>
```

**Comment by oliviercperrier** [comment]
For anyone looking for a solution i've made this component to handle wrapping part of a translation text:

Given this translation file:

```
{"welcome": "Welcome to <underline>this</underline> <red>tutorial</red>."}
```

```typescript
import React, { ReactNode } from "react";
import i18n, { TranslateOptions } from 'i18n-js';
import { Text, TTextProps } from "../Text";

type TParts = {
  text: string;
  tag: string | null;
};

type TTransInterpolate = Record<string, (chunk: string) => ReactNode>;

export type TTransProps = TTextProps & {
  transKey: string;
  interpolate?: Record<string, (chunk: string) => ReactNode>;
  options?: TranslateOptions;
};

const parseTranslation = (text: string, interpolate: TTransInterpolate) => {
  // Combine all tag names into a regex pattern
  const tagNames = Object.keys(interpolate).join("|");
  const regex = new RegExp(`(<(${tagNames})>(.*?)<\/\\2>)`, "g");

  let lastIndex = 0;
  const parts: TParts[] = [];
  let match;

  while ((match = regex.exec(text)) !== null) {
    if (match.index > lastIndex) {
      parts.push({ text: text.slice(lastIndex, match.index), tag: null });
    }

    parts.push({ text: match[3], tag: match[2] });
    lastIndex = regex.lastIndex;
  }

  if (lastIndex < text.length) {
    parts.push({ text: text.slice(lastIndex), tag: null });
  }

  return parts.map((part, index) => {
    if (part.tag && interpolate[part.tag]) {
      return <Text key={index}>{interpolate[part.tag](part.text)}</Text>;
    }
    return <Text key={index}>{part.text}</Text>;
  });
};

const Trans = ({ transKey, interpolate, options }: TTransProps) => {
  const translation = i18n.t(transKey, options);

  return (
    <Text>
      {interpolate && Object.keys(interpolate).length > 0 ? parseTranslation(translation, interpolate) : translation}
    </Text>
  );
};

export default Trans;
```

```jsx
<Trans
     transKey="welcome"
     interpolate={{
        underline: chunk => <Text tdl="underline">{chunk}</Text>,
        red: chunk => <Text color="red">{chunk}</Text>,
     }}
/>
```
