### ISSUE TITLE
Add individual locale.js files seperately during asset precompilation

### ISSUE THREAD

**Issue by absessive** [fnando/i18n-js#462]
Currently, all the I18n translations become part of application-SHA.js when running in production. Is there a way to include these separate from the applications JS file and instead have en-SHA.js, es-SHA.js, de-SHA.js etc?

**Comment by PikachuEXE** [comment]
Sorry for late reply
Do you mean exporting translations to separate files?
Try this first:
https://github.com/fnando/i18n-js#export-configuration-for-translations

**Comment by PikachuEXE** [comment]
If it does not suit your need to please provide more details about
your current setup and expected result

**Comment by absessive** [comment]
> Sorry for late reply
> Do you mean exporting translations to separate files?
> Try this first:
> https://github.com/fnando/i18n-js#export-configuration-for-translations

Yes, this is exactly what I need.

However, how does this integrate with webpacker? For e.g. if files live in `vendor/assets/javascripts/i18n/%{locale}.js` how do they get loaded in dev. In production, they work since the individual files are in `public/assets` as part of asset:precompile

**Comment by PikachuEXE** [comment]
Right now I do this:
```erb
// Single erb file, you can have multiple files

<%# encoding: UTF-8 %>

// Tell webpack to watch these files
// https://github.com/usabilityhub/rails-erb-loader#dependencies
/* rails-erb-loader-dependencies ./../config/locales/ */

import I18n from "i18n-js"

I18n.translations = <%= I18n::JS.filtered_translations.to_json %>;

export default I18n
```

And I use this `erb` loader:
```
// config/webpack/loaders/erb.js

/* global process:false */

module.exports = {
  test:     /\.erb$/,
  enforce:  "pre",
  exclude:  /node_modules/,

  use: [{
    loader:   "rails-erb-loader",
    options:  {
      runner:     (/^win/.test(process.platform) ? "ruby " : "") + "bin/rails runner",
      env:        {
        ...process.env,
        DISABLE_SPRING: 1,
        RAILS_CONFIG_EAGER_LOAD_ENABLED_IN_DEVELOPMENT: "false",
      },
    },
  }],
}
```
