### ISSUE TITLE
TypeScript type definition

### ISSUE THREAD

**Issue by ypresto** [fnando/i18n-js#463]
I wrote it and using locally..!
I'm afraid which one is better to send PR to:

- This repo (so when interface changed type definition file should be modified at the same time).
- [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) (repo for user-contributed type definition files).

Thanks..!

**Comment by PikachuEXE** [comment]
I think it's better to keep the "type" stuff off this project.
No everyone use TypeScript 
Adding it might cause un-sync state of implementation and declaration, especially when accepting PR.

**Comment by wilomgfx** [comment]
Agreed, send it to DefinitelyTyped

**Comment by PikachuEXE** [comment]
Let's go for `DefinitelyTyped`

**Comment by n0nick** [comment]
@ypresto did you end up pushing this to DefinitelyTyped? I couldn't seem to find it :)

**Comment by lenguyenthanh** [comment]
@ypresto could you push it to DefinitelyTyped or just post it here please.

**Comment by ypresto** [comment]
Sent PR to DefinitelyTyped..! https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21693

**Comment by PikachuEXE** [comment]
Seems merged already
Feel free to update the doc here

**Comment by arturowczarek** [comment]
Can anybody share some example of how to use it with typescript? I have difficulties trying to use it.

**Comment by n0nick** [comment]
@arturowczarek  FWIW, our usage is still as a global available throughout the codebase, defined as follows:

```typescript
// global.d.ts

import * as II18n from 'i18n-js';

declare global {
  // ...
  const I18n: typeof II18n;
  // ...
}
```

Eventually, we'll want to convert global usage to specific imports via `import * as I18n from 'i18n-js' ... I18n.t(...)`.

**Comment by ypresto** [comment]
My type definition contains UMD module export:

```ts
export = I18n;
export as namespace I18n;
```

So you can use this module as a global without any additional type declaration files. Note that you can use that global **only from script (not module) files**.

https://www.typescriptlang.org/docs/handbook/modules.html#umd-modules

**Comment by Rodrigo816** [comment]
Can someone help me? I don't get it how to use typescript with this lib
```
import I18n from 'i18n-js';
import * as RNLocalize from 'react-native-localize';

import en from './locales/en';
import pt from './locales/pt';

const locales = RNLocalize.getLocales();

if (Array.isArray(locales)) {
  I18n.locale = locales[0].languageTag;
}

I18n.fallbacks = true;
I18n.translations = {
  en,
  pt,
};

export default I18n;

```
`    <Text>{I18n.t('noAutoCompleteHereWhy?')}</Text>`

**Comment by PikachuEXE** [comment]
@Rodrigo816 I suggest you open another issue to ask your question
with more details on what you encountered and what you try to achieve

**Comment by ypresto** [comment]
@Rodrigo816 This library is just a JS lib and not responsible for autocompletion. If you use vscode you can contribute [i18n-ally](https://github.com/antfu/i18n-ally) to support this library.

**Comment by ZeCarlosCoutinho** [comment]
For me, the solution was similar to what I wrote [here](https://github.com/Dogfalo/materialize/issues/5402#issuecomment-1090245281). I installed the types for i18n-js, and then I prepend `global.` before `I18n`.
