### ISSUE TITLE
ReferenceError: I18n is not defined

### ISSUE THREAD

**Issue by brahamshakti** [fnando/i18n-js#468]
I am using react with rails, I installed `I18n` gem. I created a container which contains some component. 

This is my container example:

    import React, { Component } from 'react';
    import PropTypes from 'prop-types';
    import {  CONTENT  } from '../constants';
    import User from '../user';

    class User extends Component {
      constructor(props) {
        super(props);
      }
    
      render() {
        return (
          <div>
            { CONTENT }
          </div>
        )
      } 
    }

and my constant file has only one line:

    export const CONTENT = I18n.t('views.content');

It is displaying correct content on web browser

My test look like:

    
    import React from 'react';
    import { shallow } from 'enzyme';
    import User from '../User';
    import sinon from 'sinon';

    describe('<CategoryListContainer />', () => {
      const sandbox = sinon.sandbox.create();

      function makeComponent(specificProps) {
        const props = {
          name: 'Hello'
        };

        const wrapper = shallow(<User { ...props } />);
          return { props, wrapper };
        }
      }
    });

but when I am running test case for my container it throws:

    Test suite failed to run
    ReferenceError: I18n is not defined

Can you help me?

**Comment by PikachuEXE** [comment]
I use this gem too but I never use `I18n` constant in tests (and I just rely on `I18n` in `window` now in code)

Maybe others have more experience on how to import
https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js

**Comment by jeznag** [comment]
Did you try `npm i -S i18n-js` and then `import i18n from 'i18n-js';`?

**Comment by PikachuEXE** [comment]
@brahamshakti 
Please respond soon or I will close this issue
