### ISSUE TITLE
missing "de.number.human.storage_units.units.mb" when using I18n.toHumanSize

### ISSUE THREAD

**Issue by mthiemann** [fnando/i18n-js#470]
i18n-js v.3.0.1

This issue applies to all locales and storage unit abbreviations.

**Comment by PikachuEXE** [comment]
How do you use that function?
There are test cases and they all pass
https://github.com/fnando/i18n-js/blob/master/spec/js/numbers.spec.js

Maybe you can try to add some failing cases?

**Comment by mthiemann** [comment]
I just pass the number to it which is of MB and GB magnitude. Looking at the test cases you referenced the function should return the correct result.

However, I have to say that I am actually using the library [react-native-i18n](https://github.com/AlexanderZaytsev/react-native-i18n) which is using i18n-js and I was forwarded here because I was told it was an error with i18n-js.

**Comment by PikachuEXE** [comment]
Please post the link to original issue
We need more details

**Comment by mthiemann** [comment]
There is not more information in the [original issue](https://github.com/AlexanderZaytsev/react-native-i18n/issues/123).

**Comment by PikachuEXE** [comment]
Closing since there is not enough info
