### ISSUE TITLE
Translation file empty

### ISSUE THREAD

**Issue by valterspukitis** [fnando/i18n-js#471]
I'm working with backbone.js and Coffeescript and having an Issue setting up the translations.

What I've done so far to install Gem:
-Added the gem to my Gemfile and installed
```
gem 'i18n-js'
gem 'i18n',                   '~> 0.6.11'                         #'~> 0.7.0'
```
-Added //= require i18n/translations to my application.js
```
//= require i18n/translations
```
-Added config.middleware.use I18n::JS::Middleware to my application.rb
```
# Add I18n
config.middleware.use I18n::JS::Middleware
```

When loading the site we see the js files added as fallows:
```
<script src="/assets/i18n.js?body=1" type="text/javascript"></script>
<script src="/assets/i18n/shims.js?body=1" type="text/javascript"></script>
<script src="/assets/i18n/filtered.js?body=1" type="text/javascript"></script>
<script src="/assets/i18n/translations.js?body=1" type="text/javascript"></script>
```

 However, if we view the source of that translation.js file it's empty. We do see the translations.js File generated in the Public/javascript folder, with the existing translations in it.

Any thought why this is happening? Are we missing a step? Thanks in advance!

**Comment by PikachuEXE** [comment]
In asset pipeline with debug on (default is on in development)
It generate script tags for sub-files
So you should look at `/assets/i18n/filtered.js` instead in this case

Since the translation are generated in this file:
https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n/filtered.js.erb

If you turn off debug mode you will see `/assets/i18n/translations` only

**Comment by PikachuEXE** [comment]
Also you don't need to use `I18n::JS::Middleware` if using asset pipeline

**Comment by valterspukitis** [comment]
Thanks a lot for the quick response!
Indeed all the translations are in the filtered.js file, although when using I18n.t('string') it still says that translation is missing. The exact same 'string' is in our filtered.js file.
```
 translated = I18n.t('label')
```
Is this due to debug mode then or am I still missing something?

Thanks a lot!

**Comment by PikachuEXE** [comment]
So you **do** have `I18n.translations` in your browser and `I18n.t` doesn't work?
Maybe try to inspect `I18n.translations` or even replace the data inside manually and test?

**Comment by PikachuEXE** [comment]
Gonna close this after this month
