### ISSUE TITLE
Translations could be provided as flattened object

### ISSUE THREAD

**Issue by slorber** [fnando/i18n-js#476]
Hi,

Currently it seems your lib only expect deeply nested objects:

```json
{
  "common": {
    "edition": "édition",
  }
}
```

It could accept as well this flat format that is quite common in I18n setups

```json
{
  "common.edition": "édition"
}
```

I tried at least and it didn't work as I expected

**Comment by PikachuEXE** [comment]
What do you mean?

Using `I18n.t("common.edition")` should look for both translation keys above?
But that complicates things since when are 3 levels, you could have
```json
{
  "level1": {
    "level2": {
      "level3": "value"
    },
  }
}

{
  "level1": {
    "level2.level3": "value"
  }
}

{
  "level1.level2": {
    "level3": "value"
  }
}

{
  "level1.level2.level3": "value"
}
```

So 4 lookups are necessary for a key with 3 parts

If you need `.` in key, set a different separator char in config

**Comment by slorber** [comment]
It's not trhat I need . in key, it's just that it's easier to process/merge/deduplicate simple strings than deeply nested objects, and that this flat format often used for I18n (see react-intl for exemple)

**Comment by PikachuEXE** [comment]
To reduce the number of lookup there should only be 2 of them for a single call to `I18n.t`
1. The original one (deep nested)
2. Flat key

Also if one is using flat keys, should we just assume he using flat keys in translations all the time?

**Comment by slorber** [comment]
Hi,

Honnestly I don't know, maybe you can run a single check on the translations and see if they are all flat and if they are do flat lookups only?

Allowing mixed styles is certainly better but if it's less performant it does not seem a big deal to disallow it.

**Comment by PikachuEXE** [comment]
Allowing both seems strange.
That would introduce an order of lookup.
Either they are all flatten, or use nested objects.

Also if flatten, does it include the locale in the flatten keys?

I would prefer allowing the translation lookup logic to be extended/overridden.
If you really need it I can start working on it but it might take some time

**Comment by slorber** [comment]
currently for each locale I have flat bundles so I still have 1 level of nesting

all this is just suggestion, I don't really NEED it because I currently have a working workaround

**Comment by PikachuEXE** [comment]
OK Let's keep this opened
Might do some work for this later

**Comment by fnando** [comment]
I think the ideal approach for this is just making a helper that converts flatten objects into nested objects. There are libraries out there that does exactly this, so maybe we should just document the approach in a troubleshooting section.
