### ISSUE TITLE
Add callback when fallback is used?

### ISSUE THREAD

**Issue by slorber** [fnando/i18n-js#477]
Hi,

I have an app whose default language is french, and we are in progress of translating it to english.

We'd like to use fallback feature, yet be able to report and store somewhere missing english translations.

When `en -> fr` fallback is used, it seems currently not possible to run some arbitrary code to report that fallback was used (which actually means there's a missing translation).

Can we have a hook to like `missingTranslation` that notify us when fallback is used? Something like :

```javascript
I18n.onFallback = (locale, fallbackLocale, key, options) => {...}
```

**Comment by PikachuEXE** [comment]
If you need to find out what translations are missing
you can change the config in development / test:
```javascript
I18n.fallbacks = false;
I18n.missingTranslation = function () { return undefined; };
```

Or use some tool to compare the translation entry collection object?

**Comment by slorber** [comment]
yes i already do that it's just I want this in prod too because I'm not sure to visite all my websites pages in dev and miss some corner cases, so I need both fallback and hook

**Comment by PikachuEXE** [comment]
So if you have translation object like
```javascript
var translations = {
  "en": {
    "chicken": "???"
  },
  "fr": {
    "chicken": "???",
    "wine": "???"
  }
}
```

I guess you can compare the keys to find out what's missing?
Not sure, there is a tool [`i18n-tasks`](https://github.com/glebm/i18n-tasks) in Ruby

**Comment by slorber** [comment]
Hmm thanks I'll see, I'm not a Ruby developer but backend is in Ruby and we wanted same syntax for frontend/backend

**Comment by PikachuEXE** [comment]
How do you guys generate translations in JS then?

**Comment by slorber** [comment]
We transform yaml files from translations.io to json files in our build pipeline

**Comment by PikachuEXE** [comment]
I see let me work on it later

**Comment by unixmonkey** [comment]
I think you could do this already with something like this, as long as its loaded after `i18n`, and before it hits any translation calls:

```js
I18n.originalMissingTranslation = I18n.missingTranslation;
I18n.missingTranslation = function(scope, options) {
  // Add ajax or whatever here
  return I18n.originalMissingTranslation(scope, options);
};
```
