### ISSUE TITLE
new feature request: newline

### ISSUE THREAD

**Issue by udarts** [fnando/i18n-js#481]
Is it possible to add a newline feature in a string?
For example: This could be a new line\n that would be nice.

Cheers,

**Comment by fnando** [comment]
Try using `|`:

```yaml
text: |
  Line 1
  Line 2
```

As far as Ruby goes, it accepts it:

```ruby
require "yaml"

puts YAML.load("text: |\n  Line 1\n  Line 2")["text"]
Line 1
Line 2
```
