### ISSUE TITLE
How to correctly use namespaces?

### ISSUE THREAD

**Issue by Stekmo** [fnando/i18n-js#483]
I'm creating an react app in which I'm trying to implement translations. I've got a translation file for each language, but as my app has two different functionalities, I'd like to split up my translation files and put them in seperate namespaces. I can't seem to figure out how though.

I've gathered all my translations in one file, which I export
```
I18n.fallbacks = true;
I18n.defaultLocale = "en";

I18n.translations = {
    da: require("./da.json"),
    en: require("./en.json")
};

export default I18n;
```

I import this file as early as possible in my app. Then for translating text in my app, I just import I18n and use the t() function. 
`I18n.t('home.title')`

I've tried creating an object with a key around my translations, like this.
```
I18n.translations = {
    mainApp: {
        da: require("./da.json"),
        en: require("./en.json")
    }
};
```
And then including the name space when I translate it.
`I18n.t('mainApp.home.title')`

This doesn't work however.

**Comment by PikachuEXE** [comment]
Do you mean `I18n.t('mainApp.home.title')` doesn't give you an expected translation?
What does it return instead?
Also what does the `I18n.translations` look like then?

**Comment by Stekmo** [comment]
It returns [missing "en.mainApp.home.title" translation] when I use I18n.t('mainApp.home.title').
When I log I18n.translations, it looks like this:

```
{
  "mainApp": {
    "en": {
      "home":{
        "title": "title",
        "name": "name"
      },
      "about": {
        "about": "About us",
        "whoWeAre": "Who are we?"
      }
    },
    "da": {
      "home":{
        "title": "titel",
        "name": "navn"
      },
      "about": {
        "about": "Om os",
        "whoWeAre": "Hvem er vi?"
      }
    }
  }
}
```
It seems to be because it searches for a 'mainApp.home.title' key in the 'en' locale. I know I can keep all my translations in one file, and then doing the namespaces here, by wrapping each section in an object with a key. I'd love to keep the translation files seperated though, if that is possible.

**Comment by PikachuEXE** [comment]
I think you might have to do:
```javascript
// main_app_i18n.js

// Maybe need to assigned the constant first, not sure...
// MainAppI18n = require("i18n") 

MainAppI18n.fallbacks = true;
MainAppI18n.defaultLocale = "en";

MainAppI18n.translations = {
    da: require("./da.json"),
    en: require("./en.json")
};

export default MainAppI18n;
```

```javascript
// side_app_i18n.js

// Maybe need to assigned the constant first, not sure...
// SideAppI18n = require("i18n") 

SideAppI18n.fallbacks = true;
SideAppI18n.defaultLocale = "en";

SideAppI18n.translations = {
    da: require("./da.json"),
    en: require("./en.json")
};

export default SideAppI18n;
```

**Comment by asciifaceman** [comment]
I accomplished this this way:

Translations.js
```
module.exports = {
  en: {
    SomeView: {
        greeting: 'Hi',
    }
  }
  },
  es: {
    SomeView: {
        greeting: 'Hola',
    }
  }
}
```

Consuming View:
```
import Translations from './translations/Translations';
I18n.translations = Translations;
```

**Comment by PikachuEXE** [comment]
Reopen if you have more questions
