### ISSUE TITLE
DEPRECATION WARNING: The asset "translations.js" is not present in the asset pipeline.

### ISSUE THREAD

**Issue by andreaslillebo** [fnando/i18n-js#484]
After following the instructions for [Rails app without Asset Pipeline](https://github.com/fnando/i18n-js#rails-app-without-asset-pipeline), I get the following deprecation warning when visiting a page using a layout that includes the `translations.js` file:

    DEPRECATION WARNING:
    The asset "translations.js" is not present in the asset pipeline.
    Falling back to an asset that may be in the public folder.
    This behavior is deprecated and will be removed.
    To bypass the asset pipeline and preserve this behavior,
    use the `skip_pipeline: true` option.

layout-file:
```
<%= javascript_include_tag "i18n" %>
<%= javascript_include_tag "translations" %>
```

`config/application.rb`:
```ruby
config.middleware.use I18n::JS::Middleware
```

Ruby 2.4.1
Rails 5.1.4
i18n-js 3.0.2

**Comment by PikachuEXE** [comment]
If you use middleware
It "export" translation file(s) to a folder which defaults to `public/javascripts`
So the warning is correct and you can pass `skip_pipeline: true` to suppress it

I will update README to mention this option once you confirmed the message is suppressed

**Comment by andreaslillebo** [comment]
I can confirm that this works.

Adding `skip_pipline: true` to my layout-file removes the deprecation warning.
```
<%= javascript_include_tag "i18n" %>
<%= javascript_include_tag "translations", skip_pipeline: true %>
```

**Comment by PikachuEXE** [comment]
[Just updated README](38a488348200756cc1a1728b4aa822534f2decc8)
