### ISSUE TITLE
What is the best practice to handle capitalisation across different languages?

### ISSUE THREAD

**Issue by HavaH123** [fnando/i18n-js#493]
Hi, maintainers of this library, currently I am doing something like 

```
function capitalize(s) {
  return s.charAt(0).toLocaleUpperCase() + s.slice(1);
}

I18n.t('createSuccessful', {
   subject: capitalize(${I18n.t('resource')}),
})

```

The translation file looks something like this
```
{
   "createSuccessful": "{{subject}} created successfully",
   "resource": "resource"
}
```

I am wonder if it is language safe to do something like this?
Is there a prescribed way to handle capitalisation using this library?

**Comment by PikachuEXE** [comment]
Capitalisation is language specific (e.g. English has it, Chinese and Japanese don't have it)

So I really have no idea how to perform capitalisation "safely"
This library won't include `capitalisation` function since it's a bit out of scope
