### ISSUE TITLE
Yarn not including all of the files included in the package upon install

### ISSUE THREAD

**Issue by jblock** [fnando/i18n-js#495]
Hi all! We're using `yarn` to manage our dependencies inside of a larger Rails app, and we're having issues installing this package to import into our main Webpack bundle. Namely, this is the file structure of the package that gets installed with Yarn 1.6.0:

```
# yarn -v
# 1.6.0
node_modules/i18n-js
├── app
└── package.json

1 directory, 1 file
```

Mind you, this is completely different from what gets installed when I run this in `npm`:

```
# npm -v
# 3.10.8
node_modules/i18n-js
├── CHANGELOG.md
├── README.md
├── app
│   └── assets
│       └── javascripts
│           └── i18n.js
└── package.json

3 directories, 4 files
```

This very well might be a deep-seeded Yarn bug, but I wanted to make you all aware in the off-chance that you've seen something like this before (or perhaps know of anything that might have been omitted in the publishing stage that might have caused thats).

Thanks for putting out the library and your time! If you have any direction as to what a fix could be, I'm more than happy to invest my (or our team)'s time in PR-ing a fix.

**Comment by PikachuEXE** [comment]
I just tried installing with `npm` and `yarn` in verbose mode:
`npm`:
```
$ npm install -g --verbose i18n-js
npm info it worked if it ends with ok
npm verb cli [ '/users/pikachuexe/.nvm/versions/node/v8.11.1/bin/node',
npm verb cli   '/users/pikachuexe/.nvm/versions/node/v8.11.1/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   '--verbose',
npm verb cli   'i18n-js' ]
npm info using npm@5.6.0
npm info using node@v8.11.1
npm verb npm-session 61ab488318f672a8
npm http fetch GET 200 https://registry.npmjs.org/i18n-js 367ms
npm verb correctMkdir /users/pikachuexe/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /users/pikachuexe/.npm/_locks/staging-f1f06b9b529d2bc3.lock for /users/pikachuexe/.nvm/versions/node/v8.11.1/lib/node_modules/.staging
http fetch GET 200 https://registry.npmjs.org/i18n-js/-/i18n-js-3.0.3.tgz 92ms/_locks/staging-f1f06b9b529d2bc3.lock for /users/pikachuexe/.nvm/versions/node/v8.11.1/lib/node_modules/.staging
npm info lifecycle i18n-js@3.0.3~preinstall: i18n-js@3.0.3
npm info linkStuff i18n-js@3.0.3
npm verb linkBins i18n-js@3.0.3
npm verb linkMans i18n-js@3.0.3
npm info lifecycle i18n-js@3.0.3~install: i18n-js@3.0.3
npm info lifecycle i18n-js@3.0.3~postinstall: i18n-js@3.0.3
npm verb unlock done using /users/pikachuexe/.npm/_locks/staging-f1f06b9b529d2bc3.lock for /users/pikachuexe/.nvm/versions/node/v8.11.1/lib/node_modules/.staging
+ i18n-js@3.0.3
added 1 package in 1.195s
npm verb exit [ 0, true ]
npm info ok
```

`yarn`: (only related log entries posted since it's too long)
(note that I already installed it once)
```
$ yarn cache clean
$ yarn global add --verbose i18n-js
[1/4] 🔍  Resolving packages...
verbose 0.571 Performing "GET" request to "https://registry.yarnpkg.com/i18n-js".
verbose 0.634 Request "https://registry.yarnpkg.com/i18n-js" finished with status code 200.
[2/4] 🚚  Fetching packages...
(many entries...)
verbose 2.793 Performing "GET" request to "https://registry.yarnpkg.com/i18n-js/-/i18n-js-3.0.3.tgz".
[3/4] 🔗  Linking dependencies...
(many entries...)
verbose 3.722 Skipping copying of file "/users/pikachuexe/Library/Caches/Yarn/v1/npm-i18n-js-3.0.3-f537b2bd1e2801eee4f4728a17189ef0991c0270/CHANGELOG.md" as the file at "/users/pikachuexe/.config/yarn/global/node_modules/i18n-js/CHANGELOG.md" is the same size (11251) and mtime (1514862997000).
verbose 3.722 Skipping copying of file "/users/pikachuexe/Library/Caches/Yarn/v1/npm-i18n-js-3.0.3-f537b2bd1e2801eee4f4728a17189ef0991c0270/README.md" as the file at "/users/pikachuexe/.config/yarn/global/node_modules/i18n-js/README.md" is the same size (26805) and mtime (1514862797000).
verbose 3.722 Skipping copying of file "/users/pikachuexe/Library/Caches/Yarn/v1/npm-i18n-js-3.0.3-f537b2bd1e2801eee4f4728a17189ef0991c0270/package.json" as the file at "/users/pikachuexe/.config/yarn/global/node_modules/i18n-js/package.json" is the same size (585) and mtime (1514942553000).
(many entries...)
verbose 4.821 Skipping copying of file "/users/pikachuexe/Library/Caches/Yarn/v1/npm-i18n-js-3.0.3-f537b2bd1e2801eee4f4728a17189ef0991c0270/app/assets/javascripts/i18n.js" as the file at "/users/pikachuexe/.config/yarn/global/node_modules/i18n-js/app/assets/javascripts/i18n.js" is the same size (33001) and mtime (1514862797000).
(many entries...)
[4/4] 📃  Building fresh packages...
warning "i18n-js@3.0.3" has no binaries
```

I will post more after inspecting the archive files from `npm` and `yarn`

**Comment by PikachuEXE** [comment]
Here the the archive files and the file tree of extracted content
(I use Keka when `open` is run)

`npm`:
```
$ pwd
/users/pikachuexe/Downloads/i18n-js/npm
$ curl https://registry.npmjs.org/i18n-js/-/i18n-js-3.0.3.tgz -O
$ open i18n-js-3.0.3.tgz
$ tree .
.
├── i18n-js-3.0.3.tgz
└── package
    ├── CHANGELOG.md
    ├── README.md
    ├── app
    │   └── assets
    │       └── javascripts
    │           └── i18n.js
    └── package.json

4 directories, 5 files
```

`yarn`:
```
$ pwd
/users/pikachuexe/Downloads/i18n-js/yarn
$ curl https://registry.yarnpkg.com/i18n-js/-/i18n-js-3.0.3.tgz -O
$ open i18n-js-3.0.3.tgz
$ tree .
.
├── i18n-js-3.0.3.tgz
└── package
    ├── CHANGELOG.md
    ├── README.md
    ├── app
    │   └── assets
    │       └── javascripts
    │           └── i18n.js
    └── package.json

4 directories, 5 files
```

They looks the same so I am not sure what issue do you have
You can try to download & inspect the archive files yourself too

**Comment by jblock** [comment]
Hi there! Thanks for digging into this a bit. I do see the exact same file structure in the tarball when I curl it directly, but I (and the rest of my team) am still seeing a disparity between what files are extracted during a _local_ installation (when I install the module globally, the file structure looks like what you posted).

This is making me think that the problem is a `yarn` problem rather than an `i18n-js` problem. Have you verified what it looks like if you `yarn add` to a local directory?

**Comment by PikachuEXE** [comment]
`npm`:
```
$ rm -rf ./node_modules/i18n-js
$ npm install i18n-js
$ tree ./node_modules/i18n-js
./node_modules/i18n-js
├── CHANGELOG.md
├── README.md
├── app
│   └── assets
│       └── javascripts
│           └── i18n.js
└── package.json

3 directories, 4 files
```
`yarn`:
```
$ rm -rf ./node_modules/i18n-js
$ yarn add i18n-js
$ tree ./node_modules/i18n-js
./node_modules/i18n-js
├── CHANGELOG.md
├── README.md
├── app
│   └── assets
│       └── javascripts
│           └── i18n.js
└── package.json

3 directories, 4 files
```

Things that can be tried (and do together)
- Install locally on new project (folder?)
- Clear cache
- Try in VM (VirtualBox?)
- Try in Docker Container

**Comment by jblock** [comment]
D'oh! It does look like it's something wrong with how our application is configured. I tried installing the module in a fresh directory and it appears to unpack properly.

Thanks for helping me rubber-duck this! I'll close the issue

**Comment by PikachuEXE** [comment]
Good to see it's resolved :)

**Comment by Shoroh** [comment]
Hi @jblock
Looks like we've got the same issue. Have you managed it?

**Comment by jblock** [comment]
@Shoroh Yep! It turns out that we had the `app/assets` directory included in our `.yarnclean` file (conceivably to help minimize the size of `node_modules` for repos like this where the Ruby files and the JS files live in similarly-named directories).

Removing that line from the configuration file took care of the problem for us. We still aren't using the commonjs version of the library due to the need for some of these files to be server-rendered React components, but we now know that one barrier is out of the way.

**Comment by Shoroh** [comment]
@jblock 
This is it! Thanks bro!
