### ISSUE TITLE
Verifying the locale cache is somewhat slow/expensive

### ISSUE THREAD

**Issue by nateberkopec** [fnando/i18n-js#508]
It's not a major problem, but it does seem like [checking the locale cache](https://github.com/fnando/i18n-js/blob/master/lib/i18n/js/middleware.rb#L61) is somewhat expensive, and since this is a middleware it can add a few milliseconds to every request. 

I've only briefly looked at this method and this project, but is there a specific reason the cache must be implemented this way? Maybe even just making the cache swappable for a different cache store would help.

**Comment by PikachuEXE** [comment]
I am not the author of this middleware
But it seems the middleware is for generating a `translations.js` which contains translation entries in JS
I personally think this is supposed to be used in development only

**Comment by afdev82** [comment]
This could be a problem when this feature is used in production (like I plan to do).
I thought the generation was running only at server start... In this case what could be a solution for this use case? Should we use the rake task every time we deploy? There is a way to add the execution of the rake task at server start only?
