### ISSUE TITLE
Documentation wrong for interpolation

### ISSUE THREAD

**Issue by Dagurmart** [fnando/i18n-js#510]
The example for interpolation looks like this
`I18n.t("hello", {name: "John Doe"});`

isn't it supposed to be

`I18n.t("hello %{name}", {name: "John Doe"});`

**Comment by PikachuEXE** [comment]
`"hello"` is the translation entry key, not the value
```yaml
en:
  hello: "hello %{name}"
```

**Comment by Dagurmart** [comment]
Ah of course.

I had to dig around a bit to find to find out how you added placeholders (if it was %{} or {{}} or ${} etc). It would be nice if that was added to the documentation.

**Comment by PikachuEXE** [comment]
Feel free to send any update for the doc :)

**Comment by CyberMew** [comment]
Many years passed and I am still confuse on `%{}` or `{{}}` to be used. Seems like both are working. Safe to use interchangeably?

**Comment by PikachuEXE** [comment]
@CyberMew Default placeholder seems to support both (I haven't checked for test cases)

https://github.com/fnando/i18n-js/blob/5e3600017eca17ae9ae1369d03c5f55b3e46229c/app/assets/javascripts/i18n.js#L182-L183
