### ISSUE TITLE
Numbers past 53 bits break `toCurrency` and `toNumber` 

### ISSUE THREAD

**Issue by JackieCalapristi** [fnando/i18n-js#511]
See here:

<img width="277" alt="screen shot 2018-10-02 at 12 07 42 pm" src="https://user-images.githubusercontent.com/17489471/46370926-d09b2a00-c63b-11e8-9233-a07399e00426.png">

Upon further investigation, this is actually a problem with javascript's `toFixed()` function used by `i18n-js` here:
https://github.com/fnando/i18n-js/blob/6431b926cf4c05a8946116968d3d40823dd4ac99/app/assets/javascripts/i18n.js#L48 

And the reason `toFixed()` breaks on numbers like this is because JS only supports 53 bit integers which `300000000000020000` is larger than. See more info on this here: http://2ality.com/2012/07/large-integers.html. 

Ideally we would want to find a patch for this that doesn't break rounding for imprecise floating points (which appears to be the reason `toFixed()` was added to this line here: https://github.com/fnando/i18n-js/blob/6431b926cf4c05a8946116968d3d40823dd4ac99/app/assets/javascripts/i18n.js#L48 ). 

Not as ideally we could add a disclaimer for this known issue instead or in the meantime. I'm happy to help in any way I can on this!

**Comment by PikachuEXE** [comment]
Do you any known patch that solves this issue?
I have never encountered any large enough number yet

**Comment by PikachuEXE** [comment]
Added to known issues until there is a permanent fix available
https://github.com/fnando/i18n-js/commit/608d5526c6a0512cfe7d8685466d7717b768bafa

**Comment by PikachuEXE** [comment]
I wonder how the "warning" be sent
Since this library might be used in browser / NodeJS process / even mobile app (screenshot in #513)
