### ISSUE TITLE
Insufficient feedback on empty json file

### ISSUE THREAD

**Issue by fvoordeckers** [fnando/i18n-js#513]
### Behaviour
When supplying an empty translations file (json) I get an unclear error (uncaught?).

<img src="https://user-images.githubusercontent.com/10943876/46603696-2ff1b200-caf4-11e8-9d5f-ded5f7b6cfe6.png" width=250 />

### Expected
When providing invalid or empty json I would expect to get an error message stating the issue. The current error doesn't give you any clue on what the real issue is.

### Reproduce
```
import i18n from 'i18n-js';
import nl from './locales/nl.json';  // empty json file, no content at all!
i18n.translations = { nl };
```

**Comment by PikachuEXE** [comment]
What is the actual content?
If it's syntax error it shouldn't be related to the library

(I don't know what's inside `./locales/nl.json` nor how it looks like if I print `i18n.translations`)

**Comment by sg552** [comment]
I met the same problem!   No clue ~~~  checkout this post: https://stackoverflow.com/questions/52261224/i18n-react-native-unexpected-token?rq=1

really wired.  wait for others who met the same problem.~

**Comment by xstable** [comment]
Same issue here. If you have an existing but empty JSON-File for translation, this error will thrown.

**Comment by p4kaidu** [comment]
+1. Same issue

**Comment by fnando** [comment]
Further explanation: this has nothing to do with i18n-js. Unfortunately, this fails on `import nl from './locales/nl.json';`, and doesn't reach the next line (the one that sets `I18n.translations`).

Unfortunately, we can't do anything other than writing a troubleshooting section and hoping that people will read/find it.
