### ISSUE TITLE
Allow to export translations to json file

### ISSUE THREAD

**Issue by JanStevens** [fnando/i18n-js#514]
Hello,

I'm using Rails 5.2 with webpacker without the asset pipeline, my setup seems to work but I had to do some ugly configs to ensure that the generated translation file is written as a `translation.jsi18n` file so webpack wont try to transpile it. I ended up with the follow

```erb
<script type="text/javascript">
  I18nDefault = {};
  I18nDefault.defaultLocale = "<%= I18n.default_locale %>";
  I18nDefault.locale = "<%= I18n.locale %>"
</script>

<%= javascript_pack_tag('i18n/i18n') %>
```

```js
import I18n from 'i18n-js'

const { defaultLocale, locale } = window.I18nDefault

I18n.defaultLocale = defaultLocale
I18n.locale = locale

window.I18n = I18n

// Now include the file which is not JS so webpack does not try to load it
require('./translations.jsi18n')
```

This all works fine but it would be great to have an option to write a json file instead so you can manually load it in using `I18n.extend`. The original error I received is that I18n is not available in the `translation.js` file (which is obvious since webpack does not allow globals)

**Comment by PikachuEXE** [comment]
Right now I do this:
```erb
// app/assets/javascripts/plugins/i18n-js/index.js.erb
<%# encoding: UTF-8 %>

// Tell webpack to watch these files
// https://github.com/usabilityhub/rails-erb-loader#dependencies
/* rails-erb-loader-dependencies ./../config/locales/ */

import I18n from "i18n-js"

I18n.translations = <%= I18n::JS.filtered_translations.to_json %>;

export default I18n
```

**Comment by JanStevens** [comment]
Hello, 

Thanks a lot for your setup, this got us triggered in the right direction. We didn't use `js.erb` but we managed to pull it off by doing the following


```erb
<script type="text/javascript">
  I18n = {};
  I18n.defaultLocale = "<%= I18n.default_locale %>";
  I18n.locale = "<%= I18n.locale %>";
  I18n.translations = <%== I18n::JS.filtered_translations.to_json %>;
</script>
```
The global I18n window object now has the translations and then we got a JS file which is always included in our main `application.js`

```js
import I18n from 'i18n-js'

const { defaultLocale, locale, translations } = window.I18n

I18n.defaultLocale = defaultLocale
I18n.locale = locale
I18n.translations = translations

export default I18n
```

This ensures that i18n-js is always configured with the right locale and translations, our react components can then import `i18n-js` and use it as normal. This also means we don't need to write files anymore. So my I18n-js.yml file contains

```yaml
translations:
  - file: false
    only: '*.react.*'
    pretty_print: false
```

Not sure if that `file: false` will fly :)

Maybe this can all go into a wiki with possible setups?

**Comment by PikachuEXE** [comment]
Where do you place this? A template file? Is it cached? How do you cache it?
```html
<script type="text/javascript">
  I18n = {};
  I18n.defaultLocale = "<%= I18n.default_locale %>";
  I18n.locale = "<%= I18n.locale %>";
  I18n.translations = <%== I18n::JS.filtered_translations.to_json %>;
</script>
````

Feel free to send PR for updating the README
I am too busy to update it (plus I dunno how people read it)

**Comment by JanStevens** [comment]
That part is included in the main `application.erb` layout file in rails.

So It's not cached In production

**Comment by PikachuEXE** [comment]
I recommend you to cache it
Maybe put that part into [a cell](https://github.com/trailblazer/cells) and enable caching for it
I don't know how the cache key should be generated though

Maybe assign the generated json as a constant...

**Comment by JanStevens** [comment]
Thanks for the tip, went for the constant as caching introduces another list of questions
