### ISSUE TITLE
I18n.js doesn't import locales outside of 'config/locales' folder.

### ISSUE THREAD

**Issue by Shoroh** [fnando/i18n-js#515]
Hi.

I need to store some locales in `app/some_folders`, not in 'config/locales' folder.

I did as Rails manual said:

> You can change the default locale as well as configure the translations load paths in config/application.rb as follows:

```ruby
config.i18n.load_path += Dir[Rails.root.join('app', 'some_folder', '**', '*.{rb,yml}').to_s]
```

It works well in Rails partials, I see translations in scope.
But I18n.js returns `missing`.

Does I18n.js use Rails app config to look up locale files? Or is there any custom I18n.js config to setup it?

**Comment by Shoroh** [comment]
As I see [here](https://github.com/fnando/i18n-js/blob/6d821a3afad14820a94bd60c399308763316e7d0/lib/i18n/js/middleware.rb#L68), it does use App config:

```ruby
def verify_locale_files!
  valid_cache = []
  new_cache = {}

  valid_cache.push cache_path.exist?
  valid_cache.push ::I18n.load_path.uniq.size == cache.size

  ::I18n.load_path.each do |path|
    changed_at = File.mtime(path).to_i
    valid_cache.push changed_at == cache[path]
    new_cache[path] = changed_at
  end

  return if valid_cache.all?

  save_cache(new_cache)

  ::I18n::JS.export
end
```

But it started to work only after I removed `tmp` folder.
So, please close the issue, if it's not a bug.

**Comment by PikachuEXE** [comment]
One of known issues, due to how sprockets work:
https://github.com/fnando/i18n-js#missing-translations-in-precompiled-files-after-adding-any-new-locale-file

**Comment by Shoroh** [comment]
Thanks @PikachuEXE,

I'm closing it.
