### ISSUE TITLE
Select Languages for i18n-js

### ISSUE THREAD

**Issue by c2ofh** [fnando/i18n-js#517]
Hey, 

we have 14 languages in our application config, because a user can set up different content for each language (for the external frontend).
The user backend is just translated in german and english, so I need just "en" and "de" in my i18n.js.
Because we're also using fallbacks, if a translation is missing, all 14 languages are included with all keys and the fallback language.

Is there a posibility to define the languages to get rid of the useless translations?

**Comment by PikachuEXE** [comment]
How do you use this gem?

You can also read this section for more info
https://github.com/fnando/i18n-js#export-configuration-for-translations

**Comment by c2ofh** [comment]
Can be closed. I've added
```yml
only: ['de.*','en.*']
```
