### ISSUE TITLE
Updating to 3.0.11 broke exclusions in our i18n-js.yml configuration

### ISSUE THREAD

**Issue by tubbo** [fnando/i18n-js#518]
We use a special `i18n-js.yml` configuration in production to keep the size of our JS bundle down. It looks something like this:

```yaml
translations:
  - except: ['*.activerecord', '*.mongoid', '*.errors', '*.helpers', '*.views', '*.hello', '*.faker']
```

When we upgraded to **v3.0.11** from v3.0.10, it seemed that this configuration was no longer being respected...

```javascript
I18n.t('faker.address.city.0')
"#{city_prefix} #{Name.first_name}#{city_suffix}"
```

In v3.0.10, this would happen:

```javascript
I18n.t('faker.address.city.0')
"[missing \"en.faker.address.city.0\" translation]"
```

This resulted in the JS bundle ballooning in size because of all the extra i18n strings it had to load.

**Comment by PikachuEXE** [comment]
Sorry for late response, was busy with other projects

This gem has [some "exceptions" related tests](https://github.com/fnando/i18n-js/blob/master/spec/ruby/i18n/js_spec.rb#L210) already
Can you try to make it fail?

Just post the changes you made here so I can run the tests locally with different versions

**Comment by tubbo** [comment]
this turned out to be something related to a monkey-patch in our app, and probably isn't worthwhile as an issue on the i18n-js project. gonna close for now, might re-open later if we do find an issue..
