### ISSUE TITLE
Fallback not working

### ISSUE THREAD

**Issue by jorge-sanz** [fnando/i18n-js#525]
I am using the `i18n-js` npm package and I always receive `[missing "name of scope" translation]`.

How can I set a language by default for missing translations?

This what I have configured so far:
```
I18n.defaultLocale =
I18n.locale =
I18n.translations =
I18n.translations[appLanguage] =
``` 
Thank you!

**Comment by PikachuEXE** [comment]
Try `I18n.fallbacks = true`
It will fallback to `I18n.defaultLocale` for missing translations

**Comment by mikehardy** [comment]
This question is stale but I had the same problem, and (of course!) setting the appropriate configuration as @PikachuEXE mentioned worked. This is probably closeable

Thanks!

**Comment by PikachuEXE** [comment]
@mikehardy 
Nice to know you got it working :)
closing~

**Comment by michelson** [comment]
in the latest version use:

`i18n.enableFallback = true;`

**Comment by mikehardy** [comment]
@michelson can you back up this assertion? I checked and I still see fallbacks:

https://github.com/fnando/i18n-js/blob/1269f72c9e79570267ecd4e94097c1b9499e7832/app/assets/javascripts/i18n.js#L186

**Comment by michelson** [comment]
hi @mikehardy, I can confirm that the fallbacks on v4 are working ok.
this is my code:

```javascript
import { I18n } from 'i18n-js';
import translations from '../locales/translations.json';
const i18n = new I18n(translations);
i18n.enableFallback = true;
i18n.locale = document.documentElement.lang || 'en';
export default i18n;
```

then, in every file where I need to use the I18n I import that file

I hope it helps!

**Comment by mikehardy** [comment]
@michelson I  believe you, but that's still an assertion. I actually quoted code showing the old 'fallbacks' property, I have not seen anything with enableFallback yet, but perhaps I missed it?

It's also "fallbacks" in the docs: https://github.com/fnando/i18n-js#fallbacks

So I don't understand where 'enableFallbacks' comes from and I was hoping for a concrete link to code where it seemed like the way to do things
