### ISSUE TITLE
Can't mock

### ISSUE THREAD

**Issue by stereodenis** [fnando/i18n-js#526]
### Describe your environment

* React-Native version: 0.57.5
* I18n-js: 3.1.0
* OS version: Mac OS 10.13.6 (17G65)
* react-native-languages version: 3.0.1

no automock

### How to repeat issue and example

After mocking
```
jest.mock('react-native-languages', () => ({
  RNLanguages: {
    language: 'en',
    languages: ['en'],
  },
}))
```
I had this error:
```
TypeError: Cannot set property 'locale' of undefined

      5 | I18n.locale = language
```

```
#I18n.ts
import { language } from 'react-native-languages'
import I18n from 'i18n-js'
import {ru, pl, uk, en} from './locales'

I18n.locale = language
....
export default I18n
```

**Comment by PikachuEXE** [comment]
I have no idea above TypeScript
But it seems the import is incorrect and `I18n` becomes `undefined`?

**Comment by nickjohngray** [comment]
Looks like you also need to mock i18n-js
