### ISSUE TITLE
Support week of the year

### ISSUE THREAD

**Issue by haffla** [fnando/i18n-js#528]
Ruby's `strftime` supports `%W` and `%U` which gets the week number of the year (0..53). Is there a plan to support this / would you accept a PR that implemented this?

https://apidock.com/ruby/DateTime/strftime

**Comment by haffla** [comment]
Well the use case is that I want to know the number of the week. For example right now (14.12.2018) we are in week 50. `strftime` in other languages has it, so I think it would be nice if i18n-js had it, too.

Which brings me to something else: I just found https://github.com/samsonjs/strftime which is `strftime` for Javascript which supports all modifiers of the original C `strftime` (not sure about this last statement, but wasn't the C function first and all other languages' `strftime` are based on this implementation?). So wouldn't it make sense to use this lib?

I know that would be a huge deal and change to `i18n-js`, just exploring ideas.

**Comment by PikachuEXE** [comment]
Let's start with `%W` and `%U` support first
Got any idea on how to calculate?
I search stackoverflow and found [this answer](https://stackoverflow.com/a/17999593/838346)
I got no test case so I am not sure if that works properly or not

**Comment by haffla** [comment]
Sorry I haven't had time for this yet. It seems the SO answer you have linked to depends on Google Spreadsheets. I will look into this.
