### ISSUE TITLE
after applying react-redux, i18n translation content not updated after url change with react-router-redux

### ISSUE THREAD

**Issue by impossible-creations** [fnando/i18n-js#534]
When applying redux connect, i18n content will not update after "Link to" of react router.

Just simply npm install react, react redux, react router and i18n-js can reproduce the situation.

**package.json**
...
"i18n-js": "^3.1.0",
"react-redux": "^5.0.7",
"react-router-redux": "^5.0.0-alpha.9",
...

**index.js**
import React from 'react'
import ReactDOM from 'react-dom'

import {
    createStore, combineReducers, applyMiddleware,
} from 'redux'
import { Provider } from 'react-redux'

import createHistory from 'history/createBrowserHistory'
import { Route } from 'react-router'

import {
    ConnectedRouter, routerReducer, routerMiddleware,
} from 'react-router-redux'

// i18n-js
import I18n from 'i18n-js';

**header.js**
...
<Link to="/en-us/contact">Contact in English</Link>
<Link to="/zh-hk/contact">Contact in Chinese</Link>
...

**contact.js**
class Contact extends Component {

...
<h2>{i18n.t("contact.title")}</h2>
...

export default Contact; <- if not connected to Redux, then react-redux + i18js + react router works well

export default connect(mapStateToProps)(Contact); <- if connected to Redux, then i18n translation content in contact page will not update after "Link to" url update

**Comment by PikachuEXE** [comment]
I don't anything about React so I can't figure out if there is anything wrong in react setup :P

Let's test without React, like calling `i18n.t("contact.title")` in console (not in `window`? set it)
If this works, it's probably not `i18n-js` issue
