### ISSUE TITLE
Server side rendering with I18n.t

### ISSUE THREAD

**Issue by hardikjain29** [fnando/i18n-js#538]
Server: Node.js

The issue is when we do server side rendering of the `I18n.t` function.

All our pages have text wrapped in the `I18n.t()`. The client side perfectly executes the function and generats the desired translations. But on server(Node.js) while doing SSR the function returns `missingTranslations`(screenshot).

Is there a way around this?

Thanks for the help.

![image](https://user-images.githubusercontent.com/13768932/60118473-12579c00-979a-11e9-8b94-a57b2507c312.png)

**Comment by PikachuEXE** [comment]
I don't know much about "server rendering"
When `missingTranslations` is generated it means the translation entry is missing
You can try to look at the value of `I18n.translations` on **server side**
If it's missing or incomplete then you need to find a way to set/populate it
