### ISSUE TITLE
Using full sentences as keys including dots

### ISSUE THREAD

**Issue by mattias-persson** [fnando/i18n-js#540]
As brought up in #441, I'd love to use full sentences as keys. However, when including a dot in the key the translations don't work. The other issues have been closed without any effort to find a solution for this, as far as I can see. Is there any way to make it work?

**Comment by PikachuEXE** [comment]
You change `I18n.defaultSeparator` which defaults to `.`
https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js#L174-L196

Or you can take a look at #541 and see if it fits your need

**Comment by mattias-persson** [comment]
Awesome, thanks!

**Comment by PikachuEXE** [comment]
So do you still need #541?

**Comment by mattias-persson** [comment]
@PikachuEXE I just set `I18n.defaultSeparator` to something other than `.` and that worked for me.
