### ISSUE TITLE
Multiple translation use without changing locale and default locale

### ISSUE THREAD

**Issue by akshayrajoria** [fnando/i18n-js#544]
Hello Team,

I am using this repo in my react native project 
i have to use i18n.t for translating literals 

but in my app i have requirement like i have locale selected english( en-US ) but in some litreals i want to use "fr-CA" for that i found some code in readme.md  please see below code

**" You can use translate your messages:
I18n.t("some.scoped.translation", {locale: "fr"}); "**

if my locale and default locale selected as english( en-US ) and i want to use "fr-CA" for some texts
so i used this approach I18n.t("some.scoped.translation", {locale: "fr-CA"});
but its showing only english text from translation file 

i have both translation file in my project "en-US", "fr-CA" 
but it always translate litreal in english only

so how can i use fr-CA litreals without changing my current locale english( en-US )

thanks in advance 

@fnando @Sija @DefV @rywall @masatomo

**Comment by PikachuEXE** [comment]
How do you test it?
Is the translation object setup correctly for `"fr-CA"`?

Maybe you explain your way of testing like this:
```javascript
I18n.translations["fr-CA"].some.scoped.translation // -> "something in fr-CA"
I18n.translations["en"].some.scoped.translation // -> "something in en"

// Expected
I18n.t("some.scoped.translation", {locale: "fr-CA"}) // -> "something in fr-CA"
// Actual
I18n.t("some.scoped.translation", {locale: "fr-CA"}) // -> "something in en"
```

**Comment by akshayrajoria** [comment]
@PikachuEXE 
Ya correct like i am using this way please see below 
now my locale is selected english ("en") and in i18n object 
and in i18n.translation i have en.json file
for normal translation i am writing code this way please see below 
i18n.t("addToTrx") and the output for that code is "Add to Basket" this will work properly 

but for the some text like "Add to Basket" i want to print in "fr-CA" locale without changing my locale ("en") so for that i am using like 

I18n.t("addToTrx", {locale: "fr-CA"}) it should show in Canadian french  like "ajouter au panier" 
but it also printing in english only  "Add to Basket"

**Comment by PikachuEXE** [comment]
I just did a simple test in browser console:
![image](https://user-images.githubusercontent.com/1018543/63500542-97da9c80-c4fc-11e9-81a2-164e6f28cf30.png)

The code is:
```javascript
if (typeof I18n.translations !== "object") { I18n.translations = {} }
if (typeof I18n.translations["en"] !== "object") { I18n.translations["en"] = {} }
if (typeof I18n.translations["fr-CA"] !== "object") { I18n.translations["fr-CA"] = {} }
I18n.translations["en"]["addToTrx"] = "Add to Basket"
I18n.translations["fr-CA"]["addToTrx"] = "ajouter au panier"

I18n.locale = "en"
I18n.t("addToTrx")
I18n.t("addToTrx", {locale: "fr-CA"})
```

**Comment by akshayrajoria** [comment]
thanks @PikachuEXE 
actaully i am thinking and implementing the same thing what u told in your comment
