### ISSUE TITLE
Not getting currency unit for locale en-GB

### ISSUE THREAD

**Issue by akshayrajoria** [fnando/i18n-js#545]
Hi Team,
@PikachuEXE @Sija @fnando @DefV @rywall @masatomo
<img width="824" alt="Screen Shot 2019-08-27 at 5 27 35 PM" src="https://user-images.githubusercontent.com/10883534/63769497-95a78200-c8f0-11e9-8180-e876b84cd484.png">
<img width="1533" alt="Screen Shot 2019-08-27 at 5 27 53 PM" src="https://user-images.githubusercontent.com/10883534/63769513-a22bda80-c8f0-11e9-977a-5f1381429134.png">

i am using this repo in my react native app 

I set default locale and locale is en-GB

but when i am passing in "0" in ".toCurrency" will return me $0.00 but it should be £0.00  

is any thing i am doing wrong 

this is i am using when there is no value in cart and i am showing total as zero with unit

please check attachment for i18n object for locale

and this code i have written for show zero value
this.zeroAmount = I18n.toCurrency(0, {delimiter: "", separator: I18n.t("separator"), precision: 2});

so tho output of code is $0.00 but it should £0.00

thanks in advance

**Comment by PikachuEXE** [comment]
Can you provide a small script for reproducing this issue in a browser?
like:
```js
I18n.locale = "en"
I18n.translations = I18n.translations || {}
I18n.translations["en-GB"] = I18n.translations["en-GB"] || {}
// More translations I don't know what do you have so add them yourself

I18n.toCurrency(0)
```

Also do you have the same issue for other locales (if you use any)?

**Comment by akshayrajoria** [comment]
@PikachuEXE 
Hi ,
ya i am using other translations also like fr-CA this issue happend on selecting fr-CA also

In the below code is my configuration for selecting locale for i18n config 

const { languageTag, isRTL } = locale && translations[locale] && { languageTag: locale, isRTL: fallback.isRTL } ||
        (RNLocalize.findBestAvailableLanguage(Object.keys(translations)) || fallback);
    // update layout direction
    react_native_1.I18nManager.forceRTL(isRTL);
    // set i18n-js config
    // @ts-ignore
    i18n.locale = languageTag;
    // @ts-ignore
    i18n.defaultLocale = languageTag;
    // @ts-ignore
    i18n.translations = { ["en"]: translations["en"],
        ["fr-CA"]: translations["fr-CA"],
        ["en-GB"]: translations["en-GB"] };



 i need one more clarification. if there is a some missing translation it will show me like "missingTranslation.fr-CA.someText" 
is there any way to check if i call i18n.t("someText") so i know this is translation is available or not 
on my locale that is configured for use

Thanks in advance

**Comment by PikachuEXE** [comment]
Just answering `is there any way to check a translation entry is available or not`:

Start reading from https://github.com/fnando/i18n-js#setting-up
There is a section for handling missing translations

**Comment by akshayrajoria** [comment]
@PikachuEXE 
ok thank you that i have already read 

and what abt missing unit i have used fr-CA and en-GB both giving me $ only when i passed 0 in .toCurrency()

**Comment by PikachuEXE** [comment]
I don't understand your last comment
Please provide the minimal translation/settings so I can try in a browser too

Reading from [`toCurrency ` source code](https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js#L779)
It's using `number.currency.format` or `number.format` or default value which is `$`
So when providing the script please include the translation entries for one of these 2 keys
for both languages

**Comment by PikachuEXE** [comment]
Here is a very simple script made by me
You can copy and edit it to match your setup
```js
I18n.translations = I18n.translations || {}
I18n.translations["en-GB"] = I18n.translations["en-GB"] || {}
I18n.translations["en-GB"] = I18n.translations["en-GB"] || {}
I18n.translations["en-GB"]["number"] = I18n.translations["en-GB"]["number"] || {}
I18n.translations["en-GB"]["number"]["currency"] = I18n.translations["en-GB"]["number"]["currency"] || {}
I18n.translations["en-GB"]["number"]["currency"]["format"] = {
      unit: "£"
    , precision: 2
    , format: "%u%n"
    , sign_first: true
    , delimiter: ","
    , separator: "."
  }

I18n.locale = "en-GB"
I18n.toCurrency(0)
```
I get `"£0.00"` with this script

**Comment by akshayrajoria** [comment]
@PikachuEXE thank you for your help

**Comment by akshayrajoria** [comment]
@PikachuEXE 

By default a missing translation will be displayed as

[missing "name of scope" translation]

can i change the missing translation message "translationNotFound" like that message instead of this [missing "name of scope" translation] 

i got error bcoz i am using typescript in my project 

what is the syntax to change the missing translation message 

ERROR - Cannot assign to 'missingBehaviour' because it is a read-only property.


and i also tried to add prefix i got the same error. 
the code is 
i18n.missingTranslationPrefix = 'notFound: '; 

ERROR - Cannot assign to 'missingTranslationPrefix' because it is a read-only property.

**Comment by PikachuEXE** [comment]
I guess the type definition is incorrect if it shows `missingBehaviour` & `missingTranslationPrefix` as readonly
Which is another issue :S

You can see https://github.com/fnando/i18n-js#setting-up
for how to use `missingBehaviour`, `missingTranslationPrefix` & `missingTranslation`

Ignore TS error for now, if cannot ignore I will take a look at the definition and try to fix it
(I think it's possible to use your own version of definition)

**Comment by PikachuEXE** [comment]
I have run the test on for `i18n-js` typing on https://github.com/DefinitelyTyped/DefinitelyTyped
I see no error in test result and I can see assignments to `missingBehaviour`, `missingTranslationPrefix` & `missingTranslation` in test script
So I don't know what TS error can be caused by it

Please share more details if you still encounter TS errors

**Comment by akshayrajoria** [comment]
sure i will get back to you 

thanks for your help

**Comment by akshayrajoria** [comment]
@PikachuEXE 
Hi 
Is there any way that if any translation is not found so it automatically pick that literal from "en-US" locale

like i am writing code for translation I18n.t("someTextHere"); and my locale is set to fr-CA

and we have "fr-CA.json" JSON file were all literals stored 

so if this literal "someTextHere" is missing so it automatically pick from locale "en-US"

without using I18n.t("someTextHere", {locale: "en-US"}); " 


thanks in advance

**Comment by PikachuEXE** [comment]
I think right now the complex version of "fallback" is implemented via translation generation
https://github.com/fnando/i18n-js#fallbacks

However there is also JS version of fallback (but I have never used it or read the implementation)
https://github.com/fnando/i18n-js#setting-up (search for `fallback`)

**Comment by tafelito** [comment]
@PikachuEXE do you manually need to setup the currency/number format for every locale used?

**Comment by PikachuEXE** [comment]
@tafelito 
For pure JS setup I think you do
If you generate the translations object then you can "fallback" to certain locale I guess
