### ISSUE TITLE
i18n > French locale > Decimal separator should be a comma and it's a point

### ISSUE THREAD

**Issue by LucasBrazi06** [fnando/i18n-js#552]
I switched to french locale:

```
i18n.locale = 'fr';
```

An converted a number:
```
i18n.toNumber( 1.28 );
```

But it displays 1.28 instead of 1,28.

The comma is the decimal delimiter in french.

Could you please check?

Thanks in advance!

**Comment by LucasBrazi06** [comment]
What do you mean by I need 'number.format' ?
Isn't it provided by i18n-js ?
Should I provide this info per locale ?
Thanks in advance

**Comment by PikachuEXE** [comment]
I don't know what's your setup so please post what's inside `number.format` for `fr`

**Comment by LucasBrazi06** [comment]
I haven't setup anything concerning number.format and I  don't know how to access this var, it's even not documented in your readme.md
Could you please clarify?

**Comment by PikachuEXE** [comment]
When using `toNumber` without providing options
It will look for values at `number.format`
![image](https://user-images.githubusercontent.com/1018543/67666176-332d3980-f9a6-11e9-9cfb-0bcc4b3f41be.png)

So I think it would be good for you to post what's inside `number.format` by running
```javascript
i18n.locale = 'fr';
i18n.lookup("number.format")
```
in console and post the result

**Comment by tafelito** [comment]
@PikachuEXE 

```js
i18n.locale = 'fr';
i18n.lookup("number.format")
```

console

```js
undefined
```

**Comment by PikachuEXE** [comment]
@tafelito 
If you don't provide the value in your using locale
it will use the final fallback values hardcoded in JS:
https://github.com/fnando/i18n-js/blob/v3.5.1/app/assets/javascripts/i18n.js#L143-L168

**Comment by tiagocpeixoto** [comment]
My solution (based on Typescript) is reproduced below. Supports almost all languages.

English (en): $1,000.00
Portuguese (pt): $1.000,00
French (fr): $1 000,00

```typescript
i18n.translations = {
  ...
  [i18n.locale]: {
    number: {
      currency: {
        format: {
          unit: "$",
          precision: 2,
          format: "%u%n",
          sign_first: true,
          separator: getSeparator(i18n.locale, "decimal") ?? ".",
          delimiter: getSeparator(i18n.locale, "group") ?? ",",
        },
      },
      format: {
        precision: 2,
        sign_first: true,
        separator: getSeparator(i18n.locale, "decimal") ?? ".",
        delimiter: getSeparator(i18n.locale, "group") ?? ",",
      },
    },
  },
};

function getSeparator(
  locale: string,
  separatorType: string
): string | undefined {
  const numberWithGroupAndDecimalSeparator = 1000.1;
  return Intl.NumberFormat(locale)
    .formatToParts(numberWithGroupAndDecimalSeparator)
    .find((part) => part.type === separatorType)?.value;
}
```
