### ISSUE TITLE
How do I translate a number

### ISSUE THREAD

**Issue by talal7860** [fnando/i18n-js#556]
I want to translate a number to arabic. So, 1 becomes ۱, 2 becomes ٢, and so on. I can easily add a key for a number and translate it, but the problem becomes with numbers in one more than 1 unit, 12, 13. I do see methods `toNumber` `.l`, but I don't know which key to use to add translations for them.

**Comment by PikachuEXE** [comment]
You just use `t` or `translate` (alias of `t`)

![image](https://user-images.githubusercontent.com/1018543/68568637-1a894d00-0497-11ea-9a7e-0652fbfd399c.png)

Using number as keys seems working too

![image](https://user-images.githubusercontent.com/1018543/68568703-50c6cc80-0497-11ea-9fae-dec848f8d959.png)

**Comment by talal7860** [comment]
Thanks @PikachuEXE 
This works great, the thing I'm trying to translate is the numerals itself. So, 
1 = ١
2 = ٢
3 = ٣
12 = ١٢
35 = ٣٥

I can put in individual translations for each number, but what happens when I the numbers starts getting bigger, is there a way i18n can handle this?

**Comment by PikachuEXE** [comment]
I don't think I18n-js is built to handle this kind of translation automatically
No translation entry value provided = Not translated (maybe fallback)
You should find another library for your need

**Comment by talal7860** [comment]
Can I work on a PR to address this, if you would like to have this in i18n-js ?

**Comment by PikachuEXE** [comment]
I think this is a specific topic which requires quite some work and should be done on a separate project.

I found some libraries like:
- https://www.npmjs.com/package/number-to-arabic
- https://www.npmjs.com/package/number-to-words (But this one is for English only it seems)
