### ISSUE TITLE
I18n.t is not bound

### ISSUE THREAD

**Issue by bisubus** [fnando/i18n-js#559]
It's pretty much standard to use a shortcut for `translate` like `t('foo')`. However, it isn't bound to the context in the library.

This works:
```js
I18n.t('foo')
```

This causes an error:
```js
const {t} = I18n
t('foo')
```
The suggestion is to bind shortcuts to allow this:
```js
  I18n.t = I18n.translate.bind(I18n);
  I18n.l = I18n.localize.bind(I18n);
  I18n.p = I18n.pluralize.bind(I18n);
```
Original methods could be left intact because this benefits extendability.

**Comment by PikachuEXE** [comment]
I am not an JS expert
Please let me know if there is any performance impact / strange gotcha if I do that
Also please provide an example for `benefits extendability`

**Comment by bisubus** [comment]
No hidden costs, bound functions have virtually same performance as regular functions.  `bind` is ES5, since a collection of polyfills is maintained in shim.js for some purpose, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind#Polyfill could be added as well.

Currently the lib uses `this` everywhere, this allows to extend it without forking, which is a good thing:

```js
myI18n = Object.create(I18n);
myI18n.translate = (...args) => ... // custom implementation
```
An alternative that needs no `bind` is to hardcode `I18n` reference instead of `this` in all method. This allows to dereference all methods and use them like `var t =  I18n.t; t(...)` if needed but is a bad practice because this counteracts the inheritance described above for no good reason.

So `bind` seems to be a reasonable solution here.

**Comment by PikachuEXE** [comment]
OK it seems reasonable
Can you come up with a PR for that?
I am on vacation so I can't do much coding but I can still review PR

**Comment by bisubus** [comment]
Sure. Changes are very straightforward, I updated specs for consistency. Enjoy your vacation!
