### ISSUE TITLE
Fallback locales, which are not in I18n.available locales, are not included

### ISSUE THREAD

**Issue by vizo** [fnando/i18n-js#562]
Fallback locales, which are not in I18n.available_locales, are not included.
For example:
```ruby
I18n.available_locales = [:"en-GB", :"sl-SI"]
I18n.fallbacks[:"en-GB"] = ["en-GB", "en"]
I18n.fallbacks[:"sl-SI"] = ["sl-SI", "sl"]
```
"en" and "sl" locale files are not included in JS or json.

Any idea?
Thanks in advance.

**Comment by PikachuEXE** [comment]
This library fetch translations based on `I18n.available_locales`
https://github.com/fnando/i18n-js/blob/v3.6.0/lib/i18n/js.rb#L172-L184

I don't understand why you want `en` & `sl` to be present in `translations` object
Would you mind explain a bit more?
I don't know what to recommend until I understand your intention

**Comment by vizo** [comment]
I want all fallbacks and their plural rules to be included even if they are not included as available_locales. Rails I18n works exactly the same. If i chose "en-GB" as current locale, fallback of "en-GB" will be also "en", even that "en" is not included in available_locales but it's set as fallback.

So to get the same functionality we should export all available_locales + all fallbacks for each available_locale, if fallbacks is true.

**Comment by PikachuEXE** [comment]
OK let me explain my current understanding
You have some available locales, with fallbacks
Assume you have translations like this:
```ruby
# I18n.backend.translations
{
  en: {
    hello: "Hello",
  },
  :en-GB => {
    currency: "Pound",
  },
}
```
Your expected result is:
```javascript
// I18n.translations
{
  :en-GB => {
    hello: "Hello",
    currency: "Pound",
  },
}
```
Your actual result is:
```javascript
// I18n.translations
{
  :en-GB => {
    currency: "Pound",
  },
}
```

Please correct me if I am wrong

**Comment by vizo** [comment]
> OK let me explain my current understanding
> You have some available locales, with fallbacks
> Assume you have translations like this:
> 
> ```ruby
> # I18n.backend.translations
> {
>   en: {
>     hello: "Hello",
>   },
>   :en-GB => {
>     currency: "Pound",
>   },
> }
> ```
Correct.
> 
> Your expected result is:
> 
> ```js
> // I18n.translations
> {
>   :en-GB => {
>     hello: "Hello",
>     currency: "Pound",
>   },
> }
> ```
Wrong. It should be same as backend, not merged, because plural rules can be different for fallback locale. I18n-js lib should do fallbacks on client side. 
```js
// I18n.translations
{
  en: {
    hello: "Hello",
  },
  :en-GB => {
    currency: "Pound",
  },
}
```
> 
> Your actual result is:
> 
> ```js
> // I18n.translations
> {
>   :en-GB => {
>     currency: "Pound",
>   },
> }
> ```
True.
> 
> Please correct me if I am wrong
