### ISSUE TITLE
Fallback locale with interpolation

### ISSUE THREAD

**Issue by Mr-Timur** [fnando/i18n-js#563]
When on one language locale is `null` and the default locale have e.g.`Hi %{username}!`, fallback is not working and cause an error: `Uncaught (in promise) TypeError: Cannot read property 'other' of null`
http://joxi.ru/8An7783h7GWpRr

**Comment by EddieOne** [comment]
Did you set it? The setting is set to false by default. `I18n.fallbacks = true;`

**Comment by Mr-Timur** [comment]
> Did you set it? The setting is set to false by default. `I18n.fallbacks = true;`

Yes, I set it. And simple translations fallback without variable interpolation is working
