### ISSUE TITLE
translations.js is missing

### ISSUE THREAD

**Issue by radinreth** [fnando/i18n-js#566]
In the document says that:
![image](https://user-images.githubusercontent.com/5484758/79962010-b04aee80-84b1-11ea-9711-0e756e1820aa.png)

But I return the following error
![image](https://user-images.githubusercontent.com/5484758/79962239-01f37900-84b2-11ea-9efa-f58567b0efc3.png)

My development environment:

Rails version             6.0.2.2
Ruby version              ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

c

**Comment by PikachuEXE** [comment]
If you haven't added the middleware, add it
If you have added the middleware, then I need more details for your setup
i.e. What did you change besides installing the gem

You can also run `::I18n::JS.export` in console to see if it works (coz the middleware just runs it on every request)

**Comment by radinreth** [comment]
@PikachuEXE I know the reason:

`translations.js` is not generate under public/javascripts/ directory
instead it generates under app/assets/javascripts/i18n/

so if I include: `javascript_include_tag "translations", skip_pipeline: true` (mentioned in doc)
it will break,

so now I just moved the generated file into public/javascripts/ directory,
it works!

**Comment by radinreth** [comment]
resolved
