### ISSUE TITLE
Cache busting when using without asset pipeline

### ISSUE THREAD

**Issue by buhrmi** [fnando/i18n-js#571]
I'm trying to find a way to force a re-download of translations.js when the file changes.

The issue here is that ´<%= javascript_include_tag "translations", skip_pipeline: true %>´ does not attach a cache busting parameter to the URL.

Is there a way to add some sort of cache busting here?

**Comment by buhrmi** [comment]
I'm asking because I like the setup where only the current locale is loaded, eg like this: `<%= javascript_include_tag "i18n/#{I18n.locale}", skip_pipeline: true %>`. I didn't find a way to do the same thing when going through the asset pipeline.

**Comment by PikachuEXE** [comment]
If you look at the source code 
https://github.com/fnando/i18n-js/blob/b572f10cb682f0cc7fed93384bbe6ebc85212bfd/app/assets/javascripts/i18n/filtered.js.erb#L22
It just calling `I18n::JS.filtered_translations.to_json`

`I18n::JS.filtered_translations` returns something like
```ruby
{
  en: {tons: {of: :translation_entries}}
}
```

You can get and customize output with `I18n.backend.translations`
