### ISSUE TITLE
Allow transformation to camelcase keys

### ISSUE THREAD

**Issue by quorak** [fnando/i18n-js#573]
Rails offers the option to transform properties into camelcase for their js integrations at many places. Would be nice when we can use the language keys in js also in camelcase. WDYT?

**Comment by PikachuEXE** [comment]
I am fine with it but I don't have time to develop a new feature
PR is welcome
Let me know if you need example PR for making changes

**Comment by fnando** [comment]
Implemented on [v4](https://github.com/fnando/i18n/commit/d48ce75aab36ae413c29a46e7e66f30975744df1)'s client-side only.

As I see, this is a feature that is useful for projects that share translations between Rails and client-side. If you don't use Rails, then you could as well just write everything as camelcase.
