### ISSUE TITLE
Does the t method support nestedObject notation?

### ISSUE THREAD

**Issue by mitchdowney** [fnando/i18n-js#578]
I have a locales JSON file with an object like this:

```
{
    "page1": {
        "header": "Header text here"
    }
}
```

Does this library support nestedObject notation? I would like the call the `t` method like this: `t('page1.header')`

**Comment by PikachuEXE** [comment]
Short answer: Yes

Long answer: It support when the `I18n.translations` is setup properly. See README for examples

**Comment by mitchdowney** [comment]
Thanks for confirming. It's working for me now. I had an issue with React Native / XCode that was unrelated to your library.

It appears it wasn't working for me previously just because my locales JSON file in XCode resources was not updated properly. Re-building the app from within XCode fixed the problem for me.
