### ISSUE TITLE
Fallback with pluralization for keys that haven't been declared

### ISSUE THREAD

**Issue by khier996** [fnando/i18n-js#579]
When I try to translate some key with `count` param, I expect it to fallback to default locale when that key is not defined. 
But instead when I run ```I18n.t('xxx.some_key.xxx', { count: 2 })```, I get this error:
```Uncaught TypeError: Cannot read property 'some_key' of null```
I saw this commit - https://github.com/fnando/i18n-js/pull/433/commits/7c02c223e3aacbb9ff280118c992be34c91dd9f4 which I think tried to solve this issue, but after reading the automated tests from that commit, I think the fix only assumes that the key is defined, but value is null. I tested it with my code and indeed, fallbacks work. But that's not what we want. We have a pretty large app and translations for different languages are gonna be added by chunks. So, if some key is not defined, ideally we'd want to fallback on default language. Currently it completely breaks the page.

**Comment by PikachuEXE** [comment]
Maybe you can try to fork and add test case to reproduce the issue?
Then we can think about how to fix it
