### ISSUE TITLE
Support for external formatters

### ISSUE THREAD

**Issue by wwahammy** [fnando/i18n-js#584]
Right now, there's no way of adding an external formatter from outside the actual Gem. In my use-case, I need a custom formatter, but to do so I need to modify the library. This is not ideal because I then need to maintain my own fork of this repo even though effectively, all I've done is add a formatter and specs for that formatter and some minor changes to make it possible to support my formatter. My changes are partially one-offs but they may  illustrate what I'm actually trying to do https://github.com/houdiniproject/i18n-js/commit/7a6a839eb348b7b1e7c5f02a34580b353f642c17

Ideally, it should be possible to support formatters from somewhere outside of the library itself, like from another gem, inside my Rails project, etc, and then run i18n-js unmodified.

Is this something that could be implemented in i18n-js? I'm willing to help do so there's agreement on how that feature should look and that it should be added.

Also, it's totally possible that my description of the problem is not clear, in which case, don't hesitate to ask so I can clarify!

**Comment by PikachuEXE** [comment]
Interesting request
This means the option `json_only` is actually a "hidden" formatter option
And you want a custom formatter support
However formatter is attached to a segment
Does that mean we should allow every segment to have different formatter?

**Comment by fnando** [comment]
With [v4](https://github.com/fnando/i18n-js/discussions/609), my suggestion is to pipeline transformation, as in you first call `i18n export`, then execute a command/code/etc to transform the canonical output into something you want/need.

I don't see any advantages on having a flag specific for output transformation (like `--transform`) over calling the Ruby API directly, or running a command after calling `i18n export`.
