### ISSUE TITLE
How to set default variable in translation?

### ISSUE THREAD

**Issue by jagwingchoy** [fnando/i18n-js#585]
Hi there, **really sorry** that I couldn't find a solution in StackOverflow and document inside this repo. Here is my situation example:

I am translating some sentence like below: (and what I would like to archieve)

    // in contact us page
    I18n.t('contact_us_page.description')
    // in about us page
    I18n.t('about_us_page.description')

And those description translation contains a `email` variable:

    "about_us": { "description": "Here is the description. Feel free to find us via email: %{email}" },
    "contact_us": { "description": "Here is another description. Contact us via email: %{email}" },
    "email": "sample@example.com"

I don't want to add the email variable every time when I render the translation in a page like this:

    I18n.t('contact_us_page.description', { email: I18n.t('email') })

I am tried making a `scope` like the documentation but I am very confused about if I have made it wrong or it is the solution that I needed. Can anyone help and teach me how to achieve it? Appreciate for any help.

## Background
I am using in `react-native` together with `react-native-localize` package.

**Comment by PikachuEXE** [comment]
Either you edit the existing method
Or create a new method that calls `I18n.t` with your "default options"
