### ISSUE TITLE
Can I have a DEBUG Mode ?

### ISSUE THREAD

**Issue by joaovbibiano** [fnando/i18n-js#587]
I have a translation team... Its possible to show, at the same time, the KEY and translation when some condition is set to true?

Thank you!

**Comment by PikachuEXE** [comment]
This seems like a feature request
But I am not sure what you are requesting
Can you provide expected input/output/options?

**Comment by joaovbibiano** [comment]
> This seems like a feature request
> But I am not sure what you are requesting
> Can you provide expected input/output/options?

The first time, I was asking if you have this option

It would be like

On initialize the i18n-js, set some configuration like i18n.devMode = true

So, in any input who outputs the translate, it would also add the key

Without the option

"Please, press to confirm"

With this option

"{common.confirmMessage} - Please, press to confirm"

**Comment by PikachuEXE** [comment]
What's this `common.confirmMessage`?
Is that the key used in `I18n.t` like `I18n.t("common.confirmMessage")`?

Maybe overriding `I18n.interpolate` would be quicker to get what you want and you can customize it

**Comment by joaovbibiano** [comment]
> What's this `common.confirmMessage`?
> Is that the key used in `I18n.t` like `I18n.t("common.confirmMessage")`?
> 
> Maybe overriding `I18n.interpolate` would be quicker to get what you want and you can customize it

Wow... really...

I will try, or, if it not works well, I can make myself `t` funcion

Obrigado
