### ISSUE TITLE
switch to different i18n backend throws error

### ISSUE THREAD

**Issue by fluxsaas** [fnando/i18n-js#59]
Hey,
if i change my i18n backend to 

```
 # config/initializers/i18n_backend.rb
 TRANSLATION_STORE = Redis.new
 I18n.backend = I18n::Backend::Chain.new(I18n::Backend::KeyValue.new(TRANSLATION_STORE), I18n.backend)
```

it throws an 

```
NoMethodError (undefined method `initialized?' for #<I18n::Backend::Chain:0x007fca09d6c920>):
```

error. 

if i remove the i18n.js gem it works fine.... i dont have any more backtrace for debugging...

kalle

ps. nice gem by the way, love it !

**Comment by macbury** [comment]
+1

**Comment by fnando** [comment]
The biggest issue is that backends doesn't have an official public API. My recommendation with custom backends (anything other than simple or gettext) is to wrap it in your own custom backend. Then you can set it as `I18n.backend = YourCustomBackend`.

The gist is that `I18n.backend.send(:translations)` must return anything you'd like to be available.
