### ISSUE TITLE
defaultSeparator is not working

### ISSUE THREAD

**Issue by XI1914-kshitijtiwari** [fnando/i18n-js#594]
I want to change defaultSeparator from "." to something else, but it is not showing any result but still . is used as separator.

**Comment by PikachuEXE** [comment]
Please provide more details on your setup, expected and actual results
Would be good if you can also provide example code that can be executed in browser
e.g. Setup translation values & options manually & print out result

**Comment by anisfrontmen** [comment]
should work like this : 

`import I18n from 'i18n-js';
I18n.defaultSeparator = '_'`

**Comment by XI1914-kshitijtiwari** [comment]
My code was--

    import I18n from "react-native-i18n";
    import EN from "../locales/EN";
    import HIN from "../locales/HIN";
    
    I18n.fallbacks = true;
    I18n.missingBehaviour = "guess"; // It will convert HOME_noteTitle to "HOME note title" if the value of HOME_noteTitle doesn't exist in any of the translation files.
    I18n.defaultLocale = "EN"; // If the current locale in device is not en or hi
    I18n.locale = "EN"; // If we do not want the framework to use the phone's locale by default
    I18n.defaultSeparator = '_'
    I18n.translations = {
      EN,
      HIN,
    };


    export default I18n;

But it was not working. Even I tried to change in module file but no luck.

**Comment by PikachuEXE** [comment]
Here my version of test script modified from yours
No import of i18n (every test env got its own way to load I18n) nor translations
```js
I18n.fallbacks = true;
I18n.missingBehaviour = "guess"; // It will convert HOME_noteTitle to "HOME note title" if the value of HOME_noteTitle doesn't exist in any of the translation files.
I18n.defaultLocale = "en";
I18n.locale = "en";
I18n.defaultSeparator = '_';
I18n.translations = I18n.translations || {};
I18n.translations["en"] = {
  test: {
    key: "Test Value"
  }
};

console.log(I18n.t("test_key"))
```

I ran this on my project with I18n JS loaded
It does output what I expected it to output

![image](https://user-images.githubusercontent.com/1018543/109242885-dd290a00-7816-11eb-9fa7-c34c996986a7.png)

Can you try this and post back the results?
And let me know if there is anything incorrect in my test script
