### ISSUE TITLE
How to show a different message based on the user gender?

### ISSUE THREAD

**Issue by jozueconz** [fnando/i18n-js#596]
I am somewhat confused if this library is related to this page: http://i18njs.com/#contexts

I want to display a different message based on the gender of the user as in the example from the link above but I cannot achieve it...

**Comment by PikachuEXE** [comment]
Your provided page is linked to this package on NPM: 
https://www.npmjs.com/package/roddeh-i18n
See the link `NPM` on your provided page

For this project/library you will have to handle what entry to be used with your own code.
