### ISSUE TITLE
Check for missing translations

### ISSUE THREAD

**Issue by jancoow** [fnando/i18n-js#599]
Is there a tool to check if all requested translation keys in an application are defined in all translation files? I want to add this to our build pipeline so we don't miss any translations. It would also be great if unused keys in a translation file could be tracked, so we can cleanup unused translations.

**Comment by PikachuEXE** [comment]
I think you will have to use a custom function on
[`I18n.missingTranslation`](https://github.com/fnando/i18n-js/blob/v3.8.1/app/assets/javascripts/i18n.js#L675-L684) to report back missing translation keys

I don't think there is a tool for unused translations
There is one for Ruby but I am not sure how it works nor whether it's accurate: 
https://github.com/glebm/i18n-tasks

**Comment by jancoow** [comment]
While using the missingTranslation function is great for reporting back on runtime, I would rather find missing translations beforehand. I've looked at i18n-task but didn't really understand how use it with a javascript project.

**Comment by PikachuEXE** [comment]
I think that would be source code analyse level task and I doubt it's a simple task
Not to mention including such function in this library

**Comment by jancoow** [comment]
It would indeed be a code analyse task. For bigger applications it's hard to track if a translation is missing for a certain language or all languages.
