### ISSUE TITLE
Question: per Engine translations

### ISSUE THREAD

**Issue by brauliobo** [fnando/i18n-js#601]
We have a big application with 3 big engines, each of them with specific translations. How can I split the `//=require i18n/translations` to avoid mixing engines' translations? Our current translations.js file has 1.4mb due to being mixed

**Comment by PikachuEXE** [comment]
I have never used multi engine application.
Would be good to know how the application / the 3 engines are using the translations now.

**Comment by fnando** [comment]
@brauliobo can you please make a sample app with a similar configuration (engines with specific translations) available somewhere? 

I'm going to close this ticket for now, but feel free to reopen it once you've done that.

**Comment by brauliobo** [comment]
@fnando each engine has a `config/locales` directory with it own translations. On the rails app that joins them all together the `translations.js` get very big with all translations from all engines at the same time.

So I need a way to generate a `translation.js` with a specific scope (it engine scope translation in its own key)
