### ISSUE TITLE
Translation broken when there's full stop in between text

### ISSUE THREAD

**Issue by TommyLeong** [fnando/i18n-js#602]
In short, we wrap the `i18n.t()` in a helper with a method `translation.t("")`. Within the helper it gets the user preferred language and perform translation. Something I realized is that, the **translation breaks when my translation string includes 'full stop'** in between text.

**Broken translation**
translation.t("Hi. My name is")

**Working translation**
translation.t("Hi!@#$?")translation.t("My name is")
translation.t("Hi! My name is )(*@#&$")

Has anyone face this issue? Any solution to fix this issue? 

Sample debug within app with test string `okok. okok`

- I do have translation for `okok. okok` in my translation mapping

![Screenshot 2021-04-20 at 10 58 05 PM](https://user-images.githubusercontent.com/9990179/115418723-4aac5200-a22c-11eb-9a53-d584f8b00f88.png)

**Comment by TommyLeong** [comment]
Tagging @PikachuEXE, I believe you will have the answer or be able to guide me further. Thanks!

**Comment by PikachuEXE** [comment]
I think not all options for the JS library are documented well (or even documented)

There is an option `defaultSeparator` which can be set globally (`I18n.defaultSeparator = newVal`)
https://github.com/fnando/i18n-js/blob/v3.8.2/app/assets/javascripts/i18n.js#L181

Or you can pass option `separator` on some `I18n.t` calls only

**Comment by PikachuEXE** [comment]
Just added a section about this option
https://github.com/fnando/i18n-js#option-defaultseparator-global--separator-local

Let me know if anything unclear

**Comment by TommyLeong** [comment]
Hello @PikachuEXE , if I understand you correctly what you have showed in README `I18n.t("full_sentences|Server Busy. Please retry later", {separator: '|'}) `

You are trying to replace the default separator of `.` to `|`. Hence the remaining sentence of "Server Busy. Please retry later" will get translated? 

I tried to follow what you did, but still I don't manage to translate as long as there's a full-stop in between text.
``I18n.t("full_sentences| Hi. My name is", {separator: '|'}) `` Can you point out what is incorrect here?

**Comment by PikachuEXE** [comment]
I have tested this method before posting.

![image](https://user-images.githubusercontent.com/1018543/115640362-56da0180-a349-11eb-8425-e5b5c7dc3a83.png)

You can run the code to see what happen with your setup.
You can inspect the translation object / update the translation key in `I18n.t` etc. to observe the results.

```js
I18n.locale = "en"
I18n.translations["en"].full_sentences = {"Server Busy. Please retry later": "Server Busy !!!"}
I18n.t("full_sentences|Server Busy. Please retry later", {separator: '|'})
```

You can also prepare an example code that would reproduce the issue you mentioned.

**Comment by TommyLeong** [comment]
Thanks @PikachuEXE, your example does solve the issue. 🙇‍♂️
