### ISSUE TITLE
Passing locale on JavaScript side 

### ISSUE THREAD

**Issue by pavanjoshi914** [fnando/i18n-js#603]
I am trying to integrate i18n-js with rails following webpacker instructions. 

I need idea in passing locale on some of the files

I have  ```simulator``` pack created using webpacker which serves javascript files present in ```/simulator/src``` 

I am able to get current locale info in ```simulator.erb``` following  given instructions but failing to get current locale info in JS files present in ```simulator.src```, it always stucks to 'en' 

here is the screenshot of output of locale from one of the js file present in simulator/src and simulator.erb
value of ```CurrentLocale()``` differ in both the files value in js files is always stucked to 'en' and gives translation missing error when locale is changed i.e en.hello missing translation

![Screenshot from 2021-05-09 12-15-33](https://user-images.githubusercontent.com/55848322/117562969-5cad4200-b0c0-11eb-976e-a16239de6b0f.png)

here is the repo link : https://github.com/pavanjoshi914/CircuitVerse

Thanks in Advance

**Comment by pavanjoshi914** [comment]
instructions followed:root
https://gist.github.com/bazzel/ecdff4718962e57c2d5569cf01d332fe

locale passing:
```
<%# app/views/layouts/simulator.html.erb %>

<script type="text/javascript">
  I18n.defaultLocale = "<%= I18n.default_locale %>"
  I18n.locale = "<%= I18n.locale || I18n.default_locale %>"
</script>
```
however it didn't worked unless  ```require //= i18n/translations``` where added in ```app/assets/javascripts/simulator.js``` and include that file using ```javascript_include_tag```

in  <%# app/views/layouts/simulator.html.erb %>
```<script type="text/javascript">
     console.log(I18n.currentLocale());
</script>

Output:  ja  (works fine - gives value according to the locale changed)
```

in <%# simulator/src/CombinationalAnalysis.js %>
```
 console.log(I18n.currentLocale());

Output: en (always , which result in missing transaltion error when locale is changed )
```

setup:
we have a simulator pack which serves all the JS files present in directory  ```simulator/src ```

**Comment by PikachuEXE** [comment]
Which branch contains the I18n changes?
I am unable to find code like `require //= i18n/translations` or `I18n.defaultLocale = "<%= I18n.default_locale %>"` in `master` branch
You can take a look at [my current I18n setup with webpacker](https://github.com/fnando/i18n-js/issues/581#issuecomment-686863166)

**Comment by pavanjoshi914** [comment]
> Which branch contains the I18n changes?
> I am unable to find code like `require //= i18n/translations` or `I18n.defaultLocale = "<%= I18n.default_locale %>"` in `master` branch
> You can take a look at [my current I18n setup with webpacker](https://github.com/fnando/i18n-js/issues/581#issuecomment-686863166)

Thanks for assisting ,
If possible, please have a look on it https://github.com/pavanjoshi914/CircuitVerse/commit/835af71d0d8e04eb067530d2ac7a426c6077e39f


where i have to use import  based code and what is the ```:javascript``` do that code is based on any plugin not much familiar with it.
Thanks in advance

**Comment by pavanjoshi914** [comment]
simulator.js (asset file)
https://github.com/pavanjoshi914/CircuitVerse/blob/835af71d0d8e04eb067530d2ac7a426c6077e39f/app/assets/javascripts/simulator.js  
simulator.html.erb
https://github.com/pavanjoshi914/CircuitVerse/blob/835af71d0d8e04eb067530d2ac7a426c6077e39f/app/views/layouts/simulator.html.erb
conflicting js file where locale value is always 'en'
https://github.com/pavanjoshi914/CircuitVerse/blob/835af71d0d8e04eb067530d2ac7a426c6077e39f/simulator/src/combinationalAnalysis.js

translation export  
https://github.com/pavanjoshi914/CircuitVerse/blob/835af71d0d8e04eb067530d2ac7a426c6077e39f/config/i18n-js.yml

**Comment by PikachuEXE** [comment]
In the layout, this line is run first:
```
<%= javascript_pack_tag 'simulator', 'data-turbolinks-track': 'reload' %>
```
So the `I18n.locale` is still not touched by the `script` block below
After `script` block `window.I18n.locale` is set
Therefore it's expected output, and won't help finding the cause of issue.

You should be testing whether the `I18n` object in `simulator/src/combinationalAnalysis.js` is updated by the `script` block.
This can be done by adding a `console.log(I18n.currentLocale());` before you call any `I18n.t` to see what locale is set.
e.g. before line https://github.com/pavanjoshi914/CircuitVerse/blob/835af71d0d8e04eb067530d2ac7a426c6077e39f/simulator/src/combinationalAnalysis.js#L32

**Comment by pavanjoshi914** [comment]
Yup!!  I tried to change the load order of the script by putting it  at the top and above ```javascript_pack_tag``` but didn't worked.

actually things in the  ```simulator.html.erb (layot)``` are working because of the line 
 ```I18n.locale = "<%= I18n.locale || I18n.default_locale %>"```

![2021-05-11_15-58](https://user-images.githubusercontent.com/55848322/117802838-91152f80-b273-11eb-8eac-8d31c9285569.png)


If I remove this line ```I18n.locale``` value always corresponds to ```en```  in layot also


I also tried to use ```I18n.locale = "<%= I18n.locale%>"``` in ```index.js.erb``` but value of ```I18n.locale``` always  corresponds to```en``` (I wasn't expecting that)

unfortunately I18n object is not updating after locale change in ```simulator/src/combinationalAnalysis.js```
![2021-05-11_16-00](https://user-images.githubusercontent.com/55848322/117803095-dc2f4280-b273-11eb-9971-c7c8323a6d96.png)

I checked this by setting breakpoint at ``` console.log(I18n.currentLocale()); ``` in layot as well as in combinationalAnalysis.js object is getting updated in layot but not for JS file 
Any Idea what I can do for this case?
you can see new changes here https://github.com/pavanjoshi914/CircuitVerse/commit/9f4fdf6fcc00567e14f58d4a024bbb9fb65aa51b
Thanks in advance

**Comment by PikachuEXE** [comment]
If you look at [my current I18n setup with webpacker](https://github.com/fnando/i18n-js/issues/581#issuecomment-686863166)
You can see that I import the `I18n` object, then update its `locale` & `defaultLocale` with what's set in `window.I18n`
You can try that in `combinationalAnalysis.js`

If this works, it probably means the `I18n` object on `window` and `I18n` imported from `i18n-js/index.js.erb` are different objects

**Comment by pavanjoshi914** [comment]
It perfectly works !! 
Now the only thing is using such a code in every JS file is expensive and needs more modularity

**Comment by pavanjoshi914** [comment]
Reference for those who encounter similar problem

 ```window.I18n``` and ```I18n from i18n-js/index.js.erb``` are different objects so we have to explicitly update locale value of I18n object exported by ```i18n-js/index.js.erb```

same can be done using following piece of code in index.js.erb
```
if (typeof window.I18n.locale === "string") {
   I18n.locale = window.I18n.locale
 }
```

@PikachuEXE  thankyou for assisting me to solve this issue :smiley:

**Comment by PikachuEXE** [comment]
You just need to find a module / index file with `import I18n` 
and update the imported `I18n` once only

**Comment by pavanjoshi914** [comment]
yes done accordingly!!!

**Comment by pavanjoshi914** [comment]
@PikachuEXE  I want to setup I18n-js without using asset pipeline 

when I use ```  <%= javascript_include_tag "i18n" %>
<%= javascript_include_tag "translations", skip_pipeline: true %>```
It generates error assets are not precompiled  I tried ```rake tmp:clear``` but its not working

Before this I was using asset pipeline 
in a particular asset file (simulator.js) ```// = require i18n```
and in layot file ```javascript_include_tag  simulator```


any opinion on this ?

Thanks in advance!!

**Comment by pavanjoshi914** [comment]
Hii @PikachuEXE  
we are planning to decouple our simulator (js files with webpacker setup) from the backend ( Rails )
in current setup we are facing problems because of use of Rails things in the setup such as

1. Use of index.js.erb  for setup and passing locale info on front end along with ``` <%= I18n::JS.filtered_translations.to_json %>```
2. user of rails-erb-loader .
3. rake commands for importing and exporting translations. 
4. use of middle ware in application.rb

here is the link for current setup: https://github.com/CircuitVerse/CircuitVerse/pull/2266

can you share me some information about best possible way to setup i18n-js which is mostly independent on Rails backend and more on JS

Thanks in advance :star:

**Comment by PikachuEXE** [comment]
`setup i18n-js which is mostly independent on Rails backend and more on JS`

Where do you plan to store the translations?
I can't even think of anything without more details on your requirements 😅

**Comment by pavanjoshi914** [comment]
we are currently storing in yml and exporting  it into js  via rake command.

here is the current setup  [setup](https://github.com/CircuitVerse/CircuitVerse/pull/2266) which is using rails erb loader to integrate it with webpacker

**Comment by pavanjoshi914** [comment]
For loading up translations without the line ```<%= I18n::JS.filtered_translations.to_json %>``` I am trying to use yml and json loader to dump yml into json object. (currently I am  exporting them into js via rake command and loading them via erb file using the above line)

any efficient solution in your mind for this to eliminate use or index.js.erb file and rails erb loader dependency  from setup 

along with elimination of use of middleware line in backend and use of rake commands to generate translations eg: ```rake i18n:js:export```

**Comment by PikachuEXE** [comment]
[My current setup](https://github.com/fnando/i18n-js/issues/597#issuecomment-794776636) is loading translation via using middleware but only using `I18n::JS.filtered_translations.to_json` in an `erb` file.
I have never used a loader to load translations directly so I don't think I can give you and suggestion. Sorry for that.
