### ISSUE TITLE
Pluralization: "returned an object instead of string."

### ISSUE THREAD

**Issue by AlexandreMouyen** [fnando/i18n-js#604]
Hello there,

I am trying to implement the Pluralization part of readme
![image](https://user-images.githubusercontent.com/27637370/117630883-ef5ee700-b17b-11eb-9e10-68d8ae23281a.png)

When I am doing this, I have the "key 'search.map.results_title (en-GB)'  returned an object instead of a string."
![image](https://user-images.githubusercontent.com/27637370/117631266-58465f00-b17c-11eb-867b-6eacb6692185.png)

My translantion file:
```js
search: {
    where: {
      placeholder: 'Where? (city)',
      current_position: 'Current position',
      recent: 'Recent',
      suggestions: 'Suggestions',
    },
    what: {
      title1: 'What',
      title2: 'are you',
      title3: 'looking?',
    },
    map: {
      results_title: {
        one: 'A {{job}} found',
        other: '{{count}} {{job}} found',
        zero: 'No {{job}} found',
      },
    },
  },
```
Did I do something wrong?

Greetings.

**Comment by PikachuEXE** [comment]
Try something like `search.map.results_title.one` to see if the library can find the entry
Also try creating new entry group and use `count` on it. For example:
```
I18n.translations["en"]["test"] = {"one": "I am one", "zero": "I am zero", "other": "I am other"}
I18n.locale = "en"
I18n.t("test", {count: 1})
I18n.t("test", {count: 0})
I18n.t("test", {count: 2})
```

![image](https://user-images.githubusercontent.com/1018543/117634427-7aa69f80-b1b1-11eb-9c18-5d1568ea08c5.png)

**Comment by sregg** [comment]
I've recently seen this issue when `count` is `null` (or `undefined`).
