### ISSUE TITLE
Android build failed due to static minSdkVersion in AndroidManifest

### ISSUE THREAD

**Issue by sachdewaniavinash** [fnando/i18n-js#611]
1. React Native Version :  0.63.2
2. i18n Version:  2.0.15
3. buildToolsVersion: 28.0.3
4. compileSdkVersion: 28
5. gradle version : 4.2.1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVital.
> Lint infrastructure error

 Caused by: com.android.builder.errors.EvalIssueException: Failed to parse XML in /Users/runner/work/1/s/node_modules/react-native-i18n/android/src/main/AndroidManifest.xml
  The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
 
![image](https://user-images.githubusercontent.com/85228566/120467654-f96ab300-c3d2-11eb-98f0-161fda00617c.png)

Please let me know if you any other information required.

**Comment by PikachuEXE** [comment]
I have no idea why this issue is caused by this library.
I don't know how to to start investigating as I can't even reproduce the issue.
Reported in `react-native-i18n`?

**Comment by sachdewaniavinash** [comment]
Thanks @PikachuEXE.
I checked the react-native-i18n which is deprecated.

**Comment by SanskarDahiya** [comment]
> I have no idea why this issue is caused by this library.
> I don't know how to to start investigating as I can't even reproduce the issue.
> Reported in `react-native-i18n`?

I am getting this issue by moving to SDK 30 from SDK 29 in React-Native App.
Can you tell what show I do to resolve/compress this?

**Comment by SanskarDahiya** [comment]
@sachdewaniavinash 
Thanks, I was wondering why [npm](https://www.npmjs.com/package/react-native-i18n) doesn't mark this library deprecated. [Here](https://www.npmjs.com/package/react-native-i18n).

Although, I might apply a patch in react-native-i18n, instead of using another module.

BTW, Thanks to inform me that this library is deprecated.
