### ISSUE TITLE
Is the library supporting changing language?

### ISSUE THREAD

**Issue by Motazlubbad** [fnando/i18n-js#614]
Hello,
I have two different language files, and I would like to let the user changing between these languages?
Is the library supporting this feature?

My Project is a react-native project 

Thank you

**Comment by PikachuEXE** [comment]
I can't understand your description of the project setup.
I won't be able to answer your question without enough understanding on your setup & requirements (let the user changing between these languages).

**Comment by 15110011** [comment]
current locale: 'en'
and then I changed locale hand defaultLocale but it was not updating
I18n.locale = 'de'
I18n.defaultLocale = 'de' 

then close and turn on app again
console.log(I18n.locale or RNLocalize.getLocales())
// en

* version: "i18n-js": "^3.2.2",
*  "react-native": "0.60.6",

**Comment by PikachuEXE** [comment]
I don't know anything about react native 
But I assume that value need to be saved separately and restored to `I18n` object on app reboot/resume
This project would not take care of locale preference persistence

**Comment by michelson** [comment]
in react context the translations will not be automatically updated if that's what you mean.
instead, you will need a mechanism to reload the translations for example useState on locale then reload somehow the component

```js
changeState(lang){
   setLoading(true)
   I18n.locale = lang
   setLoading(false)
}
```
render

```
return (
!loading && <MyApp />
)
```
