### ISSUE TITLE
How to generate translations for locales which are not in the  I18n.available_locales

### ISSUE THREAD

**Issue by avokhmin** [fnando/i18n-js#615]
Hello!

> If you can't or prefer not to generate this file, you can move the middleware line to your config/environments/development.rb file and run rake i18n:js:export before deploying. This will export all translation files, including the custom scopes you may have defined on config/i18n-js.yml. If I18n.available_locales is set (e.g. in your Rails config/application.rb file) then only the specified locales will be exported. Current version of i18n.js will also be exported to avoid version mismatching by downloading.

How can I add extra locales which are not presented in the `I18n.available_locales`.

User case: we have the site in EN/JP, but in JS widgets we would like to use more locales.

Something like:

```
config/i18n-js.yml

translations:
  - file: "public/javascripts/translations.js"
    only: "*.js.*"
```

```
> I18n.available_locales
=> [:en, :jp]
> I18n::JS.backend.available_locales.first(4)
=> [:en, :cs, :tr, :"pt-BR"]
```

**Comment by PikachuEXE** [comment]
I think right now it's all "hardcoded" to use `I18n.available_locales`

How do you generate/pull the translations at the moment? 
I can write some patch code for your use case first.

**Comment by avokhmin** [comment]
> I think right now it's all "hardcoded" to use `I18n.available_locales`
> 
> How do you generate/pull the translations at the moment?
> I can write some patch code for your use case first.

@PikachuEXE  we use `v2.1.2` as TMP solution :)

**Comment by avokhmin** [comment]
@PikachuEXE I suppose that https://github.com/fnando/i18n-js/pull/547 can help, but need to test. What do you think?

**Comment by PikachuEXE** [comment]
I think #547 is not good enough

`I18n.available_locales` should be the default and we can update the gem to allow custom `available_locales`
What do you think?

**Comment by avokhmin** [comment]
> and we can update the gem to allow custom `available_locales`
> What do you think?

@PikachuEXE I like this idea!

**Comment by avokhmin** [comment]
@PikachuEXE do you have a plan to implement it? Or I can try to do it...

**Comment by PikachuEXE** [comment]
Please submit a PR for it
Thx
