### ISSUE TITLE
v4's "listen" mode only refreshes once at most

### ISSUE THREAD

**Issue by harigopal** [fnando/i18n-js#616]
When using the v4 alpha version, with it set up to automatically export translations _using listen_, the translations output file will only get updated once. All further changes to source files are ignored.

**To Reproduce**
1. Clone https://github.com/fnando/i18n-js-examples
2. Run `rails s` in the `rails-webpacker` folder (after adding `bin/*` files, which are missing, for some reason).
3. Edit the `en.yml` file - the output `locales.json` will be updated.
3. Edit the `en.yml` file again - the output `locales.json` will remain the same. All further edits are ignored.

**Additional context**
I spent some time digging into this, and was able to fix it by editing the `I18nJS.translations` method to _always_ initialize translations. It appears that `I18n` has some kind of caching built into it. However, I can't explain why the first attempt to change succeeds while the subsequent ones fail.

Forcing `init_translations` appears to fix this issue:

```rb
module I18nJS
  def self.translations
    ::I18n.backend.send(:init_translations)
    ::I18n.backend.send(:translations)
  end
end
```

However, I'm uncertain whether this is the correct approach for all circumstances.

I also believe this issue will pop up when _using guard_ as well, since the caching appears to happen inside `I18n`.

**Comment by fnando** [comment]
Sorry for over sighting this issue. It has been fixed on 9e8d432aa1375aed34d0085f6db3926434b2ac8e.
