### ISSUE TITLE
v4, export on envs on precompile (without database)

### ISSUE THREAD

**Issue by michelson** [fnando/i18n-js#618]
Hello @fnando, first of all, thanks for this project.
I'm into the upgrade of this gem and in my deployment process I build a docker image, this build does not have a database created on build time.

I've done this in my precompile task:

``` ruby
namespace :locales do
  desc "compile i18n before compile"
  task :build do
    system('yarn i18n:export')
  end
end

# Run yarn i18n:export prior to assets precompilation, so i18n json are available for use.
Rake::Task['assets:precompile'].enhance [ 'locales:build' ]
```
this works great in local dev env but since the export loads the rails env it crashes on Docker image build because there is no database connection made. For now, I guess I will have to compile the files by hand and then commit them to the repo.

question: is really needed to load the rails env ? could be possible to optionally skip the rails environment?

thanks

**Comment by fnando** [comment]
You can definitely load only what you need by using `i18n export -r ./custom_file.rb`, where `custom_file.rb` can be something like this:

```ruby
# frozen_string_literal: true

require "bundler/setup"
require "rails"
require "active_support/railtie"
require "action_view/railtie"

I18n.load_path += Dir["./config/locales/**/*.yml"]
```

Notice that loading activesupport and actionview may be optional depending on what you're using. I'll add a note to the troubleshooting section with this info.
