### ISSUE TITLE
TypeError: Cannot read property 'createTranslationOptions' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by dika4152** [fnando/i18n-js#619]
Hi @fnando , I was working in a project that translation between ID and EN.

on the first time I run the project in the branch that i'm working on, It works fine. and then my co-worker is pushing to develop branch. and I am fetching and merging that branch to mine.

after that I am getting this error

```
TypeError: Cannot read property 'createTranslationOptions' of undefined, js engine: hermes
```

I found out that createTranslationOptions is created and used in translate function. but I can understand why it is undefined suddenly.

Here is the project dependencies that I am working on :
```
...
"@types/i18n-js": "^3.8.1",
"i18n-js": "^3.8.0",
"libphonenumber-js": "^1.9.24",
"react": "17.0.1",
"react-native": "0.64.2",
...
```

Please let me know if you have any idea what is going on. It's a good library and helpful btw.

**Comment by dika4152** [comment]
I am sorry, I already found out what the cause

**Comment by shivani-dish** [comment]
@dika4152 I am facing this exact issue. I will need your help in figuring out the cause. TIA.
