### ISSUE TITLE
v4 translations are removed when server starts

### ISSUE THREAD

**Issue by michelson** [fnando/i18n-js#622]
### Discussed in https://github.com/fnando/i18n-js/discussions/621

<div type='discussions-op-text'>

<sup>Originally posted by **michelson** August 26, 2021</sup>
Hello, 
I've integrated the v4 in [our app](https://github.com/chaskiq/chaskiq), and we see that when the server starts (dev env), the JSON translations are emptied. 
How can we avoid this? have you seen this behavior?

thanks</div>

**Comment by fnando** [comment]
Closed via #631
