### ISSUE TITLE
Change locale on JS (Vue)

### ISSUE THREAD

**Issue by SananMaarouf** [fnando/i18n-js#627]
Hi , i have an issue that is very similar to #581 where the translation won't change. 
But their solution does not work on mine for some reason.  
I am trying to get it to work on a Rails application that uses Vue, Webpacker and Slim templating language.  I have tried to install with the webpacker, asset pipeline and non-asset pipeline method with varying degrees of success. So far the non-asset pipeline method works with the default locale only.
So far i have gotten it to export all my YML files into different files (en.js, nb.js).
It is stuck on the default language that i have specified in the ruby side and in the i18n.js, even if i change the locale to english via rails console or the browser url `?locale=en`.

Translations are in 
`public/javascripts/translations.js`
i18n.js file is in
`public/javascripts/i18n.js`
```
  var DEFAULT_OPTIONS = {
      defaultLocale: "nb"
    , locale: "nb"
```
Available languages in `application.rb`
```
    config.i18n.enforce_available_locales = false
    config.i18n.available_locales = [ :nb, :en ]
    config.i18n.default_locale = :nb
```
Vue component
```
<template lang="pug">
.page-header.justify-content-between.w-100
  h3 {{t("action_programs")}}
</template>
<script>
import {i18n} from "mixins/i18n_mixin.js"
export default {
  mixins: [i18n],
}
</script>

```
This is the mixin that i use for the Vue component
```
export const i18n = {
  methods: {
    t: (...args) => I18n.t(...args),
    currentLocale: () => I18n.currentLocale(),
  },
};
```
`app/assets/javascripts/application.js`
```
//= require i18n
//= require i18n.js
//= require i18n/translations
```
And i have the following include tag in my layout file
```
= javascript_include_tag "i18n"
= javascript_include_tag "translations", skip_pipeline: true
  javascript:
    console.log(I18n.currentLocale());

```
I have seen how you solve this with your own javascript but i am not sure where to put it

**Comment by PikachuEXE** [comment]
You need a code that sets the locale from HTML/URL/whatever
As for "where to put it"
You can put it in HTML (but depends on how you load JS it might not work)
You can put it in JS common setup code (which I am not sure if you have it)
I don't use Vue.js so I am not sure if there is any special setup around it
