### ISSUE TITLE
Add an option to show positive sign of a number

### ISSUE THREAD

**Issue by NoZiL** [fnando/i18n-js#632]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `i18n-js@3.8.0` for the project I'm working on.

I had to implement an account balance (debit and credits) and wanted to use this lightweight i18n library to achieve this. Everything works well except when you want to show the positive sign of a number, in my case showing `+` in front of credit lines and `−` in front of debits (the latter is already covered as we always show a negative sign for a negative number). I did a small enhancement with patch-package, I can push my work on a PR if you are interested by it, and I will gladly accept feedback regarding to the naming of the option hesitated between `always_show_sign` or `show_positive_sign`. IMHO this option could also be applied to `toPercentage` and `toHumanSize`
Otherwise this will serve as a reference if other people are facing this particular issue :).

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/i18n-js/app/assets/javascripts/i18n.js b/node_modules/i18n-js/app/assets/javascripts/i18n.js
index 890192d..69db0ae 100644
--- a/node_modules/i18n-js/app/assets/javascripts/i18n.js
+++ b/node_modules/i18n-js/app/assets/javascripts/i18n.js
@@ -146,6 +146,7 @@
     , separator: "."
     , delimiter: ","
     , strip_insignificant_zeros: false
+    , positive_sign: ""
   };
 
   // Set default currency format.
@@ -707,6 +708,7 @@
   // - `separator`: `"."`
   // - `delimiter`: `","`
   // - `strip_insignificant_zeros`: `false`
+  // - `show_positive_sign`: false
   //
   // You can also override these options by providing the `options` argument.
   //
@@ -724,7 +726,8 @@
       , buffer = []
       , formattedNumber
       , format = options.format || "%n"
-      , sign = negative ? "-" : ""
+      , positive_sign = options.show_positive_sign ? '+' : ''
+      , sign = negative ? "-" : positive_sign
     ;
 
     number = parts[0];
@@ -773,6 +776,7 @@
   // - `format`: `"%u%n"`
   // - `delimiter`: `","`
   // - `separator`: `"."`
+  // - `show_positive_sign`: false
   //
   // You can also override these options by providing the `options` argument.
   //
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by PikachuEXE** [comment]
I can go with `show_positive_sign`
But let's see if @fnando has any opinion on it
As there is a v4 in development and I am not sure about his plan

**Comment by NoZiL** [comment]
I've seen the v4 after that yes :). And @fnando did implement this feature in v4, a bit differently be passing a `format` and `negativeFormat` in the `FormatNumberOptions`.
[  const format = isNegative && !isZero ? negativeFormat : positiveFormat;](https://github.com/fnando/i18n/blob/7ffa8e3e41139032785cb31b3692ce90fe27ddb5/src/helpers/formatNumber.ts#L62)
https://github.com/fnando/i18n/blob/7ffa8e3e41139032785cb31b3692ce90fe27ddb5/src/typing.ts#L48
I've just this this amazing lib showcased in expo docs, I'll give the `v4` a go sometimes later on.

**Comment by PikachuEXE** [comment]
Beware you need to pass both `format = "+%n"` and `negativeFormat = "-%n"` to make it work properly
But ya it's implemented
Since we can't change the existing implementation too much in v3
Having `show_positive_sign` would be fine (until v4)
Do you want to submit a PR for that?

**Comment by fnando** [comment]
We should not add any new feature to v3.

I'm planning on releasing v4 soon (I've been using it in a few projects without any glitches). If you need to keep using v3, I'd recommend extending I18n locally on your project.
