### ISSUE TITLE
Feature Request: Change except example in README

### ISSUE THREAD

**Issue by ramirolopescanadell** [fnando/i18n-js#642]
## Description

The **except** example in the README is not very clear.
The way the **except** worked for me is without the `-` (as it is in the "only" example)

## Describe the solution
Maybe change the README from 
```
translations:
    - except: ["*.active_admin", "*.ransack", "*.activerecord.errors"]
```
to
```
translations:
  - file: "public/javascripts/i18n/%{locale}.js"
    except: ["*.active_admin", "*.ransack", "*.activerecord.errors"]
```

## Alternatives you considered

Add the new example without removing the old one.

## Additional context

Using the `- except` (with a `-` ) under the **file** key gave me an unintuitive error. It took us a while to discover that the except must be used without the `-`. Maybe adding this to the README will save someone else some time!
Thanks

**Comment by PikachuEXE** [comment]
The main branch is now v4 (unreleased)
I guess you mean v3?
