### ISSUE TITLE
I18n.localize changes the argument time zone

### ISSUE THREAD

**Issue by rgaufman** [fnando/i18n-js#647]
## Description

Before upgrading to Rails7, everything was working as expected, but now it seems I18n.localize takes the browser time_zone instead of the one I pass to it:

## How to reproduce

```
I18n.localize('date.formats.events_time_format',  "2022-04-24T15:00:00.000Z")
```

## What do you expect

I expect to see 15:00:00 like I did with Rails 6 (currently on Rails 7)

## What happened instead

I see 16:00:00, which I suspect is because we are in summer time (BST) and maybe this is what the Browser is passing?

## Software:

- Gem version: 3.3.11
- Ruby version: [ruby 3.1.2p20

**Comment by PikachuEXE** [comment]
I have no idea why rails version would affect this project's code

I traced the method call to [`parseDate`](https://github.com/fnando/i18n-js/blob/v3.9.2/app/assets/javascripts/i18n.js#L834=)

I rarely used `Date` so I have no idea what it's doing inside

**Comment by rgaufman** [comment]
Ah, it's possible the rails version was unrelated and this was just the start of BST (British Summer Time) that coincided with this!

**Comment by PikachuEXE** [comment]
I don't even know what `resource.starts_at.slice(0, -1)` means D:

**Comment by rgaufman** [comment]
I see this issue is closed now, what is the solution to this please?
