### ISSUE TITLE
Feature Request: Adding a digest to the translations filename

### ISSUE THREAD

**Issue by erikaxel** [fnando/i18n-js#650]
## Description

Our translation files amount to approximately 1.5mb as it currently stands. We would like to avoid the user having to download this each time they hit a page. The typical way this is done in Rails is add a digest to the filename, hide it behind a CDN and set a very long TTL. This is mostly handled by Rails behind the scenes. 

The following solution is based on the assumption that using digests behind a CDN is the way to go. If there are any other way to solve this today I would love to hear about it (and suggest that it is added to the readme, happy to help with this).

## Describe the solution
To make this work, we would have to

1. Set some configuration that asks I18n-js to generate filenames with digests
2. Have a way for the backend to communicate the filename to the front-end
3. (optional) Have some helpers on the front end to easily consume digested filenames.

**1. Config**
In `i18n.yml` we could have something like
```yaml
use_digest: true
```

**2. A way to communicate the digest names**
Adding something like 
```erb
<%= I18n.digest_hash %>
```
Which would output a simple hash and make it available:
```javascript
<script>
window.i18n.digests = {
   "translations.json": "translations-d6014965.json",
   // other translation files exported
}
</script>
```
I know this might be a bit counter to the direction i18n is taking, so if there are any better or more standard ways to do this without having to use a global variable on window I would love to hear it. 

**3. Easy way to consume at the front-end**
Add a helper `digestedFileName()` which knows about the global digests hash. You could argue that this is trivial to implement by accessing the hash yourself, so maybe this is not needed. But it does "insulate" the user from the name of the hash and the internal naming of it.
```javascript
import { I18n } from "i18n-js";

const response = await fetch(I18n.digestedFileName("translations.json")`);
const translations = await response.json();
i18n.store(translations);
```

**Comment by PikachuEXE** [comment]
Is this for v3 or v4?
I don't recall seeing `translations.json` in v3 and I have no knowledge on v4 (unreleased)

**Comment by erikaxel** [comment]
This is for v4.

**Comment by PikachuEXE** [comment]
Labels added :)

**Comment by fnando** [comment]
Notice that v4 is not going to receive new features anymore, but I added this to v5.

https://github.com/fnando/i18n-js/commit/cf6b39046ca6faa1ff52d1e9e1399b548f24c47a
