### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by kbanta11** [fnando/i18n-js#670]
## Description

No javascript files are being added when running `bundle install` or `gem install` with this gem and I am getting `Sprockets::FileNotFound couldn't find file in 'i18n'` on my call `//= require i18n` (have also tried `//= require i18n.js`. This seems to make sense because looking int my `vendor/assets/javascripts` (or anywhere else in my project file structure).

## How to reproduce

add i18n to gemfile and run `bundle install`, try to `//= require` it in sprockets `assets/javascripts/application.js`

- Gem version: 4.0.1
- Ruby version: 2.7.2

**Comment by fnando** [comment]
JavaScript files aren't exported anymore on v4 and must now be imported by using the [npm package](https://www.npmjs.com/package/i18n-js).
