### ISSUE TITLE
Bug: deep sorting for keys missed

### ISSUE THREAD

**Issue by oleksii-leonov** [fnando/i18n-js#691]
## Description

In `v3`, localization keys were deeply sorted:
https://github.com/fnando/i18n-js/blob/4b07b30e8b6f42c4415f4bb967e8e2986a0e2268/lib/i18n/js/utils.rb#L68

It's useful to guarantee that exported JSON files would be byte-to-byte equal.

## How to reproduce

Export JSON localization with `v4`.

## What do you expect

Same behavior as `v3`, with deeply sorted localization keys.

## What happened instead

Localization keys are not sorted.

## Software:

- Gem version: 4.2.1
- Ruby version: 3.1.3

**Comment by oleksii-leonov** [comment]
I am not sure that deep keys sorting should be in the core.
Adding it as a default plugin could be good enough.

```ruby
# frozen_string_literal: true

module I18nJS
  require "i18n-js/plugin"

  class SortKeysPlugin < I18nJS::Plugin
    module Utils
      # https://github.com/fnando/i18n-js/blob/4b07b30e8b6f42c4415f4bb967e8e2986a0e2268/lib/i18n/js/utils.rb#L68
      def self.deep_key_sort(hash)
        hash.keys.sort_by(&:to_s).each_with_object({}) do |key, seed|
          value = hash[key]
          seed[key] = value.is_a?(Hash) ? deep_key_sort(value) : value
        end
      end
    end

    def transform(translations:)
      return translations unless enabled?

      Utils.deep_key_sort(translations)
    end

    def setup
      I18nJS::Schema.root_keys << config_key
    end

    def validate_schema
      valid_keys = %i[enabled]

      schema.expect_required_keys(keys: valid_keys, path: [config_key])
      schema.reject_extraneous_keys(keys: valid_keys, path: [config_key])
    end
  end
end
```

**Comment by fnando** [comment]
This should definitely be a core, non-removable feature (tbh, I thought I had added it already, but I guess I didn't).
