### ISSUE TITLE
Bug: While trying to resolve module `make-plural` 

### ISSUE THREAD

**Issue by rell1964** [fnando/i18n-js#719]
I've been having this problem for a while and even when I update the library and clean the cache or delete node-module the error always comes back.

While trying to resolve module `make-plural` from file `../node_modules/i18n-js/dist/import/Pluralization.js`, the package `/../node_modules/make-plural/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`../node_modules/make-plural/plurals.mjs`. Indeed, none of these files exist:

  * ../node_modules/make-plural/plurals.mjs(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  *../node_modules/make-plural/plurals.mjs/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)

**Comment by qfdk** [comment]
@rell1964 
Hello,
Try with this :)
https://github.com/fnando/i18n#im-getting-an-error-like-unable-to-resolve-make-plural-from-node-modulesi18n-jsdistimportpluralizationjs
