### ISSUE TITLE
Usage w/ asset pipeline + Heroku possible?

### ISSUE THREAD

**Issue by carhartl** [fnando/i18n-js#81]
Heroku requires

```
config.assets.initialize_on_precompile = false
```

On the other hand i18n-js requires this to be true. Any idea on how to use i18n-js when deploying to Heroku except manually exporting translations before each push...?

**Comment by costa** [comment]
@johnnyshields I've just got back to it, and it kinda worked for me as it should just now (Rails 4.1.9), through second deploy though, will keep an eye on it and report.

**Comment by dhruvasagar** [comment]
So what's the accepted solution / fix / work around for this !?

**Comment by costa** [comment]
So, to conclude (hopefully), it works for me now just as it should, not sure if Heroku has anything to do with the improvement, but the most notable changes on my side are:
```diff
-    i18n-js (3.0.0.rc7)
+    i18n-js (3.0.0.rc8)
-    rails (4.1.7)
+    rails (4.1.8)
-    sprockets (2.11.3)
+    sprockets (2.12.3)
```

**Comment by PikachuEXE** [comment]
I don't think any change in `rails` would cause this
Try switching `i18n` & `sprockets`, can't be sure which one cause it

You might want to try a "solution" provided in #283 too

**Comment by costa** [comment]
@PikachuEXE Umm, just making sure you're not talking to me 'cause I've just reported it *working*.

**Comment by PikachuEXE** [comment]
LOL, didn't read it carefully enough

**Comment by espen** [comment]
Perhaps this is working on Rails 4 but I still have issues on Rails 3. Have to purge CloudFront and Memcache to ensure new assets files are generated.
